export const icons =
[
    ["binary-icon", ["dark-green", "dark-green"], /\.swp$/i, 4],
    ["link-icon", ["medium-blue", "medium-blue"], /\.lnk$/i, 3],
    ["angular-icon", ["medium-red", "medium-red"], /^angular[^.]*\.js$/i, 2],
    ["ant-icon", ["dark-pink", "dark-pink"], /^ant\.xml$|\.ant$/i, 2],
    ["apache-icon", ["medium-red", "medium-red"], /^(?:apache2?|httpd).conf$/i, 2],
    ["apache-icon", ["dark-green", "dark-green"], /\.vhost$/i, 2],
    ["apache-icon", ["medium-green", "medium-green"], /\.thrift$/i, 2],
    ["appcelerator-icon", ["medium-red", "medium-red"], /^appcelerator\.js$/i, 2],
    ["appveyor-icon", ["medium-blue", "medium-blue"], /^appveyor\.yml$/i, 2],
    ["archlinux-icon", ["dark-purple", "dark-purple"], /^\.install$/, 2],
    ["archlinux-icon", ["dark-maroon", "dark-maroon"], /^\.SRCINFO$/, 2],
    ["archlinux-icon", ["dark-yellow", "dark-yellow"], /^pacman\.conf$/, 2],
    ["archlinux-icon", ["light-yellow", "light-yellow"], /^pamac\.conf$/, 2],
    ["archlinux-icon", ["dark-cyan", "dark-cyan"], /^PKGBUILD$/, 2],
    ["archlinux-icon", ["light-yellow", "light-yellow"], /yaourtrc$/i, 2],
    ["backbone-icon", ["dark-blue", "dark-blue"], /^backbone(?:[-.]min|dev)?\.js$/i, 2],
    ["boot-icon", ["medium-green", "dark-green"], /^Makefile\.boot$/i, 2],
    ["bootstrap-icon", ["medium-yellow", "dark-yellow"], /^(?:custom\.)?bootstrap\S*\.js$/i, 2],
    ["bootstrap-icon", ["medium-blue", "medium-blue"], /^(?:custom\.)?bootstrap\S*\.css$/i, 2],
    ["bootstrap-icon", ["dark-blue", "dark-blue"], /^(?:custom\.)?bootstrap\S*\.less$/i, 2],
    ["bootstrap-icon", ["light-pink", "light-pink"], /^(?:custom\.)?bootstrap\S*\.scss$/i, 2],
    ["bootstrap-icon", ["medium-green", "medium-green"], /^(?:custom\.)?bootstrap\S*\.styl$/i, 2],
    ["bower-icon", ["medium-yellow", "medium-orange"], /^(?:\.bowerrc|bower\.json|Bowerfile)$/i, 2],
    ["brakeman-icon", ["medium-red", "medium-red"], /brakeman\.yml$/i, 2],
    ["brakeman-icon", ["dark-red", "dark-red"], /^brakeman\.ignore$/i, 2],
    ["broccoli-icon", ["medium-green", "medium-green"], /^Brocfile\./i, 2],
    ["package-icon", ["light-orange", "light-orange"], /Cargo\.toml$/i, 2],
    ["package-icon", ["dark-orange", "dark-orange"], /Cargo\.lock$/i, 2],
    ["chai-icon", ["medium-red", "dark-red"], /^chai\.(?:[jt]sx?|es6?|coffee)$/i, 2],
    ["chartjs-icon", ["dark-pink", "dark-pink"], /^Chart\.js$/i, 2],
    ["circleci-icon", ["medium-green", "medium-green"], /^circle\.yml$/i, 2],
    ["cc-icon", ["medium-green", "medium-green"], /\.codeclimate\.yml$/i, 2],
    ["codecov-icon", ["dark-pink", "dark-pink"], /^codecov\.ya?ml$/i, 2],
    ["coffee-icon", ["medium-cyan", "medium-cyan"], /\.coffee\.ecr$/i, 2],
    ["coffee-icon", ["medium-red", "medium-red"], /\.coffee\.erb$/i, 2],
    ["compass-icon", ["medium-red", "medium-red"], /^_?(?:compass|lemonade)\.scss$/i, 2],
    ["composer-icon", ["medium-yellow", "medium-yellow"], /^composer\.(?:json|lock)$/i, 2],
    ["composer-icon", ["dark-blue", "dark-blue"], /^composer\.phar$/i, 2],
    ["cordova-icon", ["light-blue", "light-blue"], /^cordova(?:[^.]*\.|-(?:\d\.)+)js$/i, 2],
    ["d3-icon", ["medium-orange", "medium-orange"], /^d3(?:\.v\d+)?[^.]*\.js$/i, 2],
    ["database-icon", ["medium-red", "medium-red"], /^METADATA\.pb$/, 2],
    ["database-icon", ["medium-red", "medium-red"], /\.git[\/\\](?:.*[\/\\])?(?:HEAD|ORIG_HEAD|packed-refs|logs[\/\\](?:.+[\/\\])?[^\/\\]+)$/, 2, !0],
    ["docker-icon", ["dark-blue", "dark-blue"], /^(?:Dockerfile|docker-compose)|\.docker(?:file|ignore)$/i, 2, !1, , /\.dockerfile$/i, /^Docker$/i],
    ["docker-icon", ["dark-orange", "dark-orange"], /^docker-sync\.yml$/i, 2],
    ["dojo-icon", ["light-red", "light-red"], /^dojo\.js$/i, 2],
    ["ember-icon", ["medium-red", "medium-red"], /^ember(?:\.|(?:-[^.]+)?-(?:\d+\.)+(?:debug\.)?)js$/i, 2],
    ["eslint-icon", ["medium-purple", "medium-purple"], /\.eslint(?:cache|ignore)$/i, 2],
    ["eslint-icon", ["light-purple", "light-purple"], /\.eslintrc(?:\.(?:js|json|ya?ml))?$/i, 2],
    ["extjs-icon", ["light-green", "light-green"], /\bExtjs(?:-ext)?\.js$/i, 2],
    ["fabfile-icon", ["medium-blue", "medium-blue"], /^fabfile\.py$/i, 2],
    ["fuelux-icon", ["medium-orange", "dark-orange"], /^fuelux(?:\.min)?\.(?:css|js)$/i, 2],
    ["gear-icon", ["medium-blue", "medium-blue"], /\.indent\.pro$/i, 2],
    ["grunt-icon", ["medium-yellow", "medium-yellow"], /gruntfile\.js$/i, 2],
    ["grunt-icon", ["medium-maroon", "medium-maroon"], /gruntfile\.coffee$/i, 2],
    ["gulp-icon", ["medium-red", "medium-red"], /gulpfile\.js$|gulpfile\.babel\.js$/i, 2],
    ["gulp-icon", ["medium-maroon", "medium-maroon"], /gulpfile\.coffee$/i, 2],
    ["html5-icon", ["medium-cyan", "medium-cyan"], /\.html?\.ecr$/i, 2],
    ["html5-icon", ["medium-red", "medium-red"], /\.(?:html?\.erb|rhtml)$/i, 2, !1, , /\.html\.erb$/i, /^HTML$/i],
    ["ionic-icon", ["medium-blue", "medium-blue"], /^ionic\.project$/, 2],
    ["js-icon", ["medium-cyan", "medium-cyan"], /\.js\.ecr$/i, 2],
    ["js-icon", ["medium-red", "medium-red"], /\.js\.erb$/i, 2],
    ["jquery-icon", ["dark-blue", "dark-blue"], /^jquery(?:[-.](?:min|latest|\d\.\d+(?:\.\d+)?))*\.(?:[jt]sx?|es6?|coffee|map)$/i, 2],
    ["jqueryui-icon", ["dark-blue", "dark-blue"], /^jquery(?:[-_.](?:ui[-_.](?:custom|dialog-?\w*)|effects)(?:\.[^.]*)?|[-.]?ui(?:-\d\.\d+(?:\.\d+)?)?(?:\.\w+)?)(?:[-_.]?min|dev)?\.(?:[jt]sx?|es6?|coffee|map|s?css|less|styl)$/i, 2],
    ["karma-icon", ["medium-cyan", "medium-cyan"], /^karma\.conf\.js$/i, 2],
    ["karma-icon", ["medium-maroon", "medium-maroon"], /^karma\.conf\.coffee$/i, 2],
    ["knockout-icon", ["medium-red", "medium-red"], /^knockout[-.](?:\d+\.){3}(?:debug\.)?js$/i, 2],
    ["leaflet-icon", ["medium-green", "medium-green"], /^leaflet\.(?:draw-src|draw|spin|coordinates-(?:\d+\.)\d+\.\d+\.src)\.(?:js|css)$|^wicket-leaflet\.js$/i, 2],
    ["lein-icon", [null, null], /project\.clj$/i, 2],
    ["manpage-icon", ["dark-green", "dark-green"], /^tmac\.|^(?:mmn|mmt)$/i, 2],
    ["marko-icon", ["medium-blue", "medium-blue"], /\.marko$/i, 2, !1, /^marko$/, /\.marko$/i, /^mark[0o]$/i],
    ["marko-icon", ["medium-maroon", "medium-maroon"], /\.marko\.js$/i, 2],
    ["materialize-icon", ["light-red", "light-red"], /^materialize(?:\.min)?\.(?:js|css)$/i, 2],
    ["mathjax-icon", ["dark-green", "dark-green"], /^MathJax[^.]*\.js$/i, 2],
    ["mocha-icon", ["medium-maroon", "medium-maroon"], /^mocha\.(?:[jt]sx?|es6?|coffee)$/i, 2],
    ["mocha-icon", ["medium-red", "medium-red"], /^mocha\.(?:s?css|less|styl)$/i, 2],
    ["mocha-icon", ["light-maroon", "light-maroon"], /mocha\.opts$/i, 2],
    ["modernizr-icon", ["medium-red", "medium-red"], /^modernizr(?:[-\.]custom|-\d\.\d+)(?:\.\d+)?\.js$/i, 2],
    ["mootools-icon", ["medium-purple", "medium-purple"], /^mootools[^.]*\d+\.\d+(?:.\d+)?[^.]*\.js$/i, 2],
    ["neko-icon", ["dark-orange", "dark-orange"], /^run\.n$/, 2],
    ["newrelic-icon", ["medium-cyan", "medium-cyan"], /^newrelic\.yml/i, 2],
    ["nginx-icon", ["dark-green", "dark-green"], /^nginx\.conf$/i, 2],
    ["shuriken-icon", ["dark-cyan", "dark-cyan"], /\.ninja\.d$/i, 2],
    ["nodemon-icon", ["medium-green", "medium-green"], /^nodemon\.json$|^\.nodemonignore$/i, 2],
    ["normalize-icon", ["medium-red", "medium-red"], /^normalize\.(?:css|less|scss|styl)$/i, 2],
    ["npm-icon", ["medium-red", "medium-red"], /^(?:package\.json|\.npmignore|\.?npmrc|npm-debug\.log|npm-shrinkwrap\.json)$/i, 2],
    ["postcss-icon", ["medium-yellow", "dark-yellow"], /\bpostcss\.config\.js$/i, 2],
    ["protractor-icon", ["medium-red", "medium-red"], /^protractor\.conf\./i, 2],
    ["pug-icon", ["medium-orange", "medium-orange"], /^\.pug-lintrc/i, 2],
    ["raphael-icon", ["medium-orange", "medium-orange"], /^raphael(?:\.min|\.no-deps)*\.js$/i, 2],
    ["react-icon", ["dark-blue", "dark-blue"], /^react(?:-[^.]*)?\.js$/i, 2],
    ["react-icon", ["medium-blue", "dark-blue"], /\.react\.js$/i, 2],
    ["book-icon", ["medium-blue", "medium-blue"], /^README(?:\b|_)|^(?:licen[sc]es?|(?:read|readme|click|delete|keep|test)\.me)$|\.(?:readme|1st)$/i, 2],
    ["book-icon", ["dark-blue", "dark-blue"], /^(?:notice|bugs|changes|change[-_]?log(?:[-._]?\d+)?|contribute|contributing|contributors|copying|hacking|history|install|maintainers|manifest|more\.stuff|projects|revision|terms|thanks)$/i, 2],
    ["requirejs-icon", ["medium-blue", "medium-blue"], /^require(?:[-.]min|dev)?\.js$/i, 2],
    ["clojure-icon", ["medium-maroon", "dark-maroon"], /^riemann\.config$/i, 2],
    ["rollup-icon", ["medium-red", "medium-red"], /^rollup\.config\./i, 2],
    ["ruby-icon", ["light-green", "light-green"], /_spec\.rb$/i, 2],
    ["scrutinizer-icon", ["dark-blue", "dark-blue"], /\.scrutinizer\.yml$/i, 2],
    ["sencha-icon", ["light-green", "light-green"], /^sencha(?:\.min)?\.js$/i, 2],
    ["snapsvg-icon", ["medium-cyan", "medium-cyan"], /^snap\.svg(?:[-.]min)?\.js$/i, 2],
    ["sourcemap-icon", ["medium-blue", "medium-blue"], /\.css\.map$/i, 2],
    ["sourcemap-icon", ["medium-yellow", "dark-yellow"], /\.js\.map$/i, 2],
    ["stylelint-icon", ["medium-purple", "medium-purple"], /^\.stylelintrc(?:\.|$)/i, 2],
    ["stylelint-icon", ["medium-yellow", "dark-yellow"], /^stylelint\.config\.js$/i, 2],
    ["stylelint-icon", ["dark-blue", "dark-blue"], /\.stylelintignore$/i, 2],
    ["toc-icon", ["medium-cyan", "dark-cyan"], /\.toc$/i, 2, !1, , /\.toc$/i, /^Table of Contents$/i],
    ["calc-icon", ["medium-maroon", "medium-maroon"], /\.8x[pk](?:\.txt)?$/i, 2, !1, , , , /^\*\*TI[789]\d\*\*/],
    ["travis-icon", ["medium-red", "medium-red"], /^\.travis/i, 2],
    ["typedoc-icon", ["dark-purple", "dark-purple"], /^typedoc\.json$/i, 2],
    ["typings-icon", ["medium-maroon", "medium-maroon"], /^typings\.json$/i, 2],
    ["uikit-icon", ["medium-blue", "medium-blue"], /^uikit(?:\.min)?\.js$/i, 2],
    ["webpack-icon", ["medium-blue", "medium-blue"], /webpack\.config\.|^webpackfile\.js$/i, 2],
    ["wercker-icon", ["medium-purple", "medium-purple"], /^wercker\.ya?ml$/i, 2],
    ["yarn-icon", ["medium-blue", "medium-blue"], /^yarn\.lock$/i, 2],
    ["yeoman-icon", ["medium-cyan", "medium-cyan"], /\.yo-rc\.json$/i, 2],
    ["yui-icon", ["dark-blue", "dark-blue"], /^(?:yahoo-|yui)[^.]*\.js$/i, 2],
    ["emacs-icon", ["medium-red", "medium-red"], /\.gnus$/i, 1.5],
    ["emacs-icon", ["dark-green", "dark-green"], /\.viper$/i, 1.5],
    ["emacs-icon", ["dark-blue", "dark-blue"], /^Cask$/, 1.5],
    ["emacs-icon", ["medium-blue", "medium-blue"], /^Project\.ede$/i, 1.5],
    ["_1c-icon", ["medium-red", "medium-red"], /\.bsl$/i, , !1, , /\.bsl$/i, /^1C$|^1[\W_ \t]?C[\W_ \t]?Enterprise$/i],
    ["_1c-icon", ["dark-orange", "dark-orange"], /\.sdbl$/i, , !1, , /\.sdbl$/i, /^1C$|^1[\W_ \t]?C[\W_ \t]?Query$/i],
    ["_1c-icon", ["dark-red", "dark-red"], /\.os$/i],
    ["_1c-alt-icon", ["medium-red", "dark-red"], /\.mdo$/i],
    ["abap-icon", ["medium-orange", "medium-orange"], /\.abap$/i, , !1, , /\.abp$/i, /^ABAP$/i],
    ["as-icon", ["medium-blue", "medium-blue"], /\.swf$/i],
    ["as-icon", ["medium-red", "medium-red"], /\.as$/i, , !1, , /\.(?:flex-config|actionscript(?:\.\d+)?)$/i, /^ActionScript$|^(?:ActionScript\s*3|as3)$/i],
    ["as-icon", ["medium-yellow", "dark-yellow"], /\.jsfl$/i],
    ["as-icon", ["dark-red", "dark-red"], /\.swc$/i],
    ["ada-icon", ["medium-blue", "medium-blue"], /\.(?:ada|adb|ads)$/i, , !1, , /\.ada$/i, /^Ada$|^(?:ada95|ada2005)$/i],
    ["ae-icon", ["dark-pink", "dark-pink"], /\.aep$/i],
    ["ae-icon", ["dark-purple", "dark-purple"], /\.aet$/i],
    ["ai-icon", ["medium-orange", "medium-orange"], /\.ai$/i],
    ["ai-icon", ["dark-orange", "dark-orange"], /\.ait$/i],
    ["indesign-icon", ["dark-pink", "dark-pink"], /\.indd$|\.idml$/i],
    ["indesign-icon", ["medium-purple", "medium-purple"], /\.indl$/i],
    ["indesign-icon", ["dark-purple", "dark-purple"], /\.indt$|\.inx$/i],
    ["indesign-icon", ["dark-blue", "dark-blue"], /\.indb$/i],
    ["psd-icon", ["medium-blue", "medium-blue"], /\.psd$/i, , !1, , , , /^8BPS/],
    ["psd-icon", ["dark-purple", "dark-purple"], /\.psb$/i],
    ["premiere-icon", ["dark-purple", "dark-purple"], /\.prproj$/i],
    ["premiere-icon", ["medium-maroon", "medium-maroon"], /\.prel$/i],
    ["premiere-icon", ["medium-purple", "medium-purple"], /\.psq$/i],
    ["alloy-icon", ["medium-red", "medium-red"], /\.als$/i, , !1, , /\.alloy$/i, /^Alloy$/i],
    ["alpine-icon", ["dark-blue", "dark-blue"], /(?:\.|^)APKBUILD$/],
    ["ampl-icon", ["dark-maroon", "dark-maroon"], /\.ampl$/i, , !1, , /\.ampl$/i, /^AMPL$/i],
    ["sun-icon", ["medium-yellow", "dark-yellow"], /\.ansiweatherrc$/i],
    ["antlr-icon", ["medium-red", "medium-red"], /\.g$/i, , !1, /^antlr$/, /\.antlr$/i, /^antlr$/i],
    ["antlr-icon", ["medium-orange", "medium-orange"], /\.g4$/i],
    ["apache-icon", ["dark-red", "dark-red"], /\.apacheconf$/i, , !1, , /\.apache-config$/i, /^Apache$|^(?:aconf|ApacheConf)$/i],
    ["apache-icon", ["medium-purple", "medium-purple"], /apache2[\\\/]magic$/i, , !0],
    ["api-icon", ["medium-blue", "medium-blue"], /\.apib$/i, , !1, , /\.apib$/i, /^API Blueprint$/i],
    ["apl-icon", ["dark-cyan", "dark-cyan"], /\.apl$/i, , !1, /^apl$/, /\.apl$/i, /^apl$/i],
    ["apl-icon", ["medium-maroon", "medium-maroon"], /\.apl\.history$/i],
    ["apple-icon", ["medium-purple", "medium-purple"], /\.(?:applescript|scpt)$/i, , !1, /^osascript$/, /\.applescript$/i, /^Apple$|^[0o]sascript$/i],
    ["arc-icon", ["medium-blue", "medium-blue"], /\.arc$/i],
    ["arduino-icon", ["dark-cyan", "dark-cyan"], /\.ino$/i, , !1, , /\.arduino$/i, /^Arduino$/i],
    ["asciidoc-icon", ["medium-blue", "medium-blue"], /\.(?:ad|adoc|asc|asciidoc)$/i, , !1, , /\.asciidoc$/i, /^AsciiDoc$/i],
    ["asp-icon", ["dark-blue", "dark-blue"], /\.asp$/i, , !1, , /\.asp$/i, /^[Aa][Ss][Pp][\W_ \t]?[Nn][Ee][Tt]$|^aspx(?:-vb)?$/],
    ["asp-icon", ["medium-maroon", "medium-maroon"], /\.asax$/i],
    ["asp-icon", ["dark-green", "dark-green"], /\.ascx$/i],
    ["asp-icon", ["medium-green", "medium-green"], /\.ashx$/i],
    ["asp-icon", ["dark-cyan", "dark-cyan"], /\.asmx$/i],
    ["asp-icon", ["medium-purple", "medium-purple"], /\.aspx$/i],
    ["asp-icon", ["medium-cyan", "medium-cyan"], /\.axd$/i],
    ["eclipse-icon", ["medium-maroon", "medium-maroon"], /\.aj$/i],
    ["binary-icon", ["medium-red", "medium-red"], /\.(?:l?a|[ls]?o|out|s|a51|n?asm|axf|elf|prx|puff|was[mt]|z80)$|\.rpy[bc]$/i, , !1, , /(?:^|\.)(?:a[rs]m|x86|z80|lc-?3|cpu12|x86asm|m68k|assembly|avr(?:dis)?asm|dasm)(?:\.|$)/i, /^Assembly$|^n?asm$/i],
    ["binary-icon", ["dark-blue", "dark-blue"], /\.agc$|\.d-objdump$/i, , !1, , /\.source\.agc$/i, /^Assembly$|^(?:Virtual\s*)?AGC$|^Apollo(?:[-_\s]*11)?\s*Guidance\s*Computer$/i],
    ["binary-icon", ["dark-green", "dark-green"], /\.ko$/i],
    ["binary-icon", ["medium-blue", "medium-blue"], /\.lst$/i, , !1, /^lst-cpu12$/, /\.lst-cpu12$/i, /^Assembly$|^lst[\W_ \t]?cpu12$/i],
    ["binary-icon", ["dark-orange", "dark-orange"], /\.(?:(?:c(?:[+px]{2}?)?-?)?objdump|bsdiff|bin|dat|pak|pdb)$/i],
    ["binary-icon", ["medium-orange", "medium-orange"], /\.gcode|\.gco/i],
    ["binary-icon", ["dark-purple", "dark-purple"], /\.py[co]$/i],
    ["binary-icon", [null, null], /\.DS_Store$/i],
    ["ats-icon", ["medium-red", "medium-red"], /\.dats$/i, , !1, , /\.ats$/i, /^ATS$|^ats2$/i],
    ["ats-icon", ["medium-blue", "medium-blue"], /\.hats$/i],
    ["ats-icon", ["dark-yellow", "dark-yellow"], /\.sats$/i],
    ["audacity-icon", ["medium-yellow", "medium-yellow"], /\.aup$/i],
    ["audio-icon", ["medium-red", "medium-red"], /\.mp3$/i, , !1, , , , /^ÿû|^ID3/],
    ["audio-icon", ["dark-yellow", "dark-yellow"], /\.wav$/i, , !1, , , , /^RIFF(?!.+WEBP)/],
    ["audio-icon", ["dark-cyan", "dark-cyan"], /\.(?:aac|ac3|m4p)$/i, , !1, , , , /^w/],
    ["audio-icon", ["medium-purple", "medium-purple"], /\.aif[fc]?$/i, , !1, , , , /^FORM.{4}AIFF/],
    ["audio-icon", ["medium-cyan", "medium-cyan"], /\.au$/i, , !1, , , , /^\.snd|^dns\./],
    ["audio-icon", ["dark-red", "dark-red"], /\.flac$/i, , !1, , , , /^fLaC/],
    ["audio-icon", ["medium-red", "medium-red"], /\.f4[ab]$/i, , !1, , , , /^FLV/],
    ["audio-icon", ["medium-cyan", "medium-cyan"], /\.m4a$/i, , !1, , , , /^.{4}ftypM4A/],
    ["audio-icon", ["dark-green", "dark-green"], /\.(?:mpc|mp\+)$/i, , !1, , , , /^MPCK/],
    ["audio-icon", ["dark-orange", "dark-orange"], /\.oga$/i],
    ["audio-icon", ["dark-maroon", "dark-maroon"], /\.opus$/i, , !1, , , , /OpusHead/],
    ["audio-icon", ["dark-blue", "dark-blue"], /\.r[am]$/i, , !1, , , , /^\.RMF/],
    ["audio-icon", ["medium-blue", "medium-blue"], /\.wma$/i],
    ["augeas-icon", ["dark-orange", "dark-orange"], /\.aug$/i],
    ["ahk-icon", ["dark-blue", "dark-blue"], /\.ahk$/i, , !1, /^ahk$/, /\.ahk$/i, /^AutoHotkey$|^ahk$/i],
    ["ahk-icon", ["dark-purple", "dark-purple"], /\.ahkl$/i],
    ["autoit-icon", ["medium-purple", "medium-purple"], /\.au3$/i, , !1, , /(?:^|\.)autoit(?:\.|$)/i, /^AutoIt$|^(?:AutoIt3|AutoItScript|au3)$/i],
    ["terminal-icon", ["medium-blue", "medium-blue"], /\.awk$/i, , !1, /^awk$/, /\.awk$/i, /^awk$/i],
    ["terminal-icon", ["medium-red", "medium-red"], /\.gawk$/i, , !1, /^gawk$/, /\.gawk$/i, /^AWK$|^gawk$/i],
    ["terminal-icon", ["medium-maroon", "medium-maroon"], /\.mawk$/i, , !1, /^mawk$/, /\.mawk$/i, /^AWK$|^mawk$/i],
    ["terminal-icon", ["dark-green", "dark-green"], /\.nawk$/i, , !1, /^nawk$/, /\.nawk$/i, /^AWK$|^nawk$/i],
    ["terminal-icon", ["dark-cyan", "dark-cyan"], /\.auk$/i],
    ["babel-icon", ["medium-yellow", "medium-yellow"], /\.(?:babelrc|languagebabel|babel)$/i],
    ["babel-icon", ["dark-yellow", "dark-yellow"], /\.babelignore$/i],
    ["bibtex-icon", ["medium-red", "dark-red"], /\.cbx$/i],
    ["bibtex-icon", ["medium-orange", "dark-orange"], /\.bbx$/i],
    ["bibtex-icon", ["medium-yellow", "dark-yellow"], /\.bib$/i, , !1, /^bibtex$/, /\.bibtex$/i, /^bibtex$/i],
    ["bibtex-icon", ["medium-green", "dark-green"], /\.bst$/i],
    ["gnu-icon", ["medium-red", "medium-red"], /\.bison$/i, , !1, , /\.bison$/i, /^Bison$/i],
    ["blender-icon", ["medium-orange", "medium-orange"], /\.blend$/i],
    ["blender-icon", ["dark-orange", "dark-orange"], /\.blend\d+$/i],
    ["blender-icon", ["dark-blue", "dark-blue"], /\.bphys$/i],
    ["bluespec-icon", ["dark-blue", "dark-blue"], /\.bsv$/i, , !1, , /\.bsv$/i, /^Bluespec$/i],
    ["boo-icon", ["medium-green", "medium-green"], /\.boo$/i, , !1, , /\.boo(?:\.unity)?$/i, /^Boo$/i],
    ["boot-icon", [null, null], /\.boot$/i],
    ["brain-icon", ["dark-pink", "dark-pink"], /\.bf?$/i, , !1, , /\.(?:bf|brainfuck)$/i, /^Brainfuck$|^(?:bf|Brainf\**ck)$/i],
    ["brew-icon", ["medium-orange", "medium-orange"], /^Brewfile$/],
    ["bro-icon", ["dark-cyan", "dark-cyan"], /\.bro$/i, , !1, , /\.bro$/i, /^Bro$/i],
    ["byond-icon", ["medium-blue", "medium-blue"], /\.dm$/i, , !1, , /\.dm$/i, /^BYOND$|^(?:DM|Dream\s*Maker(?:\s*Script)?)$/i],
    ["c-icon", ["medium-blue", "medium-blue"], /\.c$/i, , !1, /^tcc$/, /\.c$/i, /^C$/i],
    ["c-icon", ["medium-purple", "medium-purple"], /\.h$|\.cats$/i],
    ["c-icon", ["medium-green", "medium-green"], /\.idc$/i],
    ["c-icon", ["medium-maroon", "medium-maroon"], /\.w$/i],
    ["c-icon", ["dark-blue", "dark-blue"], /\.nc$/i],
    ["c-icon", ["medium-cyan", "medium-cyan"], /\.upc$/i],
    ["csharp-icon", ["medium-blue", "dark-blue"], /\.cs$/i, , !1, , /\.cs$/i, /^C#$|^c\s*sharp$/i],
    ["csscript-icon", ["dark-green", "dark-green"], /\.csx$/i, , !1, , /\.csx$/i, /^C#-Script$/i],
    ["cpp-icon", ["medium-blue", "dark-blue"], /\.c[+px]{2}$|\.cc$/i, , !1, , /\.cpp$/i, /^C\+\+$|c[-_]?pp|cplusplus/i],
    ["cpp-icon", ["medium-purple", "dark-purple"], /\.h[+px]{2}$/i],
    ["cpp-icon", ["medium-orange", "dark-orange"], /\.[it]pp$/i],
    ["cpp-icon", ["medium-red", "dark-red"], /\.(?:tcc|inl)$/i],
    ["cabal-icon", ["medium-cyan", "medium-cyan"], /\.cabal$/i, , !1, , /\.cabal$/i, /^Cabal$/i],
    ["cake-icon", ["medium-yellow", "medium-yellow"], /\.cake$/i, , !1, , /\.cake$/i, /^Cake$/i],
    ["cakefile-icon", ["medium-red", "medium-red"], /^Cakefile$/],
    ["cakephp-icon", ["medium-red", "medium-red"], /\.ctp$/i],
    ["ceylon-icon", ["medium-orange", "medium-orange"], /\.ceylon$/i],
    ["chapel-icon", ["medium-green", "medium-green"], /\.chpl$/i, , !1, , /\.chapel$/i, /^Chapel$|^chpl$/i],
    ["chrome-icon", ["medium-red", "medium-red"], /\.crx$/i, , !1, , , , /^Cr24/],
    ["chuck-icon", ["medium-green", "medium-green"], /\.ck$/i, , !1, , /\.chuck$/i, /^ChucK$/i],
    ["cirru-icon", ["medium-pink", "dark-pink"], /\.cirru$/i, , !1, , /\.cirru$/i, /^Cirru$/i],
    ["clarion-icon", ["medium-orange", "medium-orange"], /\.clw$/i, , !1, , /\.clarion$/i, /^Clarion$/i],
    ["clean-icon", ["dark-cyan", "dark-cyan"], /\.icl$/i, , !1, /^clean$/, /\.clean$/i, /^clean$/i],
    ["clean-icon", ["medium-cyan", "medium-cyan"], /\.dcl$/i],
    ["clean-icon", ["medium-blue", "medium-blue"], /\.abc$/i],
    ["click-icon", ["medium-yellow", "medium-yellow"], /\.click$/i, , !1, , /\.click$/i, /^Click$|^Click!$/i],
    ["clips-icon", ["dark-green", "dark-green"], /\.clp$/i, , !1, , /\.clips$/i, /^CLIPS$/i],
    ["clojure-icon", ["medium-blue", "dark-blue"], /\.clj$/i, , !1, /^clojure$/, /\.clojure$/i, /^cl[0o]jure$/i],
    ["clojure-icon", ["medium-purple", "dark-purple"], /\.cl2$/i],
    ["clojure-icon", ["medium-green", "dark-green"], /\.cljc$/i],
    ["clojure-icon", ["medium-red", "dark-red"], /\.cljx$|\.hic$/i],
    ["cljs-icon", ["medium-blue", "dark-blue"], /\.cljs(?:\.hl|cm)?$/i],
    ["cmake-icon", ["medium-green", "medium-green"], /\.cmake$/i, , !1, /^cmake$/, /\.cmake$/i, /^cmake$/i],
    ["cmake-icon", ["medium-red", "medium-red"], /^CMakeLists\.txt$/],
    ["coffee-icon", ["medium-maroon", "medium-maroon"], /\.coffee$/i, , !1, /^coffee$/, /\.coffee$/i, /^CoffeeScript$|^Coffee(?:-Script)?$/i],
    ["coffee-icon", ["dark-maroon", "dark-maroon"], /\.cjsx$/i],
    ["coffee-icon", ["light-maroon", "light-maroon"], /\.litcoffee$/i, , !1, /^litcoffee$/, /\.litcoffee$/i, /^CoffeeScript$|^litc[0o]ffee$/i],
    ["coffee-icon", ["medium-blue", "medium-blue"], /\.iced$/i],
    ["cf-icon", ["light-cyan", "light-cyan"], /\.cfc$/i, , !1, , /\.cfscript$/i, /^ColdFusion$|^(?:CFC|CFScript)$/i],
    ["cf-icon", ["medium-cyan", "medium-cyan"], /\.cfml?$/i, , !1, , /\.cfml?$/i, /^ColdFusion$|^(?:cfml?|ColdFusion\s*HTML)$/i],
    ["khronos-icon", ["medium-orange", "medium-orange"], /\.dae$/i],
    ["cl-icon", ["medium-orange", "medium-orange"], /\.cl$/i, , !1, /^(?:c?lisp|sbcl|[ec]cl)$/, /\.common-lisp$/i, /^Common Lisp$|^c?lisp$/i],
    ["cp-icon", ["medium-maroon", "medium-maroon"], /\.cp$/i],
    ["cp-icon", ["dark-red", "dark-red"], /\.cps$/i],
    ["zip-icon", [null, null], /\.(?:zip|z|xz)$/i, , !1, , , , /^(?:PK(?:|||)|[ ]|BZh|RNC[]|ÐÏà)/],
    ["zip-icon", ["medium-blue", "medium-blue"], /\.rar$/i, , !1, , , , /^Rar!?\0/],
    ["zip-icon", ["dark-blue", "dark-blue"], /\.t?gz$|\.tar$|\.whl$/i, , !1, , , , /^/],
    ["zip-icon", ["medium-maroon", "medium-maroon"], /\.(?:lzo?|lzma|tlz|tar\.lzma)$/i, , !1, , , , /^LZIP/],
    ["zip-icon", ["medium-maroon", "medium-maroon"], /\.7z$/i, , !1, , , , /^7z¼¯'/],
    ["zip-icon", ["medium-red", "medium-red"], /\.apk$|\.gem$/i],
    ["zip-icon", ["dark-cyan", "dark-cyan"], /\.bz2$/i],
    ["zip-icon", ["medium-blue", "medium-blue"], /\.iso$/i, , !1, , , , /^ER\0{3}|^ER/],
    ["zip-icon", ["medium-orange", "medium-orange"], /\.xpi$/i],
    ["zip-icon", ["medium-green", "medium-green"], /\.epub$/i],
    ["zip-icon", ["dark-pink", "dark-pink"], /\.jar$/i],
    ["zip-icon", ["medium-purple", "medium-purple"], /\.war$/i],
    ["zip-icon", ["dark-orange", "dark-orange"], /\.xar$/i, , !1, , , , /^xar!/],
    ["zip-icon", ["light-orange", "light-orange"], /\.egg$/i],
    ["config-icon", ["medium-yellow", "medium-yellow"], /\.(?:ini|desktop|directory|cfg|conf|prefs)$/i, , !1, , /\.ini$/i, /^d[0o]sini$/i],
    ["config-icon", ["medium-purple", "medium-purple"], /\.properties$/i, , !1, , /\.java-properties$/i],
    ["config-icon", ["medium-green", "medium-green"], /\.toml$|\.opts$/i],
    ["config-icon", ["dark-red", "dark-red"], /\.ld$/i],
    ["config-icon", ["medium-red", "medium-red"], /\.lds$|\.reek$/i],
    ["config-icon", ["dark-blue", "dark-blue"], /\.terminal$/i],
    ["config-icon", ["medium-orange", "medium-orange"], /^ld\.script$/i],
    ["config-icon", ["dark-red", "dark-red"], /\.git[\/\\](?:config|info[\/\\]\w+)$/, , !0],
    ["config-icon", ["dark-orange", "dark-orange"], /^\/(?:private\/)?etc\/(?:[^\/]+\/)*[^\/]*\.(?:cf|conf|ini)(?:\.default)?$/i, , !0],
    ["config-icon", ["medium-maroon", "medium-maroon"], /^\/(?:private\/)?etc\/(?:aliases|auto_(?:home|master)|ftpusers|group|gettytab|hosts(?:\.equiv)?|manpaths|networks|paths|protocols|services|shells|sudoers|ttys)$/i, , !0],
    ["coq-icon", ["medium-maroon", "medium-maroon"], /\.coq$/i, , !1, , /\.coq$/i, /^Coq$/i],
    ["creole-icon", ["medium-blue", "medium-blue"], /\.creole$/i, , !1, , /\.creole$/i, /^Creole$/i],
    ["crystal-icon", ["medium-cyan", "medium-cyan"], /\.e?cr$/i, , !1, /^crystal$/, /\.crystal$/i, /^Crystal$/i],
    ["csound-icon", ["medium-maroon", "medium-maroon"], /\.orc$/i, , !1, , /\.csound$/i, /^Csound$|^cs[0o]und[\W_ \t]?[0o]rc$/i],
    ["csound-icon", ["dark-orange", "dark-orange"], /\.udo$/i],
    ["csound-icon", ["dark-maroon", "dark-maroon"], /\.csd$/i, , !1, , /\.csound-document$/i, /^Csound$|^cs[0o]und[\W_ \t]?csd$/i],
    ["csound-icon", ["dark-blue", "dark-blue"], /\.sco$/i, , !1, , /\.csound-score$/i, /^Csound$|^cs[0o]und[\W_ \t]?sc[0o]$/i],
    ["css3-icon", ["medium-blue", "medium-blue"], /\.css$/i, , !1, /^css$/, /\.css$/i, /^css$/i],
    ["css3-icon", ["dark-blue", "dark-blue"], /\.less$/i, , !1, /^less$/, /\.less$/i, /^CSS$|^less$/i],
    ["cucumber-icon", ["medium-green", "medium-green"], /\.feature$/i, , !1, , /(?:^|\.)(?:gherkin\.feature|cucumber\.steps)(?:\.|$)/i, /^Cucumber$|^gherkin$/i],
    ["nvidia-icon", ["medium-green", "medium-green"], /\.cu$/i, , !1, , /\.cuda(?:-c\+\+)?$/i, /^CUDA$/i],
    ["nvidia-icon", ["dark-green", "dark-green"], /\.cuh$/i],
    ["cython-icon", ["medium-orange", "medium-orange"], /\.pyx$/i, , !1, , /\.cython$/i, /^Cython$|^pyrex$/i],
    ["cython-icon", ["medium-blue", "medium-blue"], /\.pxd$/i],
    ["cython-icon", ["dark-blue", "dark-blue"], /\.pxi$/i],
    ["dlang-icon", ["medium-red", "medium-red"], /\.di?$/i, , !1, , /\.d$/i, /^D$/i],
    ["yang-icon", ["medium-red", "medium-red"], /\.dnh$/i, , !1, , /\.danmakufu$/i, /^Danmakufu$/i],
    ["darcs-icon", ["medium-green", "medium-green"], /\.d(?:arcs)?patch$/i],
    ["dart-icon", ["medium-cyan", "medium-cyan"], /\.dart$/i, , !1, /^dart$/, /\.dart$/i, /^Dart$/i],
    ["dashboard-icon", ["medium-orange", "medium-orange"], /\.s[kl]im$/i, , !1, /^slim$/, /\.slim$/i, /^slim$/i],
    ["dashboard-icon", ["medium-green", "medium-green"], /\.cpuprofile$/i],
    ["database-icon", ["medium-yellow", "medium-yellow"], /\.(?:h|geo|topo)?json$/i],
    ["database-icon", ["light-red", "light-red"], /\.ya?ml$/i],
    ["database-icon", ["medium-maroon", "medium-maroon"], /\.cson$|\.ston$|^mime\.types$/i],
    ["database-icon", ["dark-yellow", "dark-yellow"], /\.json5$/i, , !1, /^json5$/, /\.json5$/i, /^js[0o]n5$/i],
    ["database-icon", ["medium-red", "medium-red"], /\.http$|\.pot?$/i],
    ["database-icon", ["medium-orange", "medium-orange"], /\.ndjson$|\.pytb$/i, , !1, , /\.python\.traceback$/i],
    ["database-icon", ["light-blue", "light-blue"], /\.fea$/i, , !1, , /\.opentype$/i, /^afdk[0o]$/i],
    ["database-icon", ["medium-purple", "medium-purple"], /\.json\.eex$|\.edn$/i],
    ["database-icon", ["dark-cyan", "dark-cyan"], /\.proto$/i, , !1, , /\.protobuf$/i, /^(?:protobuf|Protocol\s*Buffers?)$/i],
    ["database-icon", ["dark-blue", "dark-blue"], /\.pydeps$|\.rviz$/i],
    ["database-icon", ["dark-purple", "dark-purple"], /\.eam\.fs$/i],
    ["database-icon", ["medium-pink", "medium-pink"], /\.qml$/i],
    ["database-icon", ["dark-pink", "dark-pink"], /\.qbs$/i],
    ["database-icon", ["medium-cyan", "medium-cyan"], /\.ttl$/i, , !1, , /\.turtle$/i],
    ["database-icon", ["medium-blue", "medium-blue"], /\.syntax$/i],
    ["database-icon", ["dark-red", "dark-red"], /[\/\\](?:magic[\/\\]Magdir|file[\/\\]magic)[\/\\][-.\w]+$|lib[\\\/]icons[\\\/]\.icondb\.js$/i, , !0],
    ["dbase-icon", ["medium-red", "medium-red"], /\.dbf$/i],
    ["debian-icon", ["medium-red", "medium-red"], /\.deb$/i],
    ["debian-icon", ["dark-cyan", "dark-cyan"], /^control$/],
    ["debian-icon", ["medium-cyan", "medium-cyan"], /^rules$/],
    ["diff-icon", ["medium-orange", "medium-orange"], /\.diff$/i, , !1, , /\.diff$/i, /^Diff$|^udiff$/i],
    ["earth-icon", ["medium-blue", "medium-blue"], /\.zone$/i],
    ["earth-icon", ["medium-green", "medium-green"], /\.arpa$/i],
    ["earth-icon", ["dark-blue", "dark-blue"], /^CNAME$/],
    ["doxygen-icon", ["medium-blue", "medium-blue"], /^Doxyfile$/, , !1, , /\.doxygen$/i, /^Doxyfile$/i],
    ["dyalog-icon", ["medium-orange", "medium-orange"], /\.dyalog$/i, , !1, /^dyalog$/],
    ["dylib-icon", ["medium-cyan", "medium-cyan"], /\.(?:dylib|bundle)$/i],
    ["e-icon", ["medium-green", "medium-green"], /\.E$/, , !1, /^rune$/],
    ["eagle-icon", ["medium-red", "medium-red"], /\.sch$/i],
    ["eagle-icon", ["dark-red", "dark-red"], /\.brd$/i],
    ["ec-icon", ["dark-blue", "dark-blue"], /\.ec$/i, , !1, /^ec$/, /\.ec$/i, /^ec$/i],
    ["ec-icon", ["dark-purple", "dark-purple"], /\.eh$/i],
    ["ecere-icon", ["medium-blue", "medium-blue"], /\.epj$/i],
    ["eclipse-icon", ["dark-blue", "dark-blue"], /\.c?project$/],
    ["eclipse-icon", ["medium-red", "medium-red"], /\.classpath$/i],
    ["editorconfig-icon", ["medium-orange", "medium-orange"], /\.editorconfig$/i, , !1, , /\.editorconfig$/i, /^EditorConfig$/i],
    ["eiffel-icon", ["medium-cyan", "medium-cyan"], /\.e$/, , !1, , /\.eiffel$/i, /^Eiffel$/i],
    ["elixir-icon", ["dark-purple", "dark-purple"], /\.ex$/i, , !1, /^elixir$/, /\.elixir$/i, /^elixir$/i],
    ["elixir-icon", ["medium-purple", "medium-purple"], /\.(?:exs|eex)$/i],
    ["elixir-icon", ["light-purple", "light-purple"], /mix\.exs?$/i],
    ["elm-icon", ["medium-blue", "medium-blue"], /\.elm$/i, , !1, , /\.elm$/i, /^Elm$/i],
    ["emacs-icon", ["medium-purple", "medium-purple"], /(?:^|\.)(?:el|_?emacs|spacemacs|emacs\.desktop|abbrev[-_]defs)$/i, , !1, /^emacs$/, /\.emacs\.lisp$/i, /^Emacs Lisp$|^elisp$/i],
    ["emacs-icon", ["dark-purple", "dark-purple"], /(?:^|\.)(?:elc|eld)$/i, , !1, , , , /^;ELC\0{3}/],
    ["at-icon", ["medium-red", "dark-red"], /^(?:authors|owners)$/i],
    ["em-icon", ["medium-red", "medium-red"], /\.emberscript$/i, , !1, , /\.ember(?:script)?$/i, /^EmberScript$/i],
    ["mustache-icon", ["medium-blue", "medium-blue"], /\.em(?:blem)?$/i, , !1, , /\.emblem$/i, /^Emblem$/i],
    ["eq-icon", ["medium-orange", "medium-orange"], /\.eq$/i, , !1, , /\.eq$/i, /^EQ$/i],
    ["erlang-icon", ["medium-red", "medium-red"], /\.erl$/i, , !1, /^escript$/, /\.erlang$/i, /^Erlang$/i],
    ["erlang-icon", ["dark-red", "dark-red"], /\.beam$/i],
    ["erlang-icon", ["medium-maroon", "medium-maroon"], /\.hrl$/i],
    ["erlang-icon", ["medium-green", "medium-green"], /\.xrl$/i],
    ["erlang-icon", ["dark-green", "dark-green"], /\.yrl$/i],
    ["erlang-icon", ["dark-maroon", "dark-maroon"], /\.app\.src$/i],
    ["factor-icon", ["medium-orange", "medium-orange"], /\.factor$/i, , !1, , /\.factor$/i, /^Factor$/i],
    ["factor-icon", ["dark-orange", "dark-orange"], /\.factor-rc$/i],
    ["factor-icon", ["medium-red", "medium-red"], /\.factor-boot-rc$/i],
    ["fancy-icon", ["dark-blue", "dark-blue"], /\.fy$/i, , !1, /^fancy$/, /\.fancy$/i, /^fancy$/i],
    ["fancy-icon", ["medium-blue", "medium-blue"], /\.fancypack$/i],
    ["fancy-icon", ["medium-green", "medium-green"], /^Fakefile$/],
    ["fantom-icon", ["medium-blue", "medium-blue"], /\.fan$/i, , !1, , /\.fan(?:tom)?$/i, /^Fantom$/i],
    ["fbx-icon", ["medium-maroon", "medium-maroon"], /\.fbx$/i],
    ["finder-icon", ["medium-blue", "medium-blue"], /^Icon\r$/],
    ["finder-icon", ["dark-blue", "dark-blue"], /\.rsrc$/i],
    ["flow-icon", ["medium-orange", "medium-orange"], /\.(?:flowconfig|js\.flow)$/i],
    ["flux-icon", ["medium-blue", "medium-blue"], /\.fx$/i],
    ["flux-icon", ["dark-blue", "dark-blue"], /\.flux$/i],
    ["font-icon", ["dark-blue", "dark-blue"], /\.woff2$/i, , !1, , , , /^wOF2/],
    ["font-icon", ["medium-blue", "medium-blue"], /\.woff$/i, , !1, , , , /^wOFF/],
    ["font-icon", ["light-green", "light-green"], /\.eot$/i, , !1, , , , /^.{34}LP/],
    ["font-icon", ["dark-green", "dark-green"], /\.ttc$/i, , !1, , , , /^ttcf/],
    ["font-icon", ["medium-green", "medium-green"], /\.ttf$/i, , !1, , , , /^\0\0{3}/],
    ["font-icon", ["dark-yellow", "dark-yellow"], /\.otf$/i, , !1, , , , /^OTTO.*\0/],
    ["font-icon", ["dark-red", "dark-red"], /\.pfb$/i],
    ["font-icon", ["medium-red", "medium-red"], /\.pfm$/i],
    ["ff-icon", ["medium-orange", "medium-orange"], /\.pe$/i, , !1, /^fontforge$/, /\.source\.fontforge$/i, /^FontForge$|^pfaedit$/i],
    ["ff-icon", ["dark-blue", "dark-blue"], /\.sfd$/i, , !1, , /\.text\.sfd$/i, /^FontForge$/i],
    ["fortran-icon", ["medium-maroon", "medium-maroon"], /\.f$/i, , !1, , /\.fortran\.?(?:modern|punchcard)?$/i, /^Fortran$/i],
    ["fortran-icon", ["medium-green", "medium-green"], /\.f90$/i, , !1, , /\.fortran\.free$/i, /^Fortran$/i],
    ["fortran-icon", ["medium-red", "medium-red"], /\.f03$/i],
    ["fortran-icon", ["medium-blue", "medium-blue"], /\.f08$/i],
    ["fortran-icon", ["medium-maroon", "medium-maroon"], /\.f77$/i, , !1, , /\.fortran\.fixed$/i, /^Fortran$/i],
    ["fortran-icon", ["dark-pink", "dark-pink"], /\.f95$/i],
    ["fortran-icon", ["dark-cyan", "dark-cyan"], /\.for$/i],
    ["fortran-icon", ["dark-yellow", "dark-yellow"], /\.fpp$/i],
    ["freemarker-icon", ["medium-blue", "medium-blue"], /\.ftl$/i, , !1, , /\.ftl$/i, /^FreeMarker$|^ftl$/i],
    ["frege-icon", ["dark-red", "dark-red"], /\.fr$/i],
    ["fsharp-icon", ["medium-blue", "medium-blue"], /\.fs[xi]?$/i, , !1, , /\.fsharp$/i, /^FSharp$|^f#$/i],
    ["gml-icon", ["medium-green", "medium-green"], /\.gml$/i],
    ["gams-icon", ["dark-red", "dark-red"], /\.gms$/i, , !1, , /\.gams(?:-lst)?$/i, /^GAMS$/i],
    ["gap-icon", ["medium-yellow", "dark-yellow"], /\.gap$/i, , !1, /^gap$/, /\.gap$/i, /^gap$/i],
    ["gap-icon", ["dark-blue", "dark-blue"], /\.gi$/i],
    ["gap-icon", ["medium-orange", "medium-orange"], /\.tst$/i],
    ["gdb-icon", ["medium-green", "dark-green"], /\.gdb$/i, , !1, /^gdb$/, /\.gdb$/i, /^gdb$/i],
    ["gdb-icon", ["medium-cyan", "dark-cyan"], /gdbinit$/i],
    ["godot-icon", ["medium-blue", "medium-blue"], /\.gd$/i, , !1, , /\.gdscript$/i, /^GDScript$/i],
    ["gear-icon", ["medium-red", "medium-red"], /^\.htaccess$|\.yardopts$/i],
    ["gear-icon", ["medium-orange", "medium-orange"], /^\.htpasswd$/i],
    ["gear-icon", ["dark-green", "dark-green"], /^\.env\.|\.pairs$/i],
    ["gear-icon", ["dark-yellow", "dark-yellow"], /^\.lesshintrc$/i],
    ["gear-icon", ["medium-yellow", "medium-yellow"], /^\.csscomb\.json$|\.csslintrc$|\.jsbeautifyrc$|\.jshintrc$|\.jscsrc$/i],
    ["gear-icon", ["medium-maroon", "medium-maroon"], /\.coffeelintignore$|\.codoopts$/i],
    ["gear-icon", ["medium-blue", "medium-blue"], /\.module$/i],
    ["gear-icon", ["dark-blue", "dark-blue"], /\.arcconfig$|\.python-version$/i],
    ["gear-icon", ["dark-orange", "dark-orange"], /\.lintstagedrc$/i],
    ["gears-icon", ["dark-orange", "dark-orange"], /\.dll$/i, , !1, , , , /^PMOCCMOC/],
    ["code-icon", ["medium-blue", "medium-blue"], /\.xml$|\.config$|\.4th$|\.cocci$|\.dyl$|\.dylan$|\.ecl$|\.forth$|\.launch$|\.manifest$|\.menu$|\.srdf$|\.st$|\.ui$|\.wsf$|\.x3d$|\.xaml$/i, , !1, , , , /^<\?xml /],
    ["code-icon", ["dark-red", "dark-red"], /\.rdf$|\.capnp$|\.dotsettings$|\.flex$|\.fsh$|\.fsproj$|\.prw$|\.xproj$/i, , !1, , /\.capnp$/i],
    ["code-icon", ["medium-blue", "medium-blue"], /^_service$/],
    ["code-icon", ["medium-red", "medium-red"], /^configure\.ac$|\.ML$/],
    ["code-icon", ["medium-green", "medium-green"], /^Settings\.StyleCop$/],
    ["code-icon", ["medium-green", "medium-green"], /\.abnf$|\.ditaval$|\.storyboard$|\.xmi$|\.yacc$/i, , !1, /^abnf$/, /\.abnf$/i, /^abnf$/i],
    ["code-icon", ["medium-purple", "medium-purple"], /\.aepx$|\.dita$|\.grace$|\.lid$|\.nproj$/i],
    ["code-icon", ["dark-cyan", "dark-cyan"], /\.agda$|\.plist$|\.wisp$|\.xlf$|\.xslt$/i, , !1, , /\.plist$/i],
    ["code-icon", ["medium-orange", "medium-orange"], /\.appxmanifest$|\.befunge$|\.fun$|\.muf$|\.xul$/i],
    ["code-icon", ["medium-cyan", "medium-cyan"], /\.ash$|\.asn1?$|\.lagda$|\.lex$|\.props$|\.resx$|\.smt2$|\.vsh$|\.xsl$|\.yy$/i, , !1, /^xsl$/, /\.xsl$/i],
    ["code-icon", ["dark-blue", "dark-blue"], /\.axml$|\.bmx$|\.brs$|\.ccxml$|\.clixml$|\.fth$|\.intr$|\.mdpolicy$|\.mtml$|\.myt$|\.xsd$/i, , !1, /^brightscript$/, /\.brightscript$/i],
    ["code-icon", ["medium-maroon", "medium-maroon"], /\.bnf$|\.cbl$|\.cob$|\.cobol$|\.fxml$/i, , !1, /^bnf$/, /\.bnf$/i, /^bnf$/i],
    ["code-icon", ["dark-maroon", "dark-maroon"], /\.ccp$|\.cpy$|\.mxml$/i],
    ["code-icon", ["medium-red", "medium-red"], /\.ch$|\.cw$|\.ebnf$|\.iml$|\.jflex$|\.m4$|\.mask$|\.mumps$|\.prg$|\.pt$|\.rl$|\.sml$|\.targets$|\.webidl$|\.wsdl$|\.xacro$|\.xliff$/i, , !1, /^ebnf$/, /\.ebnf$/i],
    ["code-icon", ["dark-pink", "dark-pink"], /\.ct$|\.zcml$/i],
    ["code-icon", ["dark-green", "dark-green"], /\.cy$|\.eclxml$|\.ivy$|\.sed$|\.tml$|\.y$/i],
    ["code-icon", ["dark-purple", "dark-purple"], /\.ditamap$|\.frt$|\.lp$|\.omgrofl$|\.osm$|\.wxs$|\.xib$/i],
    ["code-icon", ["medium-pink", "medium-pink"], /\.filters$|\.lol$|\.pig$/i],
    ["code-icon", ["dark-orange", "dark-orange"], /\.grxml$|\.urdf$/i],
    ["code-icon", ["medium-yellow", "medium-yellow"], /\.jelly$/i],
    ["code-icon", ["dark-yellow", "dark-yellow"], /\.jsproj$|\.ohm$|\.sgml?$/i, , !1, /^ohm$/, /\.ohm$/i],
    ["code-icon", ["dark-blue", "dark-blue"], /\.mq[45h]$/i, , !1, , /(?:^|\.)mq[45](?=\.|$)/i],
    ["code-icon", ["light-green", "light-green"], /\.odd$/i],
    ["code-icon", ["light-blue", "light-blue"], /\.psc1$|\.smt$/i, , !1, /boolector|cvc4|mathsat5|opensmt|smtinterpol|smt-rat|stp|verit|yices2|z3/, /\.smt$/i],
    ["code-icon", ["light-cyan", "light-cyan"], /\.scxml$/i],
    ["code-icon", ["light-maroon", "light-maroon"], /\.sig$|\.wxl$/i],
    ["code-icon", ["light-orange", "light-orange"], /\.ux$|\.wxi$/i],
    ["code-icon", ["light-purple", "light-purple"], /\.vxml$/i],
    ["genshi-icon", ["medium-red", "medium-red"], /\.kid$/i, , !1, , /\.genshi$/i, /^Genshi$|^xml\+(?:genshi|kid)$/i],
    ["gentoo-icon", ["dark-cyan", "dark-cyan"], /\.ebuild$/i, , !1, , /\.ebuild$/i, /^Gentoo$/i],
    ["gentoo-icon", ["medium-blue", "medium-blue"], /\.eclass$/i],
    ["git-icon", ["medium-red", "medium-red"], /^\.git|^\.keep$|\.mailmap$/i, , !1, , /\.git-(?:commit|config|rebase)$/i, /^Git$/i],
    ["git-commit-icon", ["medium-red", "medium-red"], /^COMMIT_EDITMSG$/],
    ["git-merge-icon", ["medium-red", "medium-red"], /^MERGE_(?:HEAD|MODE|MSG)$/],
    ["glade-icon", ["medium-green", "medium-green"], /\.glade$/i],
    ["pointwise-icon", ["medium-blue", "medium-blue"], /\.glf$/i],
    ["glyphs-icon", ["medium-green", "medium-green"], /\.glyphs$/i],
    ["gn-icon", ["dark-blue", "dark-blue"], /\.gn$/i, , !1, /^gn$/, /\.gn$/i, /^gn$/i],
    ["gn-icon", ["medium-blue", "medium-blue"], /\.gni$/i],
    ["gnu-icon", ["medium-red", "dark-red"], /\.(?:gnu|gplv[23])$/i],
    ["graph-icon", ["medium-red", "medium-red"], /\.(?:gp|plo?t|gnuplot)$/i, , !1, /^gnuplot$/, /\.gnuplot$/i, /^Gnuplot$/i],
    ["go-icon", ["medium-blue", "medium-blue"], /\.go$/i, , !1, , /\.go(?:template)?$/i, /^Go$/i],
    ["golo-icon", ["medium-orange", "medium-orange"], /\.golo$/i, , !1, , /\.golo$/i, /^Golo$/i],
    ["gosu-icon", ["medium-blue", "medium-blue"], /\.gs$/i, , !1, , /\.gosu(?:\.\d+)?$/i, /^Gosu$/i],
    ["gosu-icon", ["medium-green", "medium-green"], /\.gst$/i],
    ["gosu-icon", ["dark-green", "dark-green"], /\.gsx$/i],
    ["gosu-icon", ["dark-blue", "dark-blue"], /\.vark$/i],
    ["gradle-icon", ["medium-blue", "medium-blue"], /\.gradle$/i, , !1, , /\.gradle$/i, /^Gradle$/i],
    ["gradle-icon", ["dark-purple", "dark-purple"], /gradlew$/i],
    ["gf-icon", ["medium-red", "medium-red"], /\.gf$/i],
    ["graphql-icon", ["medium-pink", "medium-pink"], /\.graphql$/i, , !1, , /\.graphql$/i, /^GraphQL$/i],
    ["graphql-icon", ["medium-purple", "medium-purple"], /\.gql$/i],
    ["graphviz-icon", ["medium-blue", "medium-blue"], /\.gv$/i, , !1, , /\.dot$/i, /^Graphviz$/i],
    ["graphviz-icon", ["dark-cyan", "dark-cyan"], /\.dot$/i],
    ["groovy-icon", ["light-blue", "light-blue"], /\.(?:groovy|grt|gtpl|gsp|gvy)$/i, , !1, /^groovy$/, /\.groovy$/i, /^Groovy$|^gsp$/i],
    ["hack-icon", ["medium-orange", "medium-orange"], /\.hh$/i, , !1, , /\.hack$/i, /^Hack$/i],
    ["haml-icon", ["medium-yellow", "medium-yellow"], /\.haml$/i, , !1, /^haml$/, /\.haml$/i, /^haml$/i],
    ["haml-icon", ["medium-maroon", "medium-maroon"], /\.hamlc$/i, , !1, /^hamlc$/, /\.hamlc$/i, /^Haml$|^hamlc$/i],
    ["harbour-icon", ["dark-blue", "dark-blue"], /\.hb$/i, , !1, , /\.harbour$/i, /^Harbour$/i],
    ["hashicorp-icon", ["dark-purple", "dark-purple"], /\.hcl$/i, , !1, , /(?:^|\.)(?:hcl|hashicorp)(?:\.|$)/i, /^Hashicorp Configuration Language$/i],
    ["haskell-icon", ["medium-purple", "medium-purple"], /\.hs$/i, , !1, /^runhaskell$/, /\.source\.haskell$/i, /^Haskell$/i],
    ["haskell-icon", ["medium-blue", "medium-blue"], /\.hsc$/i, , !1, , /\.hsc2hs$/i, /^Haskell$/i],
    ["haskell-icon", ["dark-purple", "dark-purple"], /\.c2hs$/i, , !1, , /\.c2hs$/i, /^Haskell$|^C2hs(?:\s*Haskell)?$/i],
    ["haskell-icon", ["dark-blue", "dark-blue"], /\.lhs$/i, , !1, , /\.latex\.haskell$/i, /^Haskell$|^(?:lhaskell|lhs|Literate\s*Haskell)$/i],
    ["haxe-icon", ["medium-orange", "medium-orange"], /\.hx(?:[sm]l|)?$/, , !1, , /(?:^|\.)haxe(?:\.\d+)?$/i, /^Haxe$/i],
    ["heroku-icon", ["medium-purple", "medium-purple"], /^Procfile$/],
    ["heroku-icon", ["light-purple", "light-purple"], /\.buildpacks$/i],
    ["heroku-icon", ["dark-purple", "dark-purple"], /^\.vendor_urls$/],
    ["html5-icon", ["medium-orange", "medium-orange"], /\.x?html?$/i, , !1, , /\.html\.basic$/i, /^HTML$|^(?:xhtml|htm)$/i],
    ["html5-icon", ["medium-red", "medium-red"], /\.cshtml$|\.latte$/i, , !1, /^latte$/, /\.latte$/i],
    ["html5-icon", ["medium-green", "medium-green"], /\.ejs$|\.kit$|\.swig$/i, , !1, /^swig$/, /\.swig$/i],
    ["html5-icon", ["dark-blue", "dark-blue"], /\.gohtml$|\.phtml$/i, , !1, /^gohtml$/, /\.gohtml$/i, /^HTML$|^g[0o]html$/i],
    ["html5-icon", ["medium-purple", "medium-purple"], /\.html\.eex$|\.jsp$/i, , !1, , /\.jsp$/i],
    ["html5-icon", ["medium-cyan", "medium-cyan"], /\.shtml$/i],
    ["html5-icon", ["dark-red", "dark-red"], /\.scaml$/i, , !1, /^scaml$/, /\.scaml$/i, /^HTML$|^scaml$/i],
    ["html5-icon", ["medium-red", "medium-red"], /\.vash$/i, , !1, /^vash$/, /\.vash$/i, /^HTML$|^vash$/i],
    ["html5-icon", ["medium-blue", "medium-blue"], /\.dtml$/i, , !1, /^dtml$/, /\.dtml$/i, /^HTML$|^dtml$/i],
    ["hy-icon", ["dark-blue", "dark-blue"], /\.hy$/i, , !1, , /\.hy$/i, /^Hy$|^hylang$/i],
    ["idl-icon", ["medium-blue", "medium-blue"], /\.dlm$/i, , !1, , /\.idl$/i, /^IDL$/i],
    ["idris-icon", ["dark-red", "dark-red"], /\.idr$/i, , !1, , /\.(?:idris|ipkg)$/i, /^Idris$/i],
    ["idris-icon", ["medium-maroon", "medium-maroon"], /\.lidr$/i],
    ["igorpro-icon", ["dark-red", "dark-red"], /\.ipf$/i],
    ["image-icon", ["medium-orange", "medium-orange"], /\.a?png$|\.svgz$/i, , !1, , , , /^.PNG\r\n\n/],
    ["image-icon", ["medium-yellow", "medium-yellow"], /\.gif$|\.ora$|\.sgi$/i, , !1, , , , /^GIF8[97]a/],
    ["image-icon", ["medium-green", "medium-green"], /\.jpg$/i, , !1, , , , /^ÿØÿ[Ûàá]|(?:JFIF|Exif)\0|^Ï|^ÿØ.+ÿÙ$/],
    ["image-icon", ["medium-blue", "medium-blue"], /\.ico$/i, , !1, , , , /^\0{2}\0/],
    ["image-icon", ["dark-blue", "dark-blue"], /\.webp$|\.iff$|\.lbm$|\.liff$|\.nrrd$|\.pcx$|\.vsdx?$/i, , !1, , , , /^RIFF.{4}WEBPVP8/],
    ["image-icon", ["medium-red", "medium-red"], /\.bmp$/i, , !1, , , , /^BM/],
    ["image-icon", ["medium-red", "medium-red"], /\.bpg$/i, , !1, , , , /^BPGû/],
    ["image-icon", ["medium-orange", "medium-orange"], /\.cin$/i, , !1, , , , /^*_×/],
    ["image-icon", ["dark-green", "dark-green"], /\.cd5$/i, , !1, , , , /^_CD5\0/],
    ["image-icon", ["light-yellow", "light-yellow"], /\.cpc$/i],
    ["image-icon", ["medium-orange", "medium-orange"], /\.cr2$/i, , !1, , , , /^II\*\0\0{3}CR/],
    ["image-icon", ["medium-pink", "medium-pink"], /\.dcm$|\.mpo$|\.pbm$/i, , !1, , , , /^.{128}DICM/],
    ["image-icon", ["dark-green", "dark-green"], /\.dds$/i, , !1, , , , /^DDS \|\0{3}/],
    ["image-icon", ["medium-purple", "medium-purple"], /\.djvu?$|\.pxr$/i, , !1, , , , /^AT&TFORM/],
    ["image-icon", ["dark-orange", "dark-orange"], /\.dpx$|\.raw$/i, , !1, , , , /^(?:SDPX|XPDS)/],
    ["image-icon", ["light-blue", "light-blue"], /\.ecw$|\.sct$/i],
    ["image-icon", ["dark-yellow", "dark-yellow"], /\.exr$/i, , !1, , , , /^v\/1/],
    ["image-icon", ["medium-cyan", "medium-cyan"], /\.fits?$|\.fts$/i, , !1, , , , /^SIMPLE  =/],
    ["image-icon", ["dark-red", "dark-red"], /\.flif$|\.hdp$|\.heic$|\.heif$|\.jxr$|\.wdp$/i, , !1, , , , /^FLIF/],
    ["image-icon", ["medium-blue", "medium-blue"], /\.hdr$/i, , !1, , , , /^#\?RADIANCE\n/],
    ["image-icon", ["medium-pink", "medium-pink"], /\.icns$/i, , !1, , , , /^icns/],
    ["image-icon", ["dark-green", "dark-green"], /\.(?:jp[f2xm]|j2c|mj2)$/i, , !1, , , , /^\0{3}\fjP {2}/],
    ["image-icon", ["dark-cyan", "dark-cyan"], /\.jps$/i],
    ["image-icon", ["medium-orange", "medium-orange"], /\.mng$/i, , !1, , , , /^.MNG\r\n\n/],
    ["image-icon", ["light-red", "light-red"], /\.pgf$/i],
    ["image-icon", ["light-purple", "light-purple"], /\.pict$/i],
    ["image-icon", ["dark-orange", "dark-orange"], /\.tga$/i, , !1, , , , /TRUEVISION-XFILE\.\0$/],
    ["image-icon", ["medium-red", "medium-red"], /\.tiff?$/i, , !1, , , , /^II*\0|^MM\0*/],
    ["image-icon", ["dark-maroon", "dark-maroon"], /\.wbm$/i],
    ["inform7-icon", ["medium-blue", "medium-blue"], /\.ni$/i, , !1, , /\.inform-?7?$/i, /^Inform 7$|^i7$/i],
    ["inform7-icon", ["dark-blue", "dark-blue"], /\.i7x$/i],
    ["inno-icon", ["dark-blue", "dark-blue"], /\.iss$/i, , !1, , /\.inno$/i, /^Inno Setup$/i],
    ["io-icon", ["dark-purple", "dark-purple"], /\.io$/i, , !1, /^io$/, /^source\.io$/i, /^Io$/i],
    ["ioke-icon", ["medium-red", "medium-red"], /\.ik$/i, , !1, /^ioke$/],
    ["isabelle-icon", ["dark-red", "dark-red"], /\.thy$/i, , !1, , /\.isabelle\.theory$/i, /^Isabelle$/i],
    ["isabelle-icon", ["dark-blue", "dark-blue"], /^ROOT$/],
    ["j-icon", ["light-blue", "light-blue"], /\.ijs$/i, , !1, /^jconsole$/, /\.j$/i, /^J$/i],
    ["jade-icon", ["medium-red", "medium-red"], /\.jade$/i, , !1, , /\.jade$/i, /^Jade$/i],
    ["jake-icon", ["medium-maroon", "dark-maroon"], /^Jakefile$/],
    ["jake-icon", ["medium-yellow", "dark-yellow"], /\.jake$/i],
    ["java-icon", ["medium-purple", "medium-purple"], /\.java$/i, , !1, , /\.java$/i, /^Java$/i],
    ["js-icon", ["medium-yellow", "dark-yellow"], /\.js$|\.es6$|\.es$/i, , !1, /^(?:node|iojs)$/, /\.js$/i, /^JavaScript$|^(?:js|node)$/i],
    ["js-icon", ["medium-orange", "dark-orange"], /\._js$/i],
    ["js-icon", ["medium-maroon", "dark-maroon"], /\.jsb$|\.dust$/i],
    ["js-icon", ["medium-blue", "dark-blue"], /\.jsm$|\.mjs$|\.xsjslib$/i],
    ["js-icon", ["medium-green", "dark-green"], /\.jss$/i],
    ["js-icon", ["medium-pink", "dark-pink"], /\.sjs$/i],
    ["js-icon", ["medium-red", "dark-red"], /\.ssjs$/i],
    ["js-icon", ["medium-purple", "dark-purple"], /\.xsjs$/i],
    ["jenkins-icon", ["medium-red", "dark-red"], /^Jenkinsfile$/],
    ["jinja-icon", ["dark-red", "dark-red"], /\.jinja$/i, , !1, , /\.jinja$/i, /^Jinja$|^(?:django|htmldjango|html\+django\/jinja|html\+jinja)$/i],
    ["jinja-icon", ["medium-red", "medium-red"], /\.jinja2$/i],
    ["jsonld-icon", ["medium-blue", "medium-blue"], /\.jsonld$/i],
    ["sql-icon", ["medium-blue", "medium-blue"], /\.jq$/i, , !1, , /\.jq$/i, /^JSONiq$/i],
    ["jsx-icon", ["medium-blue", "dark-blue"], /\.jsx$/i, , !1, , /\.jsx$/i, /^JSX$/i],
    ["julia-icon", ["medium-purple", "medium-purple"], /\.jl$/i, , !1, , /\.julia$/i, /^Julia$/i],
    ["jupyter-icon", ["dark-orange", "dark-orange"], /\.ipynb$/i, , !1, , /\.ipynb$/i, /^(?:ipynb|(?:Jupyter|IPython)\s*Notebook)$/i],
    ["jupyter-icon", ["dark-cyan", "dark-cyan"], /^Notebook$/],
    ["keynote-icon", ["medium-blue", "medium-blue"], /\.keynote$/i],
    ["keynote-icon", ["dark-blue", "dark-blue"], /\.knt$/i],
    ["kivy-icon", ["dark-maroon", "dark-maroon"], /\.kv$/i, , !1, , /\.kv$/i, /^Kivy$/i],
    ["earth-icon", ["medium-green", "medium-green"], /\.kml$/i],
    ["kotlin-icon", ["dark-blue", "dark-blue"], /\.kt$/i, , !1, /^kotlin$/, /\.kotlin$/i, /^k[0o]tlin$/i],
    ["kotlin-icon", ["medium-blue", "medium-blue"], /\.ktm$/i],
    ["kotlin-icon", ["medium-orange", "medium-orange"], /\.kts$/i],
    ["krl-icon", ["medium-blue", "medium-blue"], /\.krl$/i, , !1, , /\.krl$/i, /^KRL$/i],
    ["labview-icon", ["dark-blue", "dark-blue"], /\.lvproj$/i],
    ["laravel-icon", ["medium-orange", "medium-orange"], /\.blade\.php$/i, , !1, , /\.php\.blade$/i, /^Laravel$/i],
    ["lasso-icon", ["dark-blue", "dark-blue"], /\.lasso$|\.las$/i, , !1, , /\.lasso$/i, /^Lasso$|^lass[0o]script$/i],
    ["lasso-icon", ["medium-blue", "medium-blue"], /\.lasso8$/i],
    ["lasso-icon", ["medium-purple", "medium-purple"], /\.lasso9$/i],
    ["lasso-icon", ["medium-red", "medium-red"], /\.ldml$/i],
    ["lean-icon", ["dark-purple", "dark-purple"], /\.lean$/i, , !1, /^lean$/, /\.lean$/i, /^lean$/i],
    ["lean-icon", ["dark-red", "dark-red"], /\.hlean$/i],
    ["lfe-icon", ["dark-red", "dark-red"], /\.lfe$/i],
    ["lightwave-icon", ["medium-red", "medium-red"], /\.lwo$/i],
    ["lightwave-icon", ["medium-blue", "medium-blue"], /\.lws$/i],
    ["lisp-icon", ["medium-red", "medium-red"], /\.lsp$/i, , !1, /^newlisp$/, /\.newlisp$/i, /^Lisp$|^newlisp$/i],
    ["lisp-icon", ["dark-red", "dark-red"], /\.lisp$/i, , !1, /^lisp$/, /\.lisp$/i, /^lisp$/i],
    ["lisp-icon", ["medium-maroon", "medium-maroon"], /\.l$|\.nl$/i, , !1, /picolisp|pil/],
    ["lisp-icon", ["medium-blue", "medium-blue"], /\.ny$|\.sexp$/i],
    ["lisp-icon", ["medium-purple", "medium-purple"], /\.podsl$/i],
    ["ls-icon", ["medium-blue", "medium-blue"], /\.ls$/i, , !1, , /\.livescript$/i, /^LiveScript$|^(?:ls|live-script)$/i],
    ["ls-icon", ["dark-blue", "dark-blue"], /\._ls$/i],
    ["ls-icon", ["medium-green", "medium-green"], /^Slakefile$/],
    ["llvm-icon", ["dark-green", "dark-green"], /\.ll$/i, , !1, /^llvm$/, /\.llvm$/i, /^llvm$/i],
    ["llvm-icon", ["medium-yellow", "dark-yellow"], /\.clang-format$/i],
    ["mobile-icon", ["dark-blue", "dark-blue"], /\.xm$/i, , !1, /^logos$/, /\.logos$/i, /^l[0o]g[0o]s$/i],
    ["mobile-icon", ["dark-red", "dark-red"], /\.xi$/i],
    ["logtalk-icon", ["medium-red", "medium-red"], /\.(?:logtalk|lgt)$/i, , !1, , /\.logtalk$/i, /^Logtalk$/i],
    ["lookml-icon", ["medium-purple", "medium-purple"], /\.lookml$/i],
    ["lsl-icon", ["medium-cyan", "medium-cyan"], /\.lsl$/i, , !1, /^lsl$/, /\.lsl$/i, /^lsl$/i],
    ["lsl-icon", ["dark-cyan", "dark-cyan"], /\.lslp$/i],
    ["lua-icon", ["medium-blue", "medium-blue"], /\.lua$/i, , !1, /^lua$/, /\.lua$/i, /^lua$/i],
    ["lua-icon", ["dark-blue", "dark-blue"], /\.pd_lua$/i],
    ["lua-icon", ["dark-purple", "dark-purple"], /\.rbxs$/i],
    ["lua-icon", ["dark-red", "dark-red"], /\.wlua$/i],
    ["checklist-icon", ["medium-yellow", "medium-yellow"], /^Makefile|^makefile$/, , !1, /^make$/, /\.makefile$/i, /^Makefile$|^(?:bsdmake|make|mf)$/i],
    ["checklist-icon", ["medium-yellow", "medium-yellow"], /\.(?:mk|mak|make)$|^mkfile$/i],
    ["checklist-icon", ["medium-red", "medium-red"], /^BSDmakefile$|\.am$/i],
    ["checklist-icon", ["medium-green", "medium-green"], /^GNUmakefile$/i],
    ["checklist-icon", ["medium-blue", "medium-blue"], /^Kbuild$/],
    ["checklist-icon", ["dark-blue", "dark-blue"], /\.bb$/i],
    ["checklist-icon", ["dark-blue", "dark-blue"], /^DEPS$/],
    ["checklist-icon", ["medium-blue", "medium-blue"], /\.mms$/i],
    ["checklist-icon", ["light-blue", "light-blue"], /\.mmk$/i],
    ["checklist-icon", ["dark-purple", "dark-purple"], /\.pri$/i],
    ["mako-icon", ["dark-blue", "dark-blue"], /\.mak?o$/i, , !1, , /\.mako$/i, /^Mako$/i],
    ["manpage-icon", ["dark-green", "dark-green"], /\.(?:1(?:[bcmsx]|has|in)?|[24568]|3(?:avl|bsm|3c|in|m|qt|x)?|7(?:d|fs|i|ipp|m|p)?|9[efps]?|chem|eqn|groff|man|mandoc|mdoc|me|mom|n|nroff|pic|tmac|tmac-u|tr|troff)$/i, , !1, /man|mandoc|(?:[gnt]|dit)roff/i, /\.[gt]?roff$/i, /^Manual Page$|^(?:[gtn]?roff|manpage)$/i, /^\.TH[ \t]+(?:\S+)|^'\\" [tre]+(?=\s|$)/],
    ["manpage-icon", ["dark-maroon", "dark-maroon"], /\.(?:rnh|rno|roff|run|runoff)$/i, , !1, /^runoff$/, /\.runoff$/i, /^Manual Page$|^run[0o]ff$/i],
    ["mapbox-icon", ["medium-cyan", "medium-cyan"], /\.mss$/i, , !1, , /\.mss$/i, /^Mapbox$|^Carto(?:CSS)?$/i],
    ["markdown-icon", ["medium-blue", "medium-blue"], /\.(?:md|mdown|markdown|mkd|mkdown|mkdn|rmd|ron)$/i, , !1, , /\.gfm$/i, /^Markdown$/i],
    ["mathematica-icon", ["dark-red", "dark-red"], /\.mathematica$|\.nbp$/i, , !1, , /\.mathematica$/i, /^Mathematica$|^mma$/i],
    ["mathematica-icon", ["medium-red", "medium-red"], /\.cdf$/i],
    ["mathematica-icon", ["medium-orange", "medium-orange"], /\.ma$/i],
    ["mathematica-icon", ["medium-maroon", "medium-maroon"], /\.mt$/i],
    ["mathematica-icon", ["dark-orange", "dark-orange"], /\.nb$/i],
    ["mathematica-icon", ["medium-yellow", "medium-yellow"], /\.wl$/i],
    ["mathematica-icon", ["dark-yellow", "dark-yellow"], /\.wlt$/i],
    ["matlab-icon", ["medium-yellow", "medium-yellow"], /\.matlab$/i, , !1, , /\.(?:matlab|octave)$/i, /^MATLAB$|^[0o]ctave$/i],
    ["max-icon", ["dark-purple", "dark-purple"], /\.maxpat$/i],
    ["max-icon", ["medium-red", "medium-red"], /\.maxhelp$/i],
    ["max-icon", ["medium-blue", "medium-blue"], /\.maxproj$/i],
    ["max-icon", ["medium-purple", "medium-purple"], /\.mxt$/i],
    ["max-icon", ["medium-green", "medium-green"], /\.pat$/i],
    ["maxscript-icon", ["dark-blue", "dark-blue"], /\.ms$/i, , !1, , /\.maxscript$/i, /^MAXScript$/i],
    ["maxscript-icon", ["dark-purple", "dark-purple"], /\.mcr$/i],
    ["maxscript-icon", ["medium-red", "medium-red"], /\.mce$/i],
    ["maxscript-icon", ["dark-cyan", "dark-cyan"], /\.max$/i],
    ["maxscript-icon", ["medium-cyan", "medium-cyan"], /\.3ds$/i],
    ["maya-icon", ["dark-cyan", "dark-cyan"], /\.mb$/i],
    ["maya-icon", ["dark-blue", "dark-blue"], /\.mel$/i],
    ["maya-icon", ["dark-purple", "dark-purple"], /\.mcf[ip]$/i],
    ["mediawiki-icon", ["medium-yellow", "medium-yellow"], /\.mediawiki$/i, , !1, /^mediawiki$/, /\.mediawiki$/i, /^mediawiki$/i],
    ["mediawiki-icon", ["medium-orange", "medium-orange"], /\.wiki$/i],
    ["bullhorn-icon", ["medium-orange", "medium-orange"], /^\.mention-bot$/i],
    ["mercury-icon", ["medium-cyan", "medium-cyan"], /\.moo$/i, , !1, /^mmi$/, /\.mercury$/i, /^Mercury$/i],
    ["metal-icon", ["dark-cyan", "dark-cyan"], /\.metal$/i],
    ["access-icon", ["dark-maroon", "dark-maroon"], /\.accda$/i],
    ["access-icon", ["medium-maroon", "medium-maroon"], /\.accdb$/i],
    ["access-icon", ["medium-green", "medium-green"], /\.accde$/i],
    ["access-icon", ["medium-red", "medium-red"], /\.accdr$/i],
    ["access-icon", ["dark-red", "dark-red"], /\.accdt$/i],
    ["access-icon", ["light-maroon", "light-maroon"], /\.adn$|\.laccdb$/i],
    ["access-icon", ["dark-purple", "dark-purple"], /\.mdw$/i],
    ["excel-icon", ["dark-orange", "dark-orange"], /\.xls$/i],
    ["excel-icon", ["dark-green", "dark-green"], /\.xlsx$/i],
    ["excel-icon", ["medium-green", "medium-green"], /\.xlsm$/i],
    ["excel-icon", ["medium-red", "medium-red"], /\.xlsb$/i],
    ["excel-icon", ["dark-cyan", "dark-cyan"], /\.xlt$/i],
    ["onenote-icon", ["dark-purple", "dark-purple"], /\.one$/i],
    ["powerpoint-icon", ["dark-red", "dark-red"], /\.pps$/i],
    ["powerpoint-icon", ["medium-orange", "medium-orange"], /\.ppsx$/i],
    ["powerpoint-icon", ["dark-orange", "dark-orange"], /\.ppt$/i],
    ["powerpoint-icon", ["medium-red", "medium-red"], /\.pptx$/i],
    ["powerpoint-icon", ["medium-maroon", "medium-maroon"], /\.potm$/i],
    ["powerpoint-icon", ["dark-green", "dark-green"], /\.mpp$/i],
    ["word-icon", ["medium-blue", "medium-blue"], /\.doc$/i],
    ["word-icon", ["dark-blue", "dark-blue"], /\.docx$/i],
    ["word-icon", ["medium-maroon", "medium-maroon"], /\.docm$/i],
    ["word-icon", ["dark-cyan", "dark-cyan"], /\.docxml$/i],
    ["word-icon", ["dark-maroon", "dark-maroon"], /\.dotm$/i],
    ["word-icon", ["medium-cyan", "medium-cyan"], /\.dotx$/i],
    ["word-icon", ["medium-orange", "medium-orange"], /\.wri$/i],
    ["minecraft-icon", ["dark-green", "dark-green"], /^mcmod\.info$/i, , !1, , /\.forge-config$/i, /^Minecraft$/i],
    ["mirah-icon", ["medium-blue", "medium-blue"], /\.dr?uby$/g, , !1, /^mirah$/, /\.mirah$/i, /^mirah$/i],
    ["mirah-icon", ["light-blue", "light-blue"], /\.mir(?:ah)?$/g],
    ["model-icon", ["medium-red", "medium-red"], /\.obj$/i, , !1, , /\.wavefront\.obj$/i],
    ["model-icon", ["dark-blue", "dark-blue"], /\.mtl$/i, , !1, , /\.wavefront\.mtl$/i],
    ["model-icon", ["dark-green", "dark-green"], /\.stl$/i],
    ["model-icon", ["medium-orange", "medium-orange"], /\.u3d$/i],
    ["circle-icon", ["light-red", "light-red"], /\.mo$/i, , !1, , /\.modelica(?:script)?$/i, /^Modelica$/i],
    ["modula2-icon", ["medium-blue", "medium-blue"], /\.mod$/i, , !1, , /(?:^|\.)modula-?2(?:\.|$)/i, /^Modula-2$/i],
    ["modula2-icon", ["medium-green", "medium-green"], /\.def$/i],
    ["modula2-icon", ["medium-red", "medium-red"], /\.m2$/i],
    ["monkey-icon", ["medium-maroon", "medium-maroon"], /\.monkey$/i, , !1, , /\.monkey$/i, /^Monkey$/i],
    ["moon-icon", ["medium-yellow", "medium-yellow"], /\.moon$/i, , !1, /^moon$/, /\.moon$/i, /^MoonScript$/i],
    ["mruby-icon", ["medium-red", "medium-red"], /\.mrb$/i, , !1, /^mruby$/],
    ["msql-icon", ["medium-purple", "medium-purple"], /\.dsql$/i],
    ["mupad-icon", ["medium-red", "medium-red"], /\.mu$/i],
    ["music-icon", ["medium-orange", "medium-orange"], /\.chord$/i],
    ["music-icon", ["dark-blue", "dark-blue"], /\.midi?$/i, , !1, , , , /^MThd/],
    ["music-icon", ["medium-green", "medium-green"], /\.ly$/i, , !1, , /\.(?:At)?lilypond-/i, /^Lily\s*Pond$/i],
    ["music-icon", ["dark-green", "dark-green"], /\.ily$/i],
    ["music-icon", ["dark-red", "dark-red"], /\.pd$/i],
    ["mustache-icon", ["medium-orange", "medium-orange"], /\.(?:hbs|handlebars|mustache)$/i, , !1, , /(?:^|\.)(?:mustache|handlebars)(?:\.|$)/i, /^Mustache$|^(?:hbs|htmlbars|handlebars)$/i],
    ["nant-icon", ["medium-orange", "medium-orange"], /\.build$/i, , !1, , /\.nant-build$/i, /^NAnt$/i],
    ["earth-icon", ["medium-green", "medium-green"], /\.ncl$/i, , !1, , /\.ncl$/i, /^NCAR Command Language \(NCL\)$/i],
    ["neko-icon", ["medium-orange", "medium-orange"], /\.neko$/i, , !1, /^neko$/, /\.neko$/i, /^nek[0o]$/i],
    ["amx-icon", ["medium-blue", "medium-blue"], /\.axs$/i],
    ["amx-icon", ["dark-blue", "dark-blue"], /\.axi$/i],
    ["netlogo-icon", ["medium-red", "medium-red"], /\.nlogo$/i],
    ["nginx-icon", ["medium-green", "medium-green"], /\.nginxconf$/i, , !1, , /\.nginx$/i, /^NGINX$|^nginx[\W_ \t]?c[0o]nfigurati[0o]n[\W_ \t]?file$/i],
    ["nib-icon", ["dark-orange", "dark-orange"], /\.nib$/i],
    ["nimrod-icon", ["medium-green", "medium-green"], /\.nim(?:rod)?$/i, , !1, , /\.nim$/i, /^Nimrod$/i],
    ["shuriken-icon", ["medium-blue", "medium-blue"], /\.ninja$/i, , !1, /^ninja$/, /\.ninja$/i, /^ninja$/i],
    ["nit-icon", ["dark-green", "dark-green"], /\.nit$/i, , !1, , /\.nit$/i, /^Nit$/i],
    ["nix-icon", ["medium-cyan", "medium-cyan"], /\.nix$/i, , !1, , /\.nix$/i, /^Nix$|^nix[0o]s$/i],
    ["nmap-icon", ["dark-blue", "dark-blue"], /\.nse$/i, , !1, , /\.nmap$/i, /^Nmap$/i],
    ["node-icon", ["medium-green", "medium-green"], /\.njs$|\.nvmrc$/i],
    ["node-icon", ["dark-green", "dark-green"], /\.node-version$/i],
    ["nsis-icon", ["medium-purple", "medium-purple"], /\.nsi$/i, , !1, /^nsis$/, /\.nsis$/i, /^nsis$/i],
    ["nsis-icon", ["dark-cyan", "dark-cyan"], /\.nsh$/i],
    ["recycle-icon", ["light-green", "light-green"], /\.nu$/i, , !1, /^nush$/, /\.nu$/i, /^Nu$|^nush$/i],
    ["recycle-icon", ["dark-green", "dark-green"], /^Nukefile$/],
    ["nuget-icon", ["medium-blue", "medium-blue"], /\.nuspec$/i],
    ["nuget-icon", ["dark-purple", "dark-purple"], /\.pkgproj$/i],
    ["numpy-icon", ["dark-blue", "dark-blue"], /\.numpy$/i],
    ["numpy-icon", ["medium-blue", "medium-blue"], /\.numpyw$/i],
    ["numpy-icon", ["medium-orange", "medium-orange"], /\.numsc$/i],
    ["nunjucks-icon", ["dark-green", "dark-green"], /\.(?:nunjucks|njk)$/i],
    ["objc-icon", ["medium-blue", "medium-blue"], /\.mm?$/i, , !1, , /\.objc(?:pp)?$/i, /^Objective-C$|^(?:Obj-?C|ObjectiveC)(?:\+\+)?$/i],
    ["objc-icon", ["dark-red", "dark-red"], /\.pch$/i],
    ["objc-icon", ["dark-green", "dark-green"], /\.x$/i],
    ["objj-icon", ["dark-orange", "dark-orange"], /\.j$/i, , !1, , /\.objj$/i, /^Objective-J$|^(?:Obj-?J|ObjectiveJ)$/i],
    ["objj-icon", ["dark-red", "dark-red"], /\.sj$/i],
    ["ocaml-icon", ["medium-orange", "medium-orange"], /\.ml$/i, , !1, /ocaml(?:run|script)?/, /\.ocaml$/i, /^OCaml$/i],
    ["ocaml-icon", ["dark-orange", "dark-orange"], /\.mli$/i],
    ["ocaml-icon", ["medium-red", "medium-red"], /\.eliom$/i],
    ["ocaml-icon", ["dark-red", "dark-red"], /\.eliomi$/i],
    ["ocaml-icon", ["medium-green", "medium-green"], /\.ml4$/i],
    ["ocaml-icon", ["dark-green", "dark-green"], /\.mll$/i, , !1, /^ocamllex$/, /\.ocamllex$/i, /^OCaml$|^[0o]camllex$/i],
    ["ocaml-icon", ["dark-yellow", "dark-yellow"], /\.mly$/i, , !1, /^menhir$/, /\.menhir$/i, /^OCaml$|^menhir$/i],
    ["ooc-icon", ["medium-green", "medium-green"], /\.ooc$/i, , !1, , /\.ooc$/i, /^OOC$/i],
    ["opa-icon", ["medium-blue", "medium-blue"], /\.opa$/i, , !1, , /\.opa$/i, /^Opa$/i],
    ["opencl-icon", ["medium-red", "medium-red"], /\.opencl$/i, , !1, , /\.opencl$/i, /^OpenCL$/i],
    ["progress-icon", ["medium-red", "medium-red"], /\.p$/i, , !1, , /\.abl$/i, /^OpenEdge ABL$|^(?:progress|openedge|abl)$/i],
    ["openoffice-icon", ["medium-blue", "medium-blue"], /\.odt$/i],
    ["openoffice-icon", ["dark-blue", "dark-blue"], /\.ott$/i],
    ["openoffice-icon", ["dark-purple", "dark-purple"], /\.fodt$/i],
    ["openoffice-icon", ["medium-green", "medium-green"], /\.ods$/i],
    ["openoffice-icon", ["dark-green", "dark-green"], /\.ots$/i],
    ["openoffice-icon", ["dark-cyan", "dark-cyan"], /\.fods$/i],
    ["openoffice-icon", ["medium-purple", "medium-purple"], /\.odp$/i],
    ["openoffice-icon", ["dark-pink", "dark-pink"], /\.otp$/i],
    ["openoffice-icon", ["medium-pink", "medium-pink"], /\.fodp$/i],
    ["openoffice-icon", ["medium-red", "medium-red"], /\.odg$/i],
    ["openoffice-icon", ["dark-red", "dark-red"], /\.otg$/i],
    ["openoffice-icon", ["dark-orange", "dark-orange"], /\.fodg$/i],
    ["openoffice-icon", ["medium-maroon", "medium-maroon"], /\.odf$/i],
    ["openoffice-icon", ["light-pink", "light-pink"], /\.odb$/i],
    ["scad-icon", ["medium-orange", "medium-orange"], /\.scad$/i, , !1, , /\.scad$/i, /^OpenSCAD$/i],
    ["scad-icon", ["medium-yellow", "medium-yellow"], /\.jscad$/i],
    ["org-icon", ["dark-green", "dark-green"], /\.org$/i],
    ["osx-icon", ["medium-red", "medium-red"], /\.dmg$/i, , !1, , , , /^xsbb`/],
    ["ox-icon", ["medium-cyan", "dark-cyan"], /\.ox$/i, , !1, , /\.ox$/i, /^Ox$/i],
    ["ox-icon", ["medium-green", "dark-green"], /\.oxh$/i],
    ["ox-icon", ["medium-blue", "dark-blue"], /\.oxo$/i],
    ["oxygene-icon", ["medium-cyan", "dark-cyan"], /\.oxygene$/i, , !1, , /\.oxygene$/i, /^Oxygene$/i],
    ["oz-icon", ["medium-yellow", "medium-yellow"], /\.oz$/i, , !1, , /\.oz$/i, /^Oz$/i],
    ["pan-icon", ["medium-red", "medium-red"], /\.pan$/i],
    ["papyrus-icon", ["medium-green", "medium-green"], /\.psc$/i, , !1, , /(?:^|\.)(?:papyrus\.skyrim|compiled-?papyrus|papyrus-assembly)(?:\.|$)/i, /^Papyrus$/i],
    ["parrot-icon", ["medium-green", "medium-green"], /\.parrot$/i, , !1, /^parrot$/],
    ["parrot-icon", ["dark-green", "dark-green"], /\.pasm$/i, , !1, , /\.parrot\.pasm$/i, /^Parrot$|^pasm$/i],
    ["parrot-icon", ["dark-blue", "dark-blue"], /\.pir$/i, , !1, , /\.parrot\.pir$/i, /^Parrot$|^pir$/i],
    ["pascal-icon", ["medium-purple", "medium-purple"], /\.pas(?:cal)?$/i, , !1, /pascal|instantfpc/, /\.pascal$/i, /^Pascal$/i],
    ["pascal-icon", ["medium-blue", "medium-blue"], /\.dfm$/i],
    ["pascal-icon", ["dark-blue", "dark-blue"], /\.dpr$/i],
    ["pascal-icon", ["dark-purple", "dark-purple"], /\.lpr$/i],
    ["patch-icon", ["medium-green", "medium-green"], /\.patch$/i],
    ["pawn-icon", ["medium-orange", "medium-orange"], /\.pwn$/i, , !1, , /\.pwn$/i, /^PAWN$/i],
    ["pdf-icon", ["medium-red", "medium-red"], /\.pdf$/i, , !1, , , , /^%PDF/],
    ["perl-icon", ["medium-blue", "medium-blue"], /\.p(?:er)?l$|\.t$/i, , !1, /^perl$/, /\.perl$/i, /^perl$/i],
    ["perl-icon", ["dark-purple", "dark-purple"], /\.ph$/i],
    ["perl-icon", ["medium-purple", "medium-purple"], /\.plx$/i],
    ["perl-icon", ["dark-blue", "dark-blue"], /\.pm$/i],
    ["perl-icon", ["medium-red", "medium-red"], /\.(?:psgi|xs)$/i],
    ["perl6-icon", ["medium-purple", "medium-purple"], /\.pl6$/i, , !1, /^perl6$/, /(?:^|\.)perl6(?:fe)?(?=\.|$)/, /^(?:pl6|Perl\s*6)$/i],
    ["perl6-icon", ["light-blue", "light-blue"], /\.[tp]6$|\.6pl$/i],
    ["perl6-icon", ["dark-pink", "dark-pink"], /\.(?:pm6|p6m)$/i],
    ["perl6-icon", ["dark-cyan", "dark-cyan"], /\.6pm$/i],
    ["perl6-icon", ["dark-purple", "dark-purple"], /\.nqp$/i],
    ["perl6-icon", ["medium-blue", "medium-blue"], /\.p6l$/i],
    ["perl6-icon", ["dark-green", "dark-green"], /\.pod6$/i],
    ["perl6-icon", ["medium-green", "medium-green"], /^Rexfile$/],
    ["phalcon-icon", ["medium-cyan", "medium-cyan"], /\.volt$/i, , !1, , /\.volt$/i, /^Phalcon$/i],
    ["php-icon", ["dark-blue", "dark-blue"], /\.php(?:[st\d]|_cs)?$/i, , !1, /^php$/, /\.php$/i, /^PHP$/i, /^<\?php/],
    ["php-icon", ["dark-green", "dark-green"], /^Phakefile/],
    ["pickle-icon", ["dark-cyan", "dark-cyan"], /\.pkl$/i],
    ["pike-icon", ["dark-cyan", "dark-cyan"], /\.pike$/i, , !1, /^pike$/],
    ["pike-icon", ["medium-blue", "medium-blue"], /\.pmod$/i],
    ["sql-icon", ["medium-red", "medium-red"], /\.(?:pls|pck|pks|plb|plsql|pkb)$/i, , !1, , /\.plsql(?:\.oracle)?(?:\.|$)/i, /^PLSQL$/i],
    ["pod-icon", ["dark-blue", "dark-blue"], /\.pod$/i],
    ["pogo-icon", ["medium-orange", "dark-orange"], /\.pogo$/i, , !1, , /\.pogoscript$/i, /^PogoScript$/i],
    ["pony-icon", ["light-maroon", "light-maroon"], /\.pony$/i, , !1, , /\.pony$/i, /^Pony$/i],
    ["postcss-icon", ["dark-red", "dark-red"], /\.p(?:ost)?css$/i, , !1, /^postcss$/, /\.postcss$/i, /^p[0o]stcss$/i],
    ["postcss-icon", ["dark-pink", "dark-pink"], /\.sss$/i, , !1, /^sugarss$/, /\.sugarss$/i, /^PostCSS$|^sugarss$/i],
    ["postcss-icon", ["medium-orange", "dark-orange"], /\.postcssrc$/i],
    ["postscript-icon", ["medium-red", "medium-red"], /\.ps$/i, , !1, , /\.postscript$/i, /^PostScript$|^p[0o]stscr$/i, /^%!PS/],
    ["postscript-icon", ["medium-orange", "medium-orange"], /\.eps$/i],
    ["postscript-icon", ["dark-blue", "dark-blue"], /\.pfa$/i],
    ["postscript-icon", ["medium-green", "medium-green"], /\.afm$/i],
    ["povray-icon", ["dark-blue", "dark-blue"], /\.pov$/i],
    ["powerbuilder-icon", ["medium-blue", "medium-blue"], /\.pbl$|\.sra$/i],
    ["powerbuilder-icon", ["dark-blue", "dark-blue"], /\.pbt$/i],
    ["powerbuilder-icon", ["medium-red", "medium-red"], /\.srw$/i],
    ["powerbuilder-icon", ["medium-orange", "medium-orange"], /\.sru$/i],
    ["powerbuilder-icon", ["medium-maroon", "medium-maroon"], /\.srp$/i],
    ["powerbuilder-icon", ["medium-purple", "medium-purple"], /\.srj$/i],
    ["powershell-icon", ["medium-blue", "medium-blue"], /\.ps1$/i, , !1, , /\.powershell$/i, /^PowerShell$|^p[0o]sh$/i],
    ["powershell-icon", ["dark-blue", "dark-blue"], /\.psd1$/i],
    ["powershell-icon", ["medium-purple", "medium-purple"], /\.psm1$/i],
    ["powershell-icon", ["dark-purple", "dark-purple"], /\.ps1xml$/i],
    ["print-icon", ["dark-cyan", "dark-cyan"], /\.ppd$/i],
    ["processing-icon", ["dark-blue", "dark-blue"], /\.pde$/i, , !1, , /\.processing$/i, /^Processing$/i],
    ["prolog-icon", ["medium-blue", "medium-blue"], /\.pro$/i, , !1, /^swipl$/, /\.prolog$/i, /^Prolog$/i],
    ["prolog-icon", ["medium-cyan", "medium-cyan"], /\.prolog$/i],
    ["prolog-icon", ["medium-purple", "medium-purple"], /\.yap$/i, , !1, /^yap$/],
    ["propeller-icon", ["medium-orange", "medium-orange"], /\.spin$/i, , !1, , /\.spin$/i, /^Propeller Spin$/i],
    ["pug-icon", ["medium-red", "medium-red"], /\.pug$/i, , !1, , /\.pug$/i, /^Pug$/i],
    ["puppet-icon", ["medium-purple", "medium-purple"], /\.pp$/i, , !1, /^puppet$/, /\.puppet$/i, /^puppet$/i],
    ["puppet-icon", ["dark-blue", "dark-blue"], /Modulefile$/i],
    ["purebasic-icon", ["medium-red", "medium-red"], /\.pb$/i, , !1, /^purebasic$/, /\.purebasic$/i, /^purebasic$/i],
    ["purebasic-icon", ["dark-orange", "dark-orange"], /\.pbi$/i],
    ["purescript-icon", ["dark-purple", "dark-purple"], /\.purs$/i, , !1, , /\.purescript$/i, /^PureScript$/i],
    ["python-icon", ["dark-blue", "dark-blue"], /\.py$|\.bzl$|\.py3$|\.?(?:pypirc|pythonrc|python-venv)$/i, , !1, /python[\d.]*/, /\.python$/i, /^Python$|^rusth[0o]n$/i],
    ["python-icon", ["medium-blue", "medium-blue"], /\.ipy$/i],
    ["python-icon", ["dark-green", "dark-green"], /\.isolate$|\.gypi$|\.pyt$/i],
    ["python-icon", ["medium-orange", "medium-orange"], /\.pep$|\.pyde$/i, , !1, /^pep8$/, /\.pep8$/i, /^Python$|^pep8$/i],
    ["python-icon", ["medium-green", "medium-green"], /\.gyp$/i],
    ["python-icon", ["dark-purple", "dark-purple"], /\.pyp$/i],
    ["python-icon", ["medium-maroon", "medium-maroon"], /\.pyw$/i],
    ["python-icon", ["dark-pink", "dark-pink"], /\.tac$/i],
    ["python-icon", ["dark-red", "dark-red"], /\.wsgi$/i],
    ["python-icon", ["medium-yellow", "dark-yellow"], /\.xpy$/i],
    ["python-icon", ["medium-pink", "medium-pink"], /\.rpy$/i, , !1, , /\.renpy$/i, /^Python$|^Ren'?Py$/i],
    ["python-icon", ["dark-green", "dark-green"], /^(?:BUCK|BUILD|SConstruct|SConscript)$/],
    ["python-icon", ["medium-green", "medium-green"], /^(?:Snakefile|WATCHLISTS)$/],
    ["python-icon", ["dark-maroon", "dark-maroon"], /^wscript$/],
    ["r-icon", ["medium-blue", "medium-blue"], /\.(?:r|Rprofile|rsx|rd)$/i, , !1, /^Rscript$/, /\.r$/i, /^R$|^(?:Rscript|splus|Rlang)$/i],
    ["racket-icon", ["medium-red", "medium-red"], /\.rkt$/i, , !1, /^racket$/, /\.racket$/i, /^racket$/i],
    ["racket-icon", ["medium-blue", "medium-blue"], /\.rktd$/i],
    ["racket-icon", ["light-red", "light-red"], /\.rktl$/i],
    ["racket-icon", ["dark-blue", "dark-blue"], /\.scrbl$/i, , !1, /^scribble$/, /\.scribble$/i, /^Racket$|^scribble$/i],
    ["raml-icon", ["medium-cyan", "medium-cyan"], /\.raml$/i, , !1, , /\.raml$/i, /^RAML$/i],
    ["rascal-icon", ["medium-yellow", "medium-yellow"], /\.rsc$/i, , !1, , /\.rascal$/i, /^Rascal$/i],
    ["rdoc-icon", ["medium-red", "medium-red"], /\.rdoc$/i, , !1, , /\.rdoc$/i, /^RDoc$/i],
    ["xojo-icon", ["medium-green", "medium-green"], /\.rbbas$/i],
    ["xojo-icon", ["dark-green", "dark-green"], /\.rbfrm$/i],
    ["xojo-icon", ["dark-cyan", "dark-cyan"], /\.rbmnu$/i],
    ["xojo-icon", ["medium-cyan", "medium-cyan"], /\.rbres$/i],
    ["xojo-icon", ["medium-blue", "medium-blue"], /\.rbtbar$/i],
    ["xojo-icon", ["dark-blue", "dark-blue"], /\.rbuistate$/i],
    ["reason-icon", ["medium-red", "medium-red"], /\.re$/i, , !1, /^reason$/, /\.reason$/i, /^reas[0o]n$/i],
    ["reason-icon", ["medium-orange", "medium-orange"], /\.rei$/i],
    ["rebol-icon", ["dark-green", "dark-green"], /\.reb(?:ol)?$/i, , !1, /^rebol$/, /\.rebol$/i, /^reb[0o]l$/i],
    ["rebol-icon", ["dark-red", "dark-red"], /\.r2$/i],
    ["rebol-icon", ["dark-blue", "dark-blue"], /\.r3$/i],
    ["red-icon", ["medium-red", "medium-red"], /\.red$/i, , !1, , /\.red$/i, /^Red$|^red\/?system$/i],
    ["red-icon", ["light-red", "light-red"], /\.reds$/i],
    ["red-hat-icon", ["medium-red", "medium-red"], /\.rpm$/i],
    ["red-hat-icon", ["dark-red", "dark-red"], /\.spec$/i],
    ["regex-icon", ["medium-green", "medium-green"], /\.regexp?$/i, , !1, , /(?:\.|^)regexp?(?:\.|$)/i, /^RegExp$/i],
    ["android-icon", ["dark-maroon", "dark-maroon"], /\.rsh$/i],
    ["rst-icon", ["dark-blue", "dark-blue"], /\.re?st(?:\.txt)?$/i, , !1, , /\.restructuredtext$/i, /^reStructuredText$|^re?st$/i],
    ["rexx-icon", ["medium-red", "medium-red"], /\.rexx?$/i, , !1, /rexx|regina/i, /\.rexx$/i, /^REXX$/i],
    ["rexx-icon", ["medium-blue", "medium-blue"], /\.pprx$/i],
    ["riot-icon", ["medium-red", "medium-red"], /\.tag$/i, , !1, , /\.riot$/i, /^RiotJS$/i],
    ["robot-icon", ["medium-purple", "medium-purple"], /\.robot$/i],
    ["clojure-icon", ["medium-red", "medium-red"], /\.rg$/i],
    ["rss-icon", ["medium-orange", "medium-orange"], /\.rss$/i],
    ["ruby-icon", ["medium-red", "medium-red"], /\.(?:rb|ru|ruby|erb|gemspec|god|mspec|pluginspec|podspec|rabl|rake|opal)$|^\.?(?:irbrc|gemrc|pryrc|rspec|ruby-(?:gemset|version))$/i, , !1, /(?:mac|j)?ruby|rake|rbx/, /\.ruby$/i, /^Ruby$|^(?:rbx?|rake|jruby|macruby)$/i],
    ["ruby-icon", ["medium-red", "medium-red"], /^(?:Appraisals|(?:Rake|Gem|[bB]uild|Berks|Cap|Danger|Deliver|Fast|Guard|Jar|Maven|Pod|Puppet|Snap)file(?:\.lock)?)$|^rails$/],
    ["ruby-icon", ["dark-red", "dark-red"], /\.(?:jbuilder|rbuild|rb[wx]|builder)$/i],
    ["ruby-icon", ["dark-yellow", "dark-yellow"], /\.watchr$/i],
    ["rust-icon", ["medium-maroon", "medium-maroon"], /\.rs$/i, , !1, /^rust$/, /\.rust$/i, /^rust$/i],
    ["rust-icon", ["light-maroon", "light-maroon"], /\.rlib$/i],
    ["sage-icon", ["medium-blue", "medium-blue"], /\.sage$/i, , !1, /^sage$/, /\.sage$/i, /^sage$/i],
    ["sage-icon", ["dark-blue", "dark-blue"], /\.sagews$/i],
    ["saltstack-icon", ["medium-blue", "dark-blue"], /\.sls$/i, , !1, , /\.salt$/i, /^SaltStack$|^Salt(?:State)?$/i],
    ["sas-icon", ["medium-blue", "medium-blue"], /\.sas$/i, , !1, , /\.sas$/i, /^SAS$/i],
    ["sass-icon", ["light-pink", "light-pink"], /\.scss$/i, , !1, /^scss$/, /\.scss$/i, /^Sass$|^scss$/i],
    ["sass-icon", ["dark-pink", "dark-pink"], /\.sass$/i, , !1, /^sass$/, /\.sass$/i, /^sass$/i],
    ["sbt-icon", ["dark-purple", "dark-purple"], /\.sbt$/i],
    ["scala-icon", ["medium-red", "medium-red"], /\.(?:sc|scala)$/i, , !1, /^scala$/, /\.scala$/i, /^Scala$/i],
    ["scheme-icon", ["medium-red", "medium-red"], /\.scm$/i, , !1, /guile|bigloo|chicken/, /\.scheme$/i, /^Scheme$/i],
    ["scheme-icon", ["medium-blue", "medium-blue"], /\.sld$/i],
    ["scheme-icon", ["medium-purple", "medium-purple"], /\.sps$/i],
    ["scilab-icon", ["dark-purple", "dark-purple"], /\.sci$/i, , !1, /^scilab$/, /\.scilab$/i, /^scilab$/i],
    ["scilab-icon", ["dark-blue", "dark-blue"], /\.sce$/i],
    ["scilab-icon", ["dark-cyan", "dark-cyan"], /\.tst$/i],
    ["secret-icon", [null, null], /\.secret$/i],
    ["self-icon", ["dark-blue", "dark-blue"], /\.self$/i, , !1, , /\.self$/i, /^Self$/i],
    ["graph-icon", ["light-red", "light-red"], /\.csv$/i, , !1, , /(?:^|\.)csv(?:\.semicolon)?(?:\.|$)/i],
    ["graph-icon", ["light-green", "light-green"], /\.(?:tab|tsv)$/i],
    ["graph-icon", ["medium-green", "medium-green"], /\.dif$/i],
    ["graph-icon", ["medium-cyan", "medium-cyan"], /\.slk$/i],
    ["sf-icon", ["light-orange", "light-orange"], /\.sfproj$/i],
    ["terminal-icon", ["medium-purple", "medium-purple"], /\.(?:sh|rc|bats|bash|tool|install|command)$/i, , !1, /bash|sh|zsh|rc/, /\.shell$/i, /^(?:sh|shell|Shell-?Script|Bash)$/i],
    ["terminal-icon", ["dark-purple", "dark-purple"], /^(?:\.?bash(?:rc|[-_]?(?:profile|login|logout|history|prompt))|_osc|config|install-sh|PKGBUILD)$/i],
    ["terminal-icon", ["dark-yellow", "dark-yellow"], /\.ksh$/i],
    ["terminal-icon", ["medium-yellow", "dark-yellow"], /\.sh-session$/i, , !1, , /\.shell-session$/i, /^(?:Bash|Shell|Sh)[-\s]*(?:Session|Console)$/i],
    ["terminal-icon", ["medium-blue", "medium-blue"], /\.zsh(?:-theme|_history)?$|^\.?(?:antigen|zpreztorc|zlogin|zlogout|zprofile|zshenv|zshrc)$|\.tmux$/i],
    ["terminal-icon", ["medium-green", "medium-green"], /\.fish$|^\.fishrc$|\.tcsh$/i, , !1, /^fish$/, /\.fish$/i, /^fish$/i],
    ["terminal-icon", ["medium-red", "medium-red"], /\.inputrc$/i],
    ["terminal-icon", ["medium-red", "medium-red"], /^(?:configure|config\.(?:guess|rpath|status|sub)|depcomp|libtool|compile)$/],
    ["terminal-icon", ["dark-purple", "dark-purple"], /^\/(?:private\/)?etc\/(?:[^\/]+\/)*(?:profile$|nanorc$|rc\.|csh\.)/i, , !0],
    ["terminal-icon", ["medium-yellow", "medium-yellow"], /\.csh$/i],
    ["shen-icon", ["dark-cyan", "dark-cyan"], /\.shen$/i],
    ["shopify-icon", ["medium-green", "medium-green"], /\.liquid$/i],
    ["sigils-icon", ["dark-red", "dark-red"], /\.sigils$/i],
    ["silverstripe-icon", ["medium-blue", "medium-blue"], /\.ss$/i, , !1, , /(?:^|\.)ss(?:template)?(?:\.|$)/i, /^SilverStripe$/i],
    ["sketch-icon", ["medium-orange", "medium-orange"], /\.sketch$/i],
    ["slash-icon", ["dark-blue", "dark-blue"], /\.sl$/i, , !1, , /\.slash$/i, /^Slash$/i],
    ["android-icon", ["medium-green", "medium-green"], /\.smali$/i, , !1, , /\.smali$/i, /^Smali$/i],
    ["smarty-icon", ["medium-yellow", "dark-yellow"], /\.tpl$/i, , !1, , /\.smarty$/i, /^Smarty$/i],
    ["snyk-icon", ["dark-purple", "dark-purple"], /\.snyk$/i],
    ["clojure-icon", ["medium-yellow", "dark-yellow"], /\.(?:sma|sp)$/i, , !1, , /\.sp$/i, /^SourcePawn$|^s[0o]urcem[0o]d$/i],
    ["sparql-icon", ["medium-blue", "medium-blue"], /\.sparql$/i, , !1, , /\.rq$/i, /^SPARQL$/i],
    ["sparql-icon", ["dark-blue", "dark-blue"], /\.rq$/i],
    ["sqf-icon", ["dark-maroon", "dark-maroon"], /\.sqf$/i, , !1, /^sqf$/, /\.sqf$/i, /^sqf$/i],
    ["sqf-icon", ["dark-red", "dark-red"], /\.hqf$/i],
    ["sql-icon", ["medium-orange", "medium-orange"], /\.(?:my)?sql$/i, , !1, /^sql$/, /\.sql$/i, /^sql$/i],
    ["sql-icon", ["medium-blue", "medium-blue"], /\.ddl$/i],
    ["sql-icon", ["medium-green", "medium-green"], /\.udf$/i],
    ["sql-icon", ["dark-cyan", "dark-cyan"], /\.viw$/i],
    ["sql-icon", ["dark-blue", "dark-blue"], /\.prc$/i],
    ["sql-icon", ["medium-purple", "medium-purple"], /\.db2$/i],
    ["sqlite-icon", ["medium-blue", "medium-blue"], /\.sqlite$/i],
    ["sqlite-icon", ["dark-blue", "dark-blue"], /\.sqlite3$/i],
    ["sqlite-icon", ["medium-purple", "medium-purple"], /\.db$/i],
    ["sqlite-icon", ["dark-purple", "dark-purple"], /\.db3$/i],
    ["squirrel-icon", ["medium-maroon", "medium-maroon"], /\.nut$/i, , !1, , /\.nut$/i, /^Squirrel$/i],
    ["key-icon", ["medium-yellow", "medium-yellow"], /\.pub$/i],
    ["key-icon", ["medium-orange", "medium-orange"], /\.pem$/i],
    ["key-icon", ["medium-blue", "medium-blue"], /\.key$|\.crt$/i],
    ["key-icon", ["medium-purple", "medium-purple"], /\.der$/i],
    ["key-icon", ["medium-red", "medium-red"], /^id_rsa/],
    ["key-icon", ["medium-green", "medium-green"], /\.glyphs\d*License$|^git-credential-osxkeychain$/i],
    ["key-icon", ["dark-green", "dark-green"], /^(?:master\.)?passwd$/i],
    ["stan-icon", ["medium-red", "medium-red"], /\.stan$/i, , !1, , /\.stan$/i, /^Stan$/i],
    ["stata-icon", ["medium-blue", "medium-blue"], /\.do$/i, , !1, /^stata$/, /\.stata$/i, /^stata$/i],
    ["stata-icon", ["dark-blue", "dark-blue"], /\.ado$/i],
    ["stata-icon", ["light-blue", "light-blue"], /\.doh$/i],
    ["stata-icon", ["medium-cyan", "medium-cyan"], /\.ihlp$/i],
    ["stata-icon", ["dark-cyan", "dark-cyan"], /\.mata$/i, , !1, /^mata$/, /\.mata$/i, /^Stata$|^mata$/i],
    ["stata-icon", ["light-cyan", "light-cyan"], /\.matah$/i],
    ["stata-icon", ["medium-purple", "medium-purple"], /\.sthlp$/i],
    ["storyist-icon", ["medium-blue", "medium-blue"], /\.story$/i],
    ["strings-icon", ["medium-red", "medium-red"], /\.strings$/i, , !1, , /\.strings$/i, /^Strings$/i],
    ["stylus-icon", ["medium-green", "medium-green"], /\.styl$/i, , !1, , /\.stylus$/i, /^Stylus$/i],
    ["sublime-icon", ["medium-orange", "medium-orange"], /\.(?:stTheme|sublime[-_](?:build|commands|completions|keymap|macro|menu|mousemap|project|settings|theme|workspace|metrics|session|snippet))$/i],
    ["sublime-icon", ["dark-orange", "dark-orange"], /\.sublime-syntax$/i],
    ["scd-icon", ["medium-red", "medium-red"], /\.scd$/i, , !1, /sclang|scsynth/, /\.supercollider$/i, /^SuperCollider$/i],
    ["svg-icon", ["dark-yellow", "dark-yellow"], /\.svg$/i, , !1, , /\.svg$/i, /^SVG$/i],
    ["swift-icon", ["medium-green", "medium-green"], /\.swift$/i, , !1, , /\.swift$/i, /^Swift$/i],
    ["sysverilog-icon", ["medium-blue", "dark-blue"], /\.sv$/i],
    ["sysverilog-icon", ["medium-green", "dark-green"], /\.svh$/i],
    ["sysverilog-icon", ["medium-cyan", "dark-cyan"], /\.vh$/i],
    ["tag-icon", ["medium-blue", "medium-blue"], /\.?c?tags$/i],
    ["tag-icon", ["medium-red", "medium-red"], /\.gemtags/i],
    ["tcl-icon", ["dark-orange", "dark-orange"], /\.tcl$/i, , !1, /tclsh|wish/, /\.tcl$/i, /^Tcl$/i],
    ["tcl-icon", ["medium-orange", "medium-orange"], /\.adp$/i],
    ["tcl-icon", ["medium-red", "medium-red"], /\.tm$/i],
    ["coffee-icon", ["medium-orange", "medium-orange"], /\.tea$/i, , !1, , /\.tea$/i, /^Tea$/i],
    ["tt-icon", ["medium-blue", "medium-blue"], /\.tt2?$/i],
    ["tt-icon", ["medium-purple", "medium-purple"], /\.tt3$/i],
    ["tern-icon", ["medium-blue", "medium-blue"], /\.tern-project$/i],
    ["terraform-icon", ["dark-purple", "dark-purple"], /\.tf(?:vars)?$/i, , !1, , /\.terra(?:form)?$/i, /^Terraform$/i],
    ["tex-icon", ["medium-blue", "dark-blue"], /\.tex$|\.ltx$|\.lbx$/i, , !1, , /(?:^|\.)latex(?:\.|$)/i, /^TeX$|^latex$/i],
    ["tex-icon", ["medium-green", "dark-green"], /\.aux$|\.ins$/i],
    ["tex-icon", ["medium-red", "dark-red"], /\.sty$|\.texi$/i, , !1, , /(?:^|\.)tex(?:\.|$)/i, /^TeX$/i],
    ["tex-icon", ["medium-maroon", "dark-maroon"], /\.dtx$/i],
    ["tex-icon", ["medium-orange", "dark-orange"], /\.cls$|\.mkiv$|\.mkvi$|\.mkii$/i],
    ["text-icon", ["medium-blue", "medium-blue"], /\.te?xt$|\.irclog$|\.uot$/i, , !1, , , , /^ï»¿|^ÿþ/],
    ["text-icon", ["medium-maroon", "medium-maroon"], /\.log$|^Terminal[-_\s]Saved[-_\s]Output$|\.brf$/i],
    ["text-icon", ["dark-red", "dark-red"], /\.git[\/\\]description$/, , !0],
    ["text-icon", ["medium-red", "medium-red"], /\.err$|\.no$|^(?:bug-report|fdl|for-release|tests)$/i],
    ["text-icon", ["dark-red", "dark-red"], /\.rtf$|\.uof$/i],
    ["text-icon", ["dark-blue", "dark-blue"], /\.i?nfo$/i],
    ["text-icon", ["dark-purple", "dark-purple"], /\.abt$|\.sub$/i],
    ["text-icon", ["dark-orange", "dark-orange"], /\.ans$/i],
    ["text-icon", ["medium-yellow", "medium-yellow"], /\.etx$/i],
    ["text-icon", ["medium-orange", "medium-orange"], /\.msg$/i],
    ["text-icon", ["medium-purple", "medium-purple"], /\.srt$|\.uop$/i],
    ["text-icon", ["medium-cyan", "medium-cyan"], /\.(?:utxt|utf8)$/i],
    ["text-icon", ["medium-green", "medium-green"], /\.weechatlog$|\.uos$/i],
    ["textile-icon", ["medium-orange", "medium-orange"], /\.textile$/i, , !1, , /\.textile$/i, /^Textile$/i],
    ["textmate-icon", ["dark-green", "dark-green"], /\.tmcg$/i],
    ["textmate-icon", ["dark-purple", "dark-purple"], /\.tmLanguage$/i],
    ["textmate-icon", ["medium-blue", "medium-blue"], /\.tmCommand$/i],
    ["textmate-icon", ["dark-blue", "dark-blue"], /\.tmPreferences$/i],
    ["textmate-icon", ["dark-orange", "dark-orange"], /\.tmSnippet$/i],
    ["textmate-icon", ["medium-pink", "medium-pink"], /\.tmTheme$/i],
    ["textmate-icon", ["medium-maroon", "medium-maroon"], /\.tmMacro$/i],
    ["textmate-icon", ["medium-orange", "medium-orange"], /\.yaml-tmlanguage$/i],
    ["textmate-icon", ["medium-purple", "medium-purple"], /\.JSON-tmLanguage$/i],
    ["thor-icon", ["medium-orange", "medium-orange"], /\.thor$/i],
    ["thor-icon", ["dark-orange", "dark-orange"], /^Thorfile$/i],
    ["tsx-icon", ["light-blue", "light-blue"], /\.tsx$/i, , !1, , /\.tsx$/i, /^TSX$/i],
    ["turing-icon", ["medium-red", "medium-red"], /\.tu$/i, , !1, , /\.turing$/i, /^Turing$/i],
    ["twig-icon", ["medium-green", "medium-green"], /\.twig$/i, , !1, , /\.twig$/i, /^Twig$/i],
    ["txl-icon", ["medium-orange", "medium-orange"], /\.txl$/i, , !1, , /\.txl$/i, /^TXL$/i],
    ["ts-icon", ["medium-blue", "medium-blue"], /\.ts$/i, , !1, , /\.ts$/i, /^(?:ts|Type[-\s]*Script)$/i],
    ["unity3d-icon", ["dark-blue", "dark-blue"], /\.anim$/i, , !1, /^shaderlab$/, /\.shaderlab$/i, /^Unity3D$|^shaderlab$/i],
    ["unity3d-icon", ["dark-green", "dark-green"], /\.asset$/i],
    ["unity3d-icon", ["medium-red", "medium-red"], /\.mat$/i],
    ["unity3d-icon", ["dark-red", "dark-red"], /\.meta$/i],
    ["unity3d-icon", ["dark-cyan", "dark-cyan"], /\.prefab$/i],
    ["unity3d-icon", ["medium-blue", "medium-blue"], /\.unity$/i],
    ["unity3d-icon", ["medium-maroon", "medium-maroon"], /\.unityproj$/i],
    ["uno-icon", ["dark-blue", "dark-blue"], /\.uno$/i],
    ["unreal-icon", [null, null], /\.uc$/i, , !1, , /\.uc$/i, /^UnrealScript$/i],
    ["link-icon", ["dark-blue", "dark-blue"], /\.url$/i],
    ["urweb-icon", ["medium-maroon", "medium-maroon"], /\.ur$/i, , !1, , /\.ur$/i, /^UrWeb$|^Ur(?:\/Web)?$/i],
    ["urweb-icon", ["dark-blue", "dark-blue"], /\.urs$/i],
    ["vagrant-icon", ["medium-cyan", "medium-cyan"], /^Vagrantfile$/i],
    ["gnome-icon", ["medium-purple", "medium-purple"], /\.vala$/i, , !1, /^vala$/, /\.vala$/i, /^vala$/i],
    ["gnome-icon", ["dark-purple", "dark-purple"], /\.vapi$/i],
    ["varnish-icon", ["dark-blue", "dark-blue"], /\.vcl$/i, , !1, , /(?:^|\.)(?:varnish|vcl)(?:\.|$)/i, /^VCL$/i],
    ["verilog-icon", ["dark-green", "dark-green"], /\.v$/i, , !1, /^verilog$/, /\.verilog$/i, /^veril[0o]g$/i],
    ["verilog-icon", ["medium-red", "medium-red"], /\.veo$/i],
    ["vhdl-icon", ["dark-green", "dark-green"], /\.vhdl$/i, , !1, /^vhdl$/, /\.vhdl$/i, /^vhdl$/i],
    ["vhdl-icon", ["medium-green", "medium-green"], /\.vhd$/i],
    ["vhdl-icon", ["dark-blue", "dark-blue"], /\.vhf$/i],
    ["vhdl-icon", ["medium-blue", "medium-blue"], /\.vhi$/i],
    ["vhdl-icon", ["dark-purple", "dark-purple"], /\.vho$/i],
    ["vhdl-icon", ["medium-purple", "medium-purple"], /\.vhs$/i],
    ["vhdl-icon", ["dark-red", "dark-red"], /\.vht$/i],
    ["vhdl-icon", ["dark-orange", "dark-orange"], /\.vhw$/i],
    ["video-icon", ["medium-blue", "medium-blue"], /\.3gpp?$/i, , !1, , , , /^.{4}ftyp3g/],
    ["video-icon", ["dark-blue", "dark-blue"], /\.(?:mp4|m4v|h264)$/i, , !1, , , , /^.{4}ftyp/],
    ["video-icon", ["medium-blue", "medium-blue"], /\.avi$/i, , !1, , , , /^MLVI/],
    ["video-icon", ["medium-cyan", "medium-cyan"], /\.mov$/i, , !1, , , , /^.{4}moov/],
    ["video-icon", ["medium-purple", "medium-purple"], /\.mkv$/i, , !1, , , , /^Eß£Bmatroska/],
    ["video-icon", ["medium-red", "medium-red"], /\.flv$/i, , !1, , , , /^FLV/],
    ["video-icon", ["dark-blue", "dark-blue"], /\.webm$/i, , !1, , , , /^Eß£/],
    ["video-icon", ["medium-red", "medium-red"], /\.mpe?g$/i, , !1, , , , /^\0{2}[³º]/],
    ["video-icon", ["dark-purple", "dark-purple"], /\.(?:asf|wmv)$/i, , !1, , , , /^0&²ufÏ¦Ù\0ª\0bÎl/],
    ["video-icon", ["medium-orange", "medium-orange"], /\.(?:ogm|og[gv])$/i, , !1, , , , /^OggS/],
    ["vim-icon", ["medium-green", "medium-green"], /\.(?:vim|n?vimrc)$/i, , !1, /Vim?/i, /\.viml$/i, /^(?:VimL?|NVim|Vim\s*Script)$/i],
    ["vim-icon", ["dark-green", "dark-green"], /^[gn_]?vim(?:rc|info)$/i],
    ["vs-icon", ["medium-blue", "medium-blue"], /\.(?:vba?|fr[mx]|bas)$/i, , !1, , /\.vbnet$/i, /^Visual Studio$|^vb\.?net$/i],
    ["vs-icon", ["medium-red", "medium-red"], /\.vbhtml$/i],
    ["vs-icon", ["medium-green", "medium-green"], /\.vbs$/i],
    ["vs-icon", ["dark-blue", "dark-blue"], /\.csproj$/i],
    ["vs-icon", ["dark-red", "dark-red"], /\.vbproj$/i],
    ["vs-icon", ["dark-purple", "dark-purple"], /\.vcx?proj$/i],
    ["vs-icon", ["dark-green", "dark-green"], /\.vssettings$/i],
    ["vs-icon", ["medium-maroon", "medium-maroon"], /\.builds$/i],
    ["vs-icon", ["medium-orange", "medium-orange"], /\.sln$/i],
    ["vue-icon", ["light-green", "light-green"], /\.vue$/i, , !1, , /\.vue$/i, /^Vue$/i],
    ["owl-icon", ["dark-blue", "dark-blue"], /\.owl$/i],
    ["windows-icon", ["medium-purple", "medium-purple"], /\.bat$|\.cmd$/i, , !1, , /(?:^|\.)(?:bat|dosbatch)(?:\.|$)/i, /^(?:bat|(?:DOS|Win)?Batch)$/i],
    ["windows-icon", [null, null], /\.(?:exe|com|msi)$/i],
    ["windows-icon", ["medium-blue", "medium-blue"], /\.reg$/i],
    ["x10-icon", ["light-maroon", "light-maroon"], /\.x10$/i, , !1, , /\.x10$/i, /^X10$|^xten$/i],
    ["x11-icon", ["medium-orange", "medium-orange"], /\.X(?:authority|clients|initrc|profile|resources|session-errors|screensaver)$/i],
    ["xmos-icon", ["medium-orange", "medium-orange"], /\.xc$/i],
    ["appstore-icon", ["medium-blue", "medium-blue"], /\.(?:pbxproj|pbxuser|mode\dv\3|xcplugindata|xcrequiredplugins)$/i],
    ["xojo-icon", ["medium-green", "medium-green"], /\.xojo_code$/i],
    ["xojo-icon", ["medium-blue", "medium-blue"], /\.xojo_menu$/i],
    ["xojo-icon", ["medium-red", "medium-red"], /\.xojo_report$/i],
    ["xojo-icon", ["dark-green", "dark-green"], /\.xojo_script$/i],
    ["xojo-icon", ["dark-purple", "dark-purple"], /\.xojo_toolbar$/i],
    ["xojo-icon", ["dark-cyan", "dark-cyan"], /\.xojo_window$/i],
    ["xpages-icon", ["medium-blue", "medium-blue"], /\.xsp-config$/i],
    ["xpages-icon", ["dark-blue", "dark-blue"], /\.xsp\.metadata$/i],
    ["xmos-icon", ["dark-blue", "dark-blue"], /\.xpl$/i],
    ["xmos-icon", ["medium-purple", "medium-purple"], /\.xproc$/i],
    ["sql-icon", ["dark-red", "dark-red"], /\.(?:xquery|xq|xql|xqm|xqy)$/i, , !1, , /\.xq$/i, /^XQuery$/i],
    ["xtend-icon", ["dark-purple", "dark-purple"], /\.xtend$/i, , !1, , /\.xtend$/i, /^Xtend$/i],
    ["yang-icon", ["medium-yellow", "medium-yellow"], /\.yang$/i, , !1, , /\.yang$/i, /^YANG$/i],
    ["zbrush-icon", ["dark-purple", "dark-purple"], /\.zpr$/i],
    ["zephir-icon", ["medium-pink", "medium-pink"], /\.zep$/i],
    ["zimpl-icon", ["medium-orange", "medium-orange"], /\.(?:zimpl|zmpl|zpl)$/i],
    ["apple-icon", ["medium-blue", "medium-blue"], /^com\.apple\./, .5],
    ["apache-icon", ["medium-red", "medium-red"], /^httpd\.conf/i, 0],
    ["checklist-icon", ["medium-yellow", "medium-yellow"], /TODO/, 0],
    ["config-icon", [null, null], /config|settings|option|pref/i, 0],
    ["doge-icon", ["medium-yellow", "medium-yellow"], /\.djs$/i, 0, !1, , /\.dogescript$/i, /^Dogescript$/i],
    ["gear-icon", [null, null], /^\./, 0],
    ["book-icon", ["medium-blue", "medium-blue"], /\b(?:changelog|copying(?:v?\d)?|install|read[-_]?me)\b|^licen[sc]es?[-._]/i, 0],
    ["book-icon", ["dark-blue", "dark-blue"], /^news(?:[-_.]?[-\d]+)?$/i, 0],
    ["v8-icon", ["medium-blue", "medium-blue"], /^(?:[dv]8|v8[-_.][^.]*|mksnapshot|mkpeephole)$/i, 0],
    ["code-icon", ["medium-red"], /\.wxml$/i],
    ["css3-icon", ["light-blue"], /\.wxss$/i],
    ["arttext-icon", ["dark-purple", "dark-purple"], /\.artx$/i],
    ["atom-icon", ["dark-green", "dark-green"], /^\.atom$/],
    ["bower-icon", ["medium-yellow", "medium-orange"], /^bower[-_]components$/],
    ["dropbox-icon", ["medium-blue", "medium-blue"], /^(?:Dropbox|\.dropbox\.cache)$/],
    ["emacs-icon", ["medium-purple", "medium-purple"], /^\.emacs\.d$/],
    ["dylib-icon", [null, null], /\.framework$/i],
    ["git-icon", ["medium-red", "medium-red"], /\.git$/],
    ["github-icon", [null, null], /^\.github$/],
    ["meteor-icon", ["dark-orange", "dark-orange"], /^\.meteor$/],
    ["node-icon", ["medium-green", "medium-green"], /^node_modules$/],
    ["package-icon", [null, null], /^\.bundle$/i],
    ["svn-icon", [null, null], /^\.svn$/i],
    ["textmate-icon", [null, null], /\.tmBundle$/i],
    ["vagrant-icon", ["medium-cyan", "medium-cyan"], /\.vagrant$/i],
    ["appstore-icon", [null, null], /\.xcodeproj$/i]
]

