export const actionNameZH={
  "1":"创建了项目",
  "2":"重命名项目 {oldRepoName} 为",
  "5":"推送了 {branch} 分支的代码到",
  "6":"创建了任务",
  "7":"创建了合并请求",
  "9":"推送了标签 {branch} 到",
  "10":"评论了任务",
  "11":"合并了合并请求",
  "12":"关闭了任务",
  "13":"重新开启了任务",
  "14":"关闭了合并请求",
  "15":"重新开启了合并请求",
  "17":"从 {repoName} 删除分支 {deleteBranchName}",
  "22":"建议变更",
  "23":"评论了合并请求",
  "24":"上传了数据集文件",
  "25":"创建了CPU/GPU类型调试任务",
  "26":"创建了NPU类型调试任务",
  "27":"创建了NPU类型训练任务",
  "28":"创建了推理任务",
  "50":"创建了GPU类型推理任务",
  "51":"创建了ILUVATAR-GPGPU类型推理任务",
  "29":"创建了评测任务",
  "30":"导入了新模型",
  "31":"创建了CPU/GPU类型训练任务",
  "32":"创建了NPU类型训练任务",
  "33":"创建了CPU/GPU类型训练任务",
  "35":"创建的数据集 {dataset} 被设置为推荐数据集",
  "36":"提交了镜像 {image}",
  "37":"提交的镜像 {image} 被设置为推荐镜像",
  "39":"创建了NPU类型调试任务",
  "40":"创建了CPU/GPU类型调试任务",
  "41":"创建了GCU类型调试任务",
  "42":"创建了GCU类型训练任务",
  "43":"创建了MLU类型调试任务",
  "44":"创建了MLU类型训练任务",
  "45":"创建了GPU类型在线推理任务",
  "46":"创建了DCU类型调试任务",
  "47":"创建了CPU类型超算任务",
  "48":"创建了ILUVATAR-GPGPU类型调试任务",
  "49":"创建了METAX-GPGPU类型调试任务",
  "53":"创建了ILUVATAR-GPGPU类型训练任务",
  "54":"创建了GPU类型通用任务",
  "55":"创建了在线体验任务",
  "56":"创建了NLP微调任务",
  "57":"创建了DCU类型训练任务",
  "58":"创建了NLP微调任务",
  "59":"创建了在线体验任务",
  "60":"创建了CV微调任务",
  "61":"创建了Comfy UI任务",
  "62":"创建了数据集 {dataset}",
  "63":"删除了数据集 {dataset}",
  "65":"创建了METAX-GPGPU类型训练任务",
  "66":"创建模型评测任务",
  "67":"创建了模型 {aimodel}",
  "68":"删除了模型 {aimodel}",
  "70":"创建的模型 {aimodel} 被设置为推荐模型",
  "71":"创建了BIREN-GPU类型调试任务",
  "72":"创建了BIREN-GPU类型训练任务",
};

export const actionNameEN={
  "1":" created repository",
  "2":" renamed repository from {oldRepoName} to ",
  "5":" pushed to {branch} at",
  "6":" opened issue",
  "7":" created pull request",
  "9":" pushed tag {branch} to ",
  "10":" commented on issue",
  "11":" merged pull request",
  "12":" closed issue",
  "13":" reopened issue",
  "14":" closed pull request",
  "15":" reopened pull request",
  "17":" deleted branch {deleteBranchName} from {repoName}",
  "22":" proposed changes",
  "23":" commented on pull request",
  "24":" upload dataset ",
  "25":" created CPU/GPU type debugging task ",
  "26":" created NPU type debugging task ",
  "27":" created NPU type training task",
  "28":" created inference task",
  "50":" created GPU type inference task",
  "51":" created ILUVATAR-GPGPU type inference task",
  "29":" created profiling task",
  "30":" created new model",
  "31":" created CPU/GPU type training task",
  "32":" created NPU type training task",
  "33":" created CPU/GPU type training task",
  "35":" created dataset {dataset} was set as recommended dataset",
  "36":" committed image {image}",
  "37":" committed image {image} was set as recommended image",
  "39":" created NPU type debugging task ",
  "40":" created CPU/GPU type debugging task ",
  "41":" created GCU type debugging task ",
  "42":" created GCU type training task ",
  "43":" created MLU type debugging task ",
  "44":" created MLU type training task ",
  "45":" created GPU type online inference task ",
  "46":" created DCU type debugging task ",
  "47":" created CPU type super compute task ",
  "48":" created ILUVATAR-GPGPU type debugging task ",
  "49":" created METAX-GPGPU type debugging task ",
  "53":" created ILUVATAR-GPGPU type training task ",
  "54":" created GPU type general task ",
  "55":" created model experience task",
  "56":" created NLP finetune task",
  "57":" created DCU type training task ",
  "58":" created NLP finetune task",
  "59": "created model experience task",
  "60": "created CV finetune task",
  "61": "created Comfy UI task",
  "62": "created {dataset} dataset",
  "63": "deleted {dataset} dataset",
  "65": "created METAX-GPGPU type training task ",
  "66": "created model evaluate task",
  "67": "created {aimodel} model",
  "68": "deleted {aimodel} model",
  "70": "created model {aimodel} was set as recommended model",
  "71":" created BIREN-GPU type debugging task ",
  "72":" created BIREN-GPU type training task ",
};


export const OP_TYPES = {
  // 仓库操作
  REPO_CREATE: '1',
  REPO_RENAME: '2',
  REPO_PUSH_BRANCH: '5',
  REPO_PUSH_TAG: '9',
  REPO_DELETE_BRANCH: '17',
  
  // Issue操作
  ISSUE_OPEN: '6',
  ISSUE_COMMENT: '10',
  ISSUE_CLOSE: '12',
  ISSUE_REOPEN: '13',
  
  // PR操作
  PR_CREATE: '7',
  PR_MERGE: '11',
  PR_CLOSE: '14',
  PR_REOPEN: '15',
  PR_PROPOSE_CHANGES: '22',
  PR_COMMENT: '23',
  
  // 数据集操作
  DATASET_CREATE: '62',
  DATASET_DELETE: '63',
  DATASET_RECOMMEND: '35',
  
  // 模型操作
  MODEL_CREATE: '67',
  MODEL_DELETE: '68',
  MODEL_RECOMMEND: '70',
  
  // 镜像操作
  IMAGE_COMMIT: '36',
  IMAGE_RECOMMEND: '37',
  
  // 任务操作
  TASK_DEBUG_NPU: '26',
  TASK_TRAIN_NPU: '27',
  TASK_INFERENCE: '28',
  TASK_PROFILING: '29',
  TASK_TRAIN_CPU_GPU: '31',
  TASK_TRAIN_NPU_2: '32',
  TASK_DEBUG_NPU_2: '39',
  TASK_DEBUG_CPU_GPU: '40',
  TASK_DEBUG_GCU: '41',
  TASK_TRAIN_GCU: '42',
  TASK_DEBUG_MLU: '43',
  TASK_TRAIN_MLU: '44',
  TASK_ONLINE_INFERENCE: '45',
  TASK_DEBUG_DCU: '46',
  TASK_SUPER_COMPUTE: '47',
  TASK_DEBUG_ILUVATAR: '48',
  TASK_DEBUG_METAX: '49',
  TASK_INFERENCE_GPU: '50',
  TASK_INFERENCE_ILUVATAR: '51',
  TASK_TRAIN_ILUVATAR: '53',
  TASK_GENERAL_GPU: '54',
  TASK_EXPERIENCE: '55',
  TASK_NLP_FINETUNE: '56',
  TASK_TRAIN_DCU: '57',
  TASK_NLP_FINETUNE_2: '58',
  TASK_EXPERIENCE_2: '59',
  TASK_CV_FINETUNE: '60',
  TASK_COMFY_UI: '61',
  TASK_TRAIN_METAX: '65',
  TASK_MODEL_EVALUATE: '66',
  TASK_DEBUG_BIREN: '71',
  TASK_TRAIN_BIREN: '72'
}
// 任务类型列表
export const TASK_OP_TYPES = [
  '25', '26', '27', '28', '29', '30', '31', '32', '33', '39',
  '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
  '50', '51', '53', '54', '55', '56', '57', '58', '59', '60',
  '61', '65', '66', '71', '72'
]