const en = {
  loading: 'Loading...',
  noData: 'No Data',
  noMessage: "No Message",
  noDataset: 'Empty, with nothing at all.',
  date: 'Date',

  confirm: 'Confirm',
  cancel: 'Cancel',
  confirm1: 'Confirm',
  confirmOp: "Confirm Operate",
  cancelOp: "Cancel Operate",
  enterReason: "Please enter the reason",
  clear: "Clear",
  none: "None",
  pleaseCompleteTheInformationFirst: 'Please Complete the Information first!',
  submittedSuccessfully: 'Submitted Successfully!',
  submittedFailed: 'Submitted Failed!',
  operation: 'Operation',
  edit: 'Edit',
  delete: 'Delete',
  tips: 'Tips',
  expandMore: 'Expand More',
  goBack: 'Go back',
  star: 'Star',
  unStar: 'UnStar',
  submit: 'Submit',
  selectAll: 'Select All',
  selectNone: 'Select None',
  copy: 'Copy',
  copySuccess: 'Copied successfully',
  copyLink: 'Copy Link',
  copyedLink: 'Link has been copied',
  downloadAddress: 'Download address',
  operationFailed: 'Operation failed',
  cancelOperate: 'You have canceled the operation',

  accomplishTask: 'Accomplish Task',
  adminOperate: 'Administrator Operation',
  runCloudBrainTask: 'Run Computing Task',
  operating: 'Operating',
  succeeded: 'Succeeded',
  debugTask: 'Debug Task',
  trainTask: 'Train Task',
  trainDuration: "Train task duration",
  inferenceTask: 'Inference Task',
  benchmarkTask: 'Benchmark Task',
  onlineinfer: "Online Inference",
  onlineinferTask: "Online Inference Task",
  consoleHome: "Console Home",
  superComputeTask: "HPC Task",
  generalTask: "General Task",
  createPublicProject: 'Create Public Projects',
  dailyPutforwardTasks: 'Daily Put Forward Tasks',
  dailyPR: 'Daily PR',
  comment: 'Comment',
  uploadDatasetFile: 'Upload Dataset Files',
  importNewModel: 'Import New Models',
  completeWechatCodeScanningVerification: 'Complete Wechat Code Scanning Verification',
  dailyRunCloudbrainTasks: 'Daily Run Computing Tasks',
  datasetRecommendedByThePlatform: 'Dataset Recommended by the Platform',
  aimodelRecommendedByThePlatform: "Model Recommended by the Platform",
  dailyCreateDataset: "Create Datasets",
  dailyCreateDataset1: "created dataset",
  dailyCreateAimodel: "Create Models",
  dailyCreateAimodel1: "created model",
  submitNewPublicImage: 'Submit New Public Images',
  imageRecommendedByThePlatform: 'Image Recommended by the Platform',
  firstChangeofAvatar: 'First Change of Avatar',
  dailyCommit: 'Daily Commit',
  calcPointDetails: 'Calculation Points Details',
  calcPointAcquisitionInstructions: 'Calculation Points Acquisition Instructions',
  CurrAvailableCalcPoints: 'Currently Available Calculation Points',
  totalGainCalcPoints: 'Total Gain of Calculation Points',
  totalConsumeCalcPoints: 'Total Consume of Calculation Points',
  gainDetail: 'Gain Detail',
  consumeDetail: 'Consume Detail',
  serialNumber: 'Serial Number',
  time: 'Time',
  scene: 'Scene',
  behaviorOfPoint: 'Behavior Of Point',
  explanation: 'Explanation',
  points: 'Points',
  status: 'Status',
  runTime: 'Run Time',
  taskName: 'Task Name',

  createdRepository: 'created repository ',
  repositoryWasDel: 'repository was deleted',
  userWasDel: 'user was deleted',
  userAccountWasDel: "user account was deleted",
  openedIssue: 'opened issue ',
  createdPullRequest: 'created pull request ',
  commentedOnIssue: 'commented on issue ',
  uploadDataset: 'upload dataset ',
  createdNewModel: 'created new model ',
  invitedFriend: 'invited friend ',
  firstBindingWechatRewards: 'first binding wechat rewards',
  created: 'created ',
  type: ' type ',
  dataset: 'Datasets ',
  setAsRecommendedDataset: ' was set as recommended dataset',
  setAsRecommendedAimodel: ' was set as recommended model',
  committedImage: 'committed image ',
  image: 'image ',
  setAsRecommendedImage: ' was set as recommended image',
  updatedAvatar: 'updated avatar',
  pushedBranch: 'pushed to {branch} at ',
  deleteBranch: 'deleted branch {branch} from {repo}',
  pushedTag: ' pushed tag {tag} to ',
  deleteTag: ' deleted tag {tag} from {repo}',
  dailyMaxTips: `can't get full points when reach the daily upper limit`,
  memory: 'Memory',
  sharedMemory: 'Shared Memory',
  ';': ', ',

  noPointGainRecord: 'No Point Earn Record Yet',
  noPointConsumeRecord: 'No Point Consume Record Yet',
  consumeDescr: 'Explanation: Starting from late October 2024, the billing cycle for Computing tasks will be adjusted. For specific billing rules, please refer to the "Billing Rules" section on the "<a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/quickstart/resources?id=%e8%ae%a1%e8%b4%b9%e8%a7%84%e5%88%99">Platform Computing Resources and Points Explanation</a>" page in the online help.',

  emptyPage: 'Request forbidden by administrative rules',
  emptyPageDescr: 'The page you are trying to reach either <strong>does not exist</strong> or <strong>you are not authorized</strong> to view it.',
  handleTask: 'Processing tasks',
  freeCompute: 'Inclusive computing power',
  repoPathTips: 'The path only allows letters, numbers, and - _, Up to 100 characters.',
  useInPcWeb: 'For a better user experience, please open this page on your PC.',
  acknowledgementsTips: {
    main1: 'If the OpenI Community has provided assistance to your research work, please acknowledge it in your paper (',
    main2: ').',
    moreContent: 'more content',
    p1: `English version: Thanks for the support provided by OpenI Community (<a href="https://openi.pcl.ac.cn" target="_blank">https://openi.pcl.ac.cn</a>).`,
    p2: `Chinese version: 感谢启智社区提供的技术支持(<a href="https://openi.pcl.ac.cn" target="_blank">https://openi.pcl.ac.cn</a>)。`,
    p3: `If your work references this platform, you are also welcome to submit your work information in the following open source projects:`,
    p4: `<a href="https://openi.pcl.ac.cn/OpenIOSSG/references" target="_blank">https://openi.pcl.ac.cn/OpenIOSSG/references</a>`,
  },
  computeResourceTitle: {
    CPU: 'CPU',
    VCPU: 'VCPU',
    'CPU/GPU': 'NVIDIA GPU',
    GPU: 'NVIDIA GPU',
    NPU: 'Ascend NPU',
    GCU: 'Enflame GCU',
    MLU: 'Cambricon MLU',
    DCU: 'HYGON DCU',
    'ILUVATAR-GPGPU': 'Iluvatar CoreX GPGPU',
    'METAX-GPGPU': 'MetaX GPGPU',
    'BIREN-GPU': 'BIREN GPU',
  },
  TaskTypeTitle: {
    Notebook: 'Notebook/Online Inference',
    Notebook1: 'Notebook',
    TrainJob: 'Train Job',
    Ecs: 'Ecs',
    Inference: 'Inference',
    Service: 'Service',
  },
  resourcesManagement: {
    OpenI: 'OpenI',
    C2Net: 'C2Net',
    IFLYTEKTraining: "IFLYTEKTraining",
    OpenIOne: 'OpenI One',
    OpenITwo: 'OpenI Two',
    OpenIChengdu: 'OpenI ChengDu AI Chenter',
    chengduCenter: 'ChengDu AI Center',
    pclcci: 'PCL Cloud Computer Institute',
    hefeiCenter: 'HeFei AI Center',
    xuchangCenter: 'XuChang AI Center',
    huoshi: "HuoShi AI Center",
    willOnShelf: 'To Be On Shelf',
    onShelf: 'On Shelf',
    offShelf: 'Off Shelf',
    toOnShelf: 'To On Shelf',
    toOffShelf: 'To Off Shelf',
    toSetPriceAndOnShelf: 'To Set Price and On Shelf',
    status: 'Status',
    reason: "Reason",
    allStatus: 'All Status',
    syncAiNetwork: 'Sync AI Network',
    resQueue: 'Resources Queue',
    allResQueue: 'All Resources Queues',
    addResQueue: 'Add Resources Queue',
    addResQueueBtn: 'Add Resources Queue',
    editResQueue: 'Edit Resources Queue',
    resQueueCode: 'Resources Queue Code',
    resQueueName: 'Resources Queue Name',
    resQueueType: "Resources Queue Type",
    resQueueIsAvailable: "Resources Queue Is Available",
    resQueueIsAvailableAll: "Resources Queue Is Available(All)",
    allResQueueType: "All Resources Queue Type",
    whichCluster: 'Cluster',
    allCluster: 'All Clusters',
    aiCenter: 'AI Center',
    aiCenterID: 'AI Center ID',
    allAiCenter: 'All AI Centers',
    computeResource: 'Compute Resource',
    allComputeResource: 'All Compute Resources',
    accCardType: 'Acc Card Type',
    allAccCardType: 'All Acc Card Type',
    allNetworkType: 'All Network Type',
    cardsTotalNum: 'Cards Total Number',
    accCardsNum: 'Acc Cards Number',
    allCardsNum: 'All Cards Number',
    remark: 'Remark',
    pleaseEnterRemark: 'Please Enter Remark(The maximum length shall not exceed 255)',
    pleaseEnterPositiveIntegerCardsTotalNum: 'Please Enter Positive Integer Cards Total Number!',
    addResSpecificationAndPriceInfo: 'Add Resources Specification and Price Info',
    addResSpecificationBtn: 'Add Resources Specification',
    editResSpecificationAndPriceInfo: 'Edit Resources Specification and Price Info',
    resSpecificationAndPriceManagement: 'Resources Specification Management',
    sourceSpecCode: 'Source Specification Code',
    sourceSpecCodeTips: 'OpenI Two Should Enter the Source Specification Code',
    sourceSpecId: 'Source Specification ID',
    cpuNum: 'CPU Number',
    gpuMem: 'GPU Memory',
    mem: 'Memory',
    shareMem: 'Share Memory',
    unitPrice: 'Unit Price',
    point_hr: 'Point/hr',
    ShelfReason: 'Reason for Shelf',
    node: 'node',
    free: 'Free',
    onShelfConfirm: 'Are you sure to on shelf the resources specification?',
    offShelfConfirm: 'Are you sure to off shelf the resources specification?',
    onShelfCode1001: 'On shelf failed, the resources queues not available.',
    onShelfCode1003: 'On shelf failed, the resources specification not available.',
    offShelfDlgTip1: 'The current resource specification has been used in the following roles:',
    offShelfDlgTip2: 'Please confirm to off shelf?',
    characterLengthPrompt: "Please enter no more than 255 characters",
    resSceneManagement: 'Resources Scene Management',
    addResScene: 'Add Resources Scene',
    addResSceneBtn: 'Add Resources Scene',
    editResScene: 'Edit Resources Scene',
    resSceneName: 'Resources Scene Name',
    jobType: 'Job Type',
    allJobType: 'All Job Types',
    allJobStatus: 'All Job Status',
    sceneType: "Community Scene Type",
    allSceneType: "All Community Scene Type",
    isExclusiveSpec: 'Is Exclusive Spec?',
    allExclusiveAndCommonUseSpec: 'All Exclusive and Common Use Spec',
    public: "Public",
    exclusive: "Exclusive",
    exclusiveTxt: "Exclusive",
    exclusiveSpec: 'Exclusive Spec',
    commonUseSpec: 'Common Use Spec',
    exclusiveOrg: 'Exclusive Organization',
    exclusiveOrgTips: 'Multiple organization names are separated by semicolons',
    computeCluster: 'Compute Cluster',
    resourceSpecification: 'Resource Specification',
    lastUpdateTime: 'Last Update Time',
    resSceneDeleteConfirm: 'Are you sure to delete the current Resource Scene?',
    resourceSpecificationIsAvailable: 'Specification Is Available',
    resourceSpecificationIsAvailableAll: 'Specification Is Available(All)',
    available: 'Available',
    notAvailable: 'Not Available',
    selectSpec: 'Select resource specification',
    accordingSpec: 'According to resource specification',
    accordingQueue: 'According to resources queue',
    accordingSelect: 'According to the selected option',
    allIsEnableVisualization: 'Is Enable Visualization(All)',
    notEnable: 'Not Enable',
    enable: 'Enable',
    roleNameTips: 'Maximum input of 80 characters',
    roleDescTips: 'Maximum input of 800 characters',
  },
  logManagement: {
    operationLog: "Operation Log",
    allOperationType: "All Operation Types",
    resourceSpecificationOnshelf: 'Resource Specification Onshelf',
    resourceSpecificationEdit: 'Resource Specification Edit',
    resourceSpecificationOffshelf: 'Resource Specification Offshelf',
    resourceSpecificationAddition: 'Resource Specification Addition',
    resourceSpecificationAutoUpdate: 'Resource Specification Auto Update',
    operationType: 'Operation Type',
    operationReason: 'Operation Reason',
    operator: 'Operator',
    operationTime: 'Operation Time',
  },
  user: {
    inviteFriends: 'Invite Friends',
    inviteFriendsTips: 'Copy QR code or invite registration link to share with friends',
    clickToViewTheEventDetails: 'Click to view the event details',
    copyRegistrationInvitationLink: 'Copy registration invitation link',
    registrationAdress: 'Registration Adress: ',
    recommender: 'Recommender: ',
    invitedFriends: 'Invited friends',
    registrationTime: 'Registration time',
    theSharedContentHasBeenCopiedToTheClipboard: 'The shared content has been copied to the clipboard',
    copyError: 'Copy error',
    Activated: 'Activated',
    notActive: 'Not active',
    normal: 'Normal',
  },
  tranformImageFailed: 'Picture desensitization failed',
  originPicture: 'Origin picture',
  desensitizationPicture: 'Desensitization picture',
  desensitizationObject: 'Desensitization object',
  example: 'Example',
  startDesensitization: 'Start desensitization',
  all: 'All',
  others: 'Others',
  onlyFace: 'Only face',
  onlyLicensePlate: 'Only license plate',
  dragThePictureHere: 'Drag the picture here',
  or: ' or ',
  clickUpload: 'Click upload',
  dataDesensitizationModelExperience: 'Data desensitization model experience',
  dataDesensitizationModelDesc: 'Use AI technology to desensitize the face and license plate number in the picture. For more information about this model, please visit the project',
  limitFilesUpload: 'Only jpg/jpeg/png files can be uploaded',
  limitSizeUpload: 'The size of the uploaded file cannot exceed 20M!',
  bootPlaceholder: 'Please enter the startup file',
  notebook: {
    createNewNotebook: "Create new notebook debug task",
    sameTaskTips1: "You have created an",
    sameTaskTips2: "equivalent task",
    sameTaskTips3: "that is waiting or running, please wait for the task to finish before creating it.",
    sameTaskTips4: "You can view all your Cloudbrain tasks in",
    sameTaskTips5: "My Workspace",
    sameTaskTips6: "Computing Task",
    sameTaskTips7: "",
    cpuEnv: "CPU Environment",
    gpuEnv: "GPU Environment",
    npuEnv: "NPU environment",
    newTask: "Create new task",
    noQuene: "The current resources are sufficient and no tasks are queued",
    queneTips1: "Your current queue position is",
    queneTips2: "",
    watiResource: "Waiting for resources to be allocated, please be patient",
    debug: "Debug",
    stop: "Stop",
    stopping: "Stopping",
    notebookRunning: "The debugging environment has been started, and it will automatically close after 4 hours ",
    stopSuccess: "Stop task succeeded",
    specification: "Specification",
    graphicMemory: "Graphic Memory",
    memory: "Memory",
    sharedMemory: "Shared Memory",
    tips: 'The newly created debugging task will be placed in the project openi-notebook under your name. If there is no such project, the system will automatically create a new one.',
    balanceOfPoints: 'Balance of Points:',
    points: 'points',
    hours: 'Hours',
    expected_time: ', expected to be available for',
    limitTitle: 'The number of {type} has reached the limit.',
    limitReason: 'The current account can create up to {count} and simultaneously run {runCount} debugging tasks. Please stop running tasks and delete some historical tasks before submitting a new one.',
    stopReason: 'The current account already has {count} tasks waiting or running. Please stop them before submitting a new task.',
    deleteReason: 'The current account can create up to {count} {type}. Please delete historical tasks before submitting a new one.',
    stopSuccess: 'Stop task succeeded',
    stopFailed: 'Stop task failed',
    deleteSuccess: 'Delete task succeeded',
    deleteFailed: 'Delete task failed',
    handleSuccess: 'Operation succeeded. Please continue creating the task.',
  },
  modelManage: {
    modelManage: 'Model management',
    modelName: 'Model name',
    useCluster: 'Available clusters',
    license: 'License',
    selectLicense: 'Select license',
    local: 'Local',
    online: 'Online',
    external: 'External',
    createModel: 'Create model',
    importLocalModel: 'Import Local Model',
    importOnlineModel: 'Import Online Model',
    importFrom: 'Where to import from',
    createNewModel: 'Create a new model',
    localModelTips: 'Import locally stored model files to the OpenI collaboration platform',
    onlineModelTips1: 'Import the model output from the training task into model management. To import an online model, you need to first',
    onlineModelTips2: 'create a training task',
    nextSteps: 'Next step',
    back: 'Back',
    step1: 'Select import type and project',
    step2: 'Set model information',
    step3: 'Upload model file',
    project: 'Belonging to repository',
    newRepoPath: 'New repository path',

    modelInfo: 'Model information',
    modelBriefIntro: 'Model brief introduction',
    trainingInfo: 'Training information',
    modifyModelInfo: 'Modify model information',
    modelList: 'Model list',
    modelFiles: 'Model files',
    addModelFiles: 'Add model files',
    uploadModelFiles: 'Upload model files',
    pleaseInputModelName: 'Please input model name',
    version: 'Version',
    modelVersion: 'Model version',
    modelEngine: 'Model engine',
    modelSource: 'Model source',
    modelLabel: 'Model label',
    externalToken: 'External Token',
    modelLabelInputTips: 'Input labels, multiple labels are separated by spaces',
    modelLabelGatedTips: "To migrate Gated's model files, it is necessary to input HuggingFace's Token",
    modelDescr: 'Model description',
    modelDescrInputTips: 'The description should not exceed 255 characters',
    confirm: 'Confirm',
    cancel: 'Cancel',
    modelCreateFailed: 'Model create failed',
    modelModifyFailed: 'Model modify failed',
    fileUpload: 'File upload',
    folderUpload: 'Folder upload',
    upload: 'Upload',
    uploadPath: 'Upload Path',
    uploadStatus: 'Upload status',
    modelFileUploadDefaultTips: 'Click to add files or drag files here directly',
    modelFileUploadErrTips: 'File name should not exceed 128 characters, Upload a maximum of {maxCount} files at a time, single file exceeding {size}, please use <a target="_blank" href="{url}" style="cursor: pointer;">SDK to upload</a>,  When there are a large number of files, it is recommended to compress them before uploading',
    modelFileNameTips: 'The file name should not exceed 128 characters',
    modelFileNamSspaceTips: 'The file name contains spaces',
    fileIstoBig: 'File size ({{filesize}} MiB) exceeds the maximum size of ({{maxFilesize}} MiB)',
    removeFile: 'Rmove file',
    uploadSuccess: 'upload success',
    uploadFailed: 'upload failed',
    calcFileMd5: 'Calculating file MD5...',
    uploading: 'Uploading...',
    fileHasAlreadyInTheModel: 'This file has already in the model: ',
    fileEqualInTheModel: 'This file content is the same as other file: ',
    fileExistInTheModel: 'This file name is the same as other file: ',
    uploadFile: 'Upload files',
    uploadFolder: 'Upload folders',
    addUploadFolder: 'Add upload folder',
    clearAll: 'Clear all',
    fileCountAndSize: 'Selected files: {count}, total size: {size}',
    folderUploadPlaceholder: 'Click to add a folder or drag folders/files here directly',
    folderUploadTips: 'The number of files uploaded this time does not exceed {maxCount}, and the total size does not exceed {maxSize}, please use <a target="blank" href="https://openi.pcl.ac.cn/docs/index.html#/api/list">SDK</a> to upload too many large files.',
    folderUploadErrorTips: 'The number of files uploaded this time does not exceed {maxCount}, and single file size does not exceed {maxSize}',
    basicInfo: 'Basic information',
    modelSize: 'Model size',
    descr: 'Description',
    createTime: 'Create Time',
    label: 'Label',
    trainTaskInfo: 'Train task information',
    trainTask: 'Train task',
    codeBranch: 'Code branch',
    bootFile: 'Boot file',
    viewSamples: 'View samples',
    trainDataset: 'Train dataset',
    datasetfile: 'Dataset files',
    fileShort: 'files',
    specInfo: 'Specifications',
    workServerNumber: 'Amount of compute node',
    runParameters: 'Run parameters',
    seeMore: 'View more',
    collapseDetails: 'Collapse details',
    modelFilesList: 'Mode files list',
    fileName: 'File name',
    fileSize: 'File size',
    updateTime: 'Update Time',
    operate: 'Operation',
    download: 'Download',
    delete: 'Delete',
    infoModificationFailed: 'Information modify failed',
    deleteModelFileConfirmTips: 'Are you sure you want to delete the current model file?',
    modelFileDeleteFailed: 'Model file delete failed',
    modelAccess: 'Model Access',
    modelAccessPublic: 'Public',
    modelAccessPrivate: 'Private',
    modelAccessTips: 'Only public projects can be set as public models',
    modelSettings: 'Model Settings',
    edit: 'Edit',
    editFiles: 'Edit files',
    preview: 'Preview',
    modelIntroduction: 'Model Introduction',
    hasNoIntroForModel: 'No detailed model introduction yet',
    createModelIntro: 'Create model Introduction',
    briefIntroduction: 'Introduction',
    addLabels: 'Add labels',
    discardFileChanges: 'Discard current content modifications?',
    editFileContentFirst: 'Please edit the file content first!',
    ownerRepository: 'Repository',
    creator: 'Creator',
    migrator: 'Migrator',
    useModel: 'Use the model',
    modelEvolutionMap: 'Model Evolution Map',
    evolutionMap: 'Evolution Map',
    settings: 'Settings',
    parentModel: 'Parent Model',
    currentModel: 'Current Model',
    derivedModel: 'Derived Model',
    publicDerivedModel: 'Public Derived Model',
    privateDerivedModel: 'Private Derived Model',
    refRepository: 'Reference repository',
    publicRefRepository: 'Public Reference repository',
    privateRefRepository: 'Private Reference repository',
    modelDownloadAll: 'Download All',
    otherOnline: 'Other online url',
    trainUsedDataList: 'The dataset used with this model',
    trainUsedRepo: 'Code used with this modely',
    modelUseTaskList: 'The task used for the model',
    forkModelSuccess: 'The model content has been copied and repository forked successfully!',
    debugModel: 'Debug Model',
    onlineInference: 'Online Inference',
    onlineInferenceTask: 'Online Inference Task',
    onlineLoraTrain: 'Online Train',
    onlineWorkflow: 'online Workflow',
    deleted: 'Deleted',
    derivativeTimes: 'Derivative times',
    derivativeTimes1: 'Derivative',
    mostDerivative: 'Most Derivative',
    modelBaseInfo: 'Basic information of the model',
    modelCollaborator: 'Model collaborators',
    managementTeam: 'Model Management Teams',
    add_team_success: 'The team now have access to the model.',
    remove_team_success: 'The team access to the model has been removed.',
    deletCollaboratedTips: 'After deleting the collaborator, he will no longer be able to access this model. Do you want to continue with the operation?',
    total_size: 'Total size',
    total_size_asc: 'Total size in descending order'
  },
  repos: {
    activeOrganization: 'Active Organization',
    activeUsers: 'Active Users',
    follow: 'Follows',
    unFollow: 'Unfollow',
    selectedFields: 'Recommend Repositories',
    mostPopular: 'Most Popular',
    mostActive: 'Most Active',
    newest: 'Newest',
    recentlyUpdated: 'Recently Updated',
    mostStars: 'Most Stars',
    mostForks: 'Most Forks',
    mostDatasets: 'Most Datasets',
    mostAiTasks: 'Most AI Tasks',
    mostModels: 'Most Models',
    repos: 'Repositories',
    publicRepos: 'Public Repositories',
    repoTopics: 'Repositories Topics',
    dataset: 'Datasets',
    model: 'Models',
    aiTask: 'AI Tasks',
    updated: 'Updated',
    contributors: 'Contributors',
    searchRepositories: 'Search Repositories...',
    search: 'Search',
    allFields: 'All Fields',
    preferred: 'Preferred',
    openIIncubation: 'OpenI Incubation',
    hotPapers: 'Hot Papers',
    watch: 'Watch',
    star: 'Star',
    fork: 'Fork',
    noReposfound: 'No matching repositories found.',
    source: 'Sources',
    mirrors: 'Mirrors',
    collaborative: 'Collaborative',
    forks: 'Forks',
    selectRepo: 'Select repositories',
    selectRepoPlaceholder: 'Search repositories name...',
    cancelToping: 'Unpin',
    topping: 'Pin',
    toppingSuccess: 'Pinned successfully！',
    cancancelTopingSuccess: 'Unpinned successfully！',
    deleteThisRepos: 'Delete This Repository',
    delete_notices_2: '- This operation will permanently delete the <strong>{repos}</strong> repository including the code, issues, merge requests, and other contents',
    sureReposName: 'Enter the repository name as confirmation：',
    repos_name1: 'Repository Name',
    deleteReposNameError: 'Repository name input error!',
  },
  timeObj: {
    ago: '{msg} ago',
    from_now: '{msg} from now',
    now: 'now',
    future: 'future',
    '1s': '1 second',
    '1m': '1 minute',
    '1h': '1 hour',
    '1d': '1 day',
    '1w': '1 week',
    '1mon': '1 month',
    '1y': '1 year',
    seconds: '{msg} seconds',
    minutes: '{msg} minutes',
    hours: '{msg} hours',
    days: '{msg} days',
    weeks: '{msg} weeks',
    months: '{msg} months',
    years: '{msg} years',
    raw_seconds: 'seconds',
    raw_minutes: 'minutes',
  },
  modelObj: {
    model_label: 'Model',
    model_select_placeholder: 'Select Models',
    model_export_placeholder: 'Please select model file',
    model_select: 'Select Models',
    model_current_repo: 'Current repository',
    model_my: 'My Models',
    model_collaborate: 'My Collaborated Models',
    model_collected: 'My Favorite Models',
    model_my_migrate: 'My Migrate Models',
    model_public: 'Public Models',
    model_recommend: 'Recommended Models',
    model_migrate: 'Migrate Models',
    model_search_placeholder: 'Search model name...',
    model_selected: 'Selected model',
    model_ok: 'OK',
    model_most: 'Up to {msg} models.',
    model_not_equal_file: 'Cannot select models with the same name',
    model_exceeds_failed: 'Model size exceeds',
    model_should_same_model: 'Select the files should in the same model.',
    model_search: 'Search model',
    model_square_empty: "It's empty, with nothing",
    model_suport_file_tips: 'The supported format of the model file is [ckpt, pb, h5, json, pkl, pth, t7, pdparams, onnx, pbtxt, keras, mlmodel, cfg, pt]',
    boot_file_helper: 'The startup file is the entry file that your program executes, and it must be a file ending in .py',
    can_online_infer: 'Online',
    can_fine_tune: 'Finetune',
    model_exceeds_failed: "Model size exceeds ",
    model_sdk_use_way: 'Model SDK use way',
    codeUseDlgTriggerTxt: 'How to use models in OpenI',
    codeUseDlgTitle: 'How to use models on the OpenI',
    codeDownDlgTitle: 'How to download files on the OpenI',
    model_not_equal_file: "Cannot select models with the same name.",

    migrate_external_model: 'New Model Migration',
    external_model_name: 'External model name',
    migrate_external_model_name_tips: 'Currently only support migrating models from HuggingFace. Please enter the model name, such as THUDM/chatglm3-6b',
    openi_model_repo_url: 'OpenI model repository URL',
    migrate_model_should_be_public: 'Migrated model should be public',
    migrate_model: 'Migrate Model',
    please_enter_right_external_model_name: 'Please enter the correct external model name',
    migrate_external_model_failed: 'Migrate external model failed!',
    create_model_migrate_loading_content: 'Creating model migration in progress, please wait~',
    create_model_migrate_exists: 'The migrated model already exists, please check the <a href="{url}">details</a>.',
    migrate_from: 'Migrating from {url}',
    migrate_watting: 'Waiting',
    migrating: 'Migrating',
    migrate_success: 'Successful',
    migrate_failed: 'Failed',
    migrate_failed_tips: 'Model migration failed! Please ',
    migrate_retry: 'Re migrate',
    migrate_try_later: ', or try again later',
    re_migrate_failed: 'Re migrate failed',
    sync_now: 'Synchronize Now',
    model_sync: 'Model Synchronize Update',
    current_size: 'Current Size',
    new_size: 'Latest size',
    status_add: 'Added',
    status_del: 'Deleted',
    status_update: 'Updated',
    start_sync: 'Start Synchronize',
    model_no_update_tips: 'The model file remains unchanged and does not require updating',
    model_sdk_tips1: '## Download OpenI file to local folder:\n *File larger than {fileSize} When using SDK to download, please modify the parameters in the following code according to the specific **local save path*** \n ### Download using Python code',
    model_sdk_tips2: '#### Download using the command line',
    model_sdk_tips3: '\nFor installation and usage instructions of the openi library, please refer to the <a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/model/sdk">User Manual</a>。',
    model_download: 'Download',
    model_source: 'Source model：',
    model_name1: 'Model name',
    deleteThisModel: 'Delete this model',
    deleteThisModelTips: 'Deleting a model is permanent and cannot be undone. Please proceed with caution.',
    delete_notices_2: '- This operation will permanently delete the model <strong>{model}</strong>.',
    sureModelName: 'Enter model name for confirmation：',
    deleteModelNameError: 'Model name input error!',
  },
  datasetObj: {
    dataset_label: "Datasets",
    dataset_select_placeholder: "Select Datasets",
    eval_select_placeholder: "Select up to 5 evaluation datasets",
    dataset_select: "Select Datasets",
    dataset_search_placeholder: "Search dataset name ...",
    dataset_unziping: "Decompressing",
    dataset_success: "Decompression successed",
    dataset_unzip_failed: "Decompression failed",
    dataset_status: 'Decompression state',
    dataset_exceeds_failed: "Dataset size exceeds ",
    dataset_my_upload: "Upload by me",
    dataset_current_repo: "Current Repository",
    dataset_public: "Public dataset",
    dataset_collected: "My collection",
    dataset_relate: "Related dataset",
    dataset_selected: "Selected datasets",
    dataset_ok: "OK",
    dataset_not_equal_file: "Cannot select a dataset with the same name.",
    dataset_most: "Up to {msg} datasets.",
    dataset_file_was_deleted: "The file has been deleted",
    dataset_sdk_use_way: 'Dataset SDK use way',
    codeUseDlgTriggerTxt: 'How to use datasets in OpenI',
    codeUseDlgTitle: 'How to use datasets on the OpenI',

    create_new_dataset: 'Create New Dataset',
    dataset_name1: 'Dataset name',
    dataset_name: 'English name of dataset',
    dataset_zh_name: 'Chinese name of dataset',
    dataset_description: 'Dataset Description',
    select_category: 'Select Category',
    task: 'Task',
    application: 'Application',
    select_task: 'Select research direction/application field',
    dataset_name_tooltips: 'Please enter letters, numbers, _, and -, which can only start and end with numbers or letters, with a maximum length of 100 characters.',
    dataset_name_cn_tooltips: 'Please enter Chinese characters, letters, numbers, _, and - up to 100 characters.',
    category: 'Category',
    license: 'License',
    license_helper: 'Select a license file',
    dataset_name_required1: 'Please enter the Chinese name of the dataset',
    dataset_name_required2: 'Input does not comply with dataset name rules',
    dataset_name_required3: 'Please enter the English name of the dataset',
    dataset_description_required: 'Please enter dataset description details',
    category_required: 'Please select a category',
    select_task_required: 'Please select research direction/application field',
    dataset_repo_tips: 'Since each repository can only create one dataset, only repository without a dataset can be specified here',
    exampleDataset: 'Example dataset',
    selectOpeniDataset: 'Select platform dataset',
    buildDatasetTips: 'How to build a dataset',
    create_public_tips: '*The default dataset created is a public dataset, which can be set as a private dataset on the dataset page',
    dataset_owner: 'Owner',
    name: 'Name',
    dataset_acess: 'Dataset access',
    dataset_size: 'Dataset size',
    hasNoIntroForModel: 'No detailed dataset introduction yet',
    createModelIntro: 'Create dataset Introduction',
    dataset_intro: 'Dataset Introduction',
    use_dataset: 'Use the dataset',
    deleteDataFileConfirmTips: 'Are you sure you want to delete the current file {name}?',
    dataFileDeleteFailed: 'Dataset file delete failed',
    dataDownloadAll: 'Download All',
    createDataset: 'Create dataset',
    deletCollaboratedTitle: 'Deleting the collaborator',
    deletCollaboratedTips: 'After deleting the collaborator, he will no longer be able to access this dataset. Do you want to continue with the operation?',
    dataBaseInfo: 'Basic information of the dataset',
    dataSearch: 'Search...',
    notFoundUser: 'No match found',
    administrators: 'Administrator',
    writePermission: 'Write',
    readPermission: 'Read',
    datasetCollaborator: 'Dataset collaborators',
    searchUsers: 'Search Users',
    addCollaborators: 'Add collaborator',
    managementTeam: 'Dataset Management Teams',
    searchTeams: 'search Teams',
    addTeam: 'Add Team',
    dangerousOperationZone: 'Dangerous operation zone',
    deleteThisDataset: 'Delete this dataset',
    deleteThisDatasetTips: 'Deleting a dataset is permanent and cannot be undone. Please proceed with caution.',
    sureDatasetName: 'Enter dataset name for confirmation：',
    deleteDatasetNameError: 'Dataset name input error!',
    add_collaborator_success: 'The collaborator has been added.',
    add_team_success: 'The team now have access to the dataset.',
    remove_collaborator_success: 'The collaborator has been removed.',
    remove_team_success: 'The team access to the dataset has been removed.',
    delete_notices_1: '- This operation <strong> cannot be </strong> rolled back.',
    delete_notices_2: '- This operation will permanently delete the dataset <strong>{dataset}</strong>.',
  },
  imagesObj: {
    cloudbrain_images: 'Image',
    openIGPU: 'OpenI GPU',
    c2netGPU: 'C2Net GPU',
    images_search: 'Search Image tag/description/operating system/python library/label...',
    image_public: 'Recommended Image',
    image_my: 'My Image',
    image_collected: 'My Favorite Image',
    framework: 'Framework',
    version: 'Version',
    frameworkName: 'Framework name',
    frameworkVersion: 'Framework version',
    pyVersion: 'Python version',
    cudaVersion: 'Cuda version',
    cannVersion: 'Cann version',
    dtkVersion: 'Dtk version',
    deleteTips: 'Are you sure you want to delete this image? Once this image is deleted, it cannot be recovered.',
    deleteSuccessTips: 'Successfully deleted',
    editImage: 'Modify image',
    submitImage: 'Submit image',
    appyImage: 'Apply to become a platform recommended image',
    imageTag: 'Image tag',
    imageDesc:'Image description',
    imageTagPlaceholder: 'Please enter the image tag',
    imageTagInputTips: 'Please enter letters, numbers, _, . and -, with a maximum length of 50 characters and starting with a letter.',
    imageAdress: 'Image address',
    imageAdressPlaceholder: 'Please enter the image adress',
    imageAiCenterPlaceholder: 'Please enter the ai center. For example:\n[{"aiCenterId":"","trainJobUrl":"","notebookUrl":"","accDeviceModel":"",poolIds:""}]',
    operationSystem: 'Operating system',
    operationSystemName: 'Operating system name',
    operationSystemNamePlaceholder: 'Please enter the operating system name',
    operationSystemVersionPlaceholder: 'Please enter the operating system version',
    pyPackge: 'Python libraries',
    thirdPackages: 'Python libraries and version',
    thirdPackagesPlaceholder: `Please enter the installed Python library and version, one per line, up to 10 lines. For example:\ntorch==1.13.1\ntransformers==4.25.1`,
    topic: 'Label',
    topicPlaceholder: 'After entering, press enter to confirm the label',
    topicTips: `Please provide additional information in the label field for the image, such as the compatible card type: <span class="light">T4</span>, <span class="light">Ascend 910</span>`,
    descr: 'Image description',
    descrPlaceholder: 'Please enter the image description, which should not exceed 1000 characters',
    recommend: 'Recommend',
    notRecommend: 'Unrecommend',
    submitTips: 'The code directory /tmp/code will not be submitted with the image, and new files (folders) in other directories will be packaged into the image.',
    submitNpuTip1: 'The directory /home/ma-user/work will not be submitted with the image, and other directories will be packaged into the image.',
    submitNpuTip2: 'During the image saving process, the Notebook will be unavailable and the status of this task will change from Running to Waiting.',
    submitDcuTip1: '目录/home/ma-user/work不会随镜像提交，其他目录都会打包到镜像中。',
    submitDcuTip2: 'The image must be smaller than 30G to be saved successfully. If the image is not used for 30 days, the system will be cleaned up and cannot be used',
    submitApply: 'Submit Apply',
    imageCommitting: 'Image committing...',
    imageCommitSuccess: 'Image committed successfully',
    imageCommitErrorTips1: 'Check whether the size of the submitted image exceeds 20G!',
    imageCommitErrorTips2: 'Check whether the size of the submitted image exceeds 40G!',
    committing: 'Commiting',
    commitSuccess: 'Committed successfully',
    commitFailed: 'Committed failed',
    recommendNeedReview: 'Pending approval',
    recommendReviewApproved: 'Approved',
    recommendReviewFailed: 'Not approved',
    applyForRecommend: 'Apply recommendation',
    copyAdress: 'Copy adress',
    filterImages: 'Filter images',
    filterImagesPlaceholderCuda: 'Framework name/Framework version/Python version/Cuda version',
    filterImagesPlaceholderCann: 'Framework name/Framework version/Python version/Cann version',
    filterImagesPlaceholderDtk: 'Framework name/Framework version/Python version/Dtk version',
    imageTaskType: 'Task type',
    imageTaskTips: 'Apply to',
    approval_status: 'Approval status',
    all_approval_status: 'All Approval Status',
    pending_approval: 'Pending approval',
    approved: 'Approved',
    not_approved: 'Not approved',
    none: 'None',
    create_cloud_brain_mirror: 'Create cloud brain image',
    not_recommend: 'Not recommend',
  },
  specObj: {
    resSelectTips: 'The "resource specification" is the hardware you use to run the task. In order for more people to use the resources of this platform, please select according to your actual needs',
    no_use_resource: 'No resources available',
  },
  datasets: {
    computer_vision: "computer vision",
    natural_language_processing: "natural language processing",
    speech_processing: "speech processing",
    computer_vision_natural_language_processing:
      "computer vision and natural language processing",
    machine_translation: "machine translation",
    medical_imaging: "medical imaging",
    question_answering_system: "question answering system",
    information_retrieval: "information retrieval",
    knowledge_graph: "knowledge graph",
    text_annotation: "text annotation",
    text_categorization: "text categorization",
    emotion_analysis: "emotion analysis",
    language_modeling: "language modeling",
    speech_recognition: "speech recognition",
    automatic_digest: "automatic digest",
    information_extraction: "information extraction",
    description_generation: "description generation",
    image_classification: "image classification",
    face_recognition: "face recognition",
    image_search: "image search",
    target_detection: "target detection",
    image_description_generation: "image description generation",
    vehicle_license_plate_recognition: "vehicle license plate recognition",
    medical_image_analysis: "medical image analysis",
    unmanned: "unmanned",
    unmanned_security: "unmanned security",
    drone: "drone",
    vr_ar: "VR/AR",
    "2_d_vision": "2.D vision",
    "2.5_d_vision": "2.5D vision",
    "3_d_reconstruction": "3Dreconstruction",
    image_processing: "image processing",
    video_processing: "video processing",
    visual_input_system: "visual input system",
    speech_coding: "speech coding",
    speech_enhancement: "speech enhancement",
    speech_synthesis: "speech synthesis",
    ros_hmci_datasets: "ROS-hmci datasets",
    downloadtimes: 'Download times',
    downloadtimes1: 'Download',
    citations: 'Citations times',
    citations1: 'Citations',
    default: "Default",
    newest: "Newest",
    oldest: "Oldest",
    recentupdate: "Recently updated",
    leastupdate: "Least recently updated",
    moststars: "Collection Nums",
    mostCollections: "Most Stars",
    mostusecount: "Most Quote",
    alphabetasc: "Alphabetical order ascending",
    alphabetdesc: "Alphabetical order descending",
    chinesename: "Chinese name",
    chinesenameasc: "Reverse Order of Chinese Names",
    size: "Size",
    sort: "Sort",
    unstarSuccess: "Cancel favorite successfully!",
    starSuccess: "favorite successfully！",
    platform_recommendations: 'Show platform recommendations only',
    category: 'Category',
    task: 'Task',
    license: 'License',
    publick_dataset: 'Public Dataset',
    my_dataset: 'My Datasets',
    favorite_dataset: 'My Favorite Datasets',
    recommend_dataset: 'Recommended Datasets',
    collaborated_dataset: 'My Collaborated Datasets',
    views: 'Views',
    loadMore: 'Load more'
  },
  cloudbrainObj: {
    cloudbrain: 'Cloudbrain',
    openi: 'OpenI Resource Cluster',
    c2net: 'China Computing NET(Beta)',
    create: 'New ',
    createTask: 'Create Task',
    cluster: 'Resource cluster',
    computeResource: 'Computing resource',
    sameTaskTips1: 'You have already {count} running or waiting task(s), which has reached the maximum limit. Please wait until the tasks are finished before creating new ones.',
    sameTaskTips2: 'You can view all your Computing tasks in <a href="/cloudbrains" target="_blank"> My Workspace &gt; Computing Task </a>.',
    pathTips1: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the dataset is storaged in <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the run parameter <strong style="color:#010101">{model}</strong>, and please put your model into <strong style="color:#010101">{output}</strong> then you can download it online.',
    pathTips11: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the dataset is storaged in <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the <strong style="color:#010101">{model}</strong>, and please put your model into <strong style="color:#010101">{output}</strong> then you can download it online.',
    pathTips2: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the dataset is storaged in <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the <strong style="color:#010101">{model}</strong>, and please put your model into <strong style="color:#010101">{output}</strong> then you can download it online.',
    pathTips3: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the dataset is storaged in <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the <strong style="color:#010101">{model}</strong>.',
    pathTips4: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the pre-trained model is storaged in the run parameter <strong style="color:#010101">{model}</strong>, and please put your model into <strong style="color:#010101">{output}</strong> then you can download it online.',
    pathTips5: 'The dataset is stored in <strong style="color:#010101">{dataset}</strong>, the model file is stored in <strong style="color:#010101">{model}</strong>, please store the inference output in <strong style="color:#010101">{output}</strong> for subsequent downloads.',
    pathTips6: 'The dataset location is stored in the run parameter <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the run parameter <strong style="color:#010101">{model}</strong>, and the output path is stored in the run parameter <strong style="color:#010101">{output}</strong>.',
    pathTips66: 'The dataset location is stored in the run parameter <strong style="color:#010101">{dataset}</strong>, the pre-trained model is storaged in the run parameter <strong style="color:#010101">{model}</strong>, and please put your model into <strong style="color:#010101">{output}</strong> then you can download it online.',
    pathTips7: 'The dataset location is stored in the run parameter <strong style="color:#010101">{dataset}</strong>, the model file is stored in the run parameter <strong style="color:#010101">{model}</strong>, and the inference output path is stored in the run parameter <strong style="color:#010101">{output}</strong>.',
    pathTips71: 'The code is storaged in <strong style="color:#010101">{code}</strong>, the dataset is storaged in <strong style="color:#010101">{dataset}</strong>, the model file is storaged in the <strong style="color:#010101">{model}</strong>, and please put your inference output into <strong style="color:#010101">{output}</strong> then you can download it online.',
    basicInfo: 'Basic Info',
    paramsSetting: 'Parameter setting',
    resourceSetting: 'Resource setting',
    runningStatus: 'Running status',
    basicParameters: 'Basic parameters',
    otherParameters: 'Other parameters',
    parameters: 'Parameters',
    valueAndContent: 'Value&Content',
    taskPrepareTips: 'The task is currently being prepared. Drink a glass of water and come back to take a look~',
    waitCountStart: 'Your current queue position is ',
    waitCountEnd: '',
    mindTorchHelper: 'Don\'t want to queue up? View how to migrate PyTorch to MindSpore with just one step',
    task: ' Task',
    taskList: 'Task List',
    taskName: 'Task name',
    appName: 'App name',
    appList: 'App List',
    taskNameTips: 'Name must start with a lowercase letter or number,can include lowercase letter,number,_ and -,can not end with _, and can be up to 36 characters long.',
    taskNameTips1: 'Name must start with a lowercase letter,can include lowercase letter,number,and -, and between 5 and 26 characters.',
    imageInnerUrlErrTips: 'The image url you specified is not applicable to this task. Please specify a different image.',
    imageUrlErrTips: 'Please enter a valid image url.',
    taskDescr: 'Description',
    taskDescrPlaceholder: 'The description should not exceed 255 characters',
    codeBranch: 'Code branch',
    image: 'Image',
    selectImage: 'Select Image',
    selectImagePlaceholder: 'Select image or input image url',
    dataset: 'Datasets',
    networkType: 'Access Internet',
    allNetworkType: 'All network',
    codeGenerate: 'Code Generate',
    noInternet: 'No',
    hasInternet: 'Yes',
    networkTypeDesc: '「Access Internet」Describe whether the computing resource center supports internet access. When \'No\' is selected, more computing resource centers can be allocated, and the dataset and models on the OpenI platform can still be used.',
    resourceSpec: 'Specification',
    specPlaceholder: 'Select resource specification',
    specDescr: 'Resource Note',
    PointGainDescr: 'Points acquisition instructions',
    balanceOfPoints: 'Balance of Points',
    points: 'Points',
    canUseTime: ', expected to be available for ',
    hours: 'Hours',
    versionCount: 'Version Nums',
    runVersion: 'Run Version',
    createTime: 'Create time',
    startRunTime: 'Start run time',
    endRunTime: 'End run time',
    runDuration: 'Running Time',
    refresh: 'Refresh',
    codePath: 'Code storage path',
    datasetPath: 'Dataset storage path',
    modelPath: 'Model storage path',
    outputPath: 'Output storage path',
    codeObsPath: 'Code OBS address',
    clusterAndComputeResource: 'Cluster/Compute Resources',
    runParameter: 'Run Parameters',
    addRunParameter: 'Add Run Parameters',
    parameterName: 'Parameter Name',
    parameterValue: 'Parameter Value',
    customPath: 'Custom Path',
    port: 'Port',
    customPathTips: 'Custom paths are only allowed to contain lowercase letters and numbers, with the first character being a letter, and the length must not exceed 32 characters; The port number can be selected from the range of 8000-8800',
    debug: 'Debug',
    reDebug: 'Restart',
    reInfer: 'ReInference',
    stop: 'Stop',
    modify: 'Modify',
    delete: 'Delete',
    startUse: 'Start use',
    more: 'More',
    commitImage: 'Submit Image',
    downloadModel: 'Download',
    configurationInfo: 'Configuration Information',
    taskRuntimeInfo: 'Task Runtime Information',
    log: 'Logs',
    logFile: 'Log file',
    downloadLog: 'Download log file',
    viewFullScreen: 'Fullscreen',
    exitFullScreen: 'Exit fullscreen',
    scrolledToTopTip: 'You have scrolled to the top of the log',
    scrolledToBottomTip: 'You have scrolled to the bottom of the log',
    resourceOccupancy: 'Resources Occupancy',
    modelDownload: 'File Download',
    lossPlot: 'loss',
    evalOverview: 'Overview of Evaluation Results',
    evalDetail: 'Evaluation Results Details',
    failedReason: 'Failed reason',
    publicImage: 'Public Image',
    recommendImage: 'Recommend Images',
    myImage: 'My Images',
    myFavImage: 'My collected images',
    searchImagePlaceholder: 'Search image tag/description/operating system/python library/label...',
    useImage: 'Use',
    submitting: 'Commiting',
    submitFailed: 'Commit failed',
    checkImageSizeTips: 'Check whether the size of the submitted image exceeds 20G.',
    maxTaskTips: '<p><span>*</span>The platform only retains the results of debug, train, inference and evaluation tasks for nearly<span> 30 </span> days. <span>Tasks over 30 days will not be able to download results and view logs, and cannot be debugged、evaluation and trained again</span></p>',
    datasetFiles: 'Datasets',
    fileWasDeleted: 'The file has been deleted',
    debugTaskEmptyTitle: 'Debug task has not been created',
    debugTaskEmptyTip0: 'Code version: You have not initialized the code repository, please <a href="{url}">initialized</a> first;',
    debugTaskEmptyTip1: 'Running time: no more than 4 hours, it will automatically stop if it exceeds 4 hours;',
    debugTaskEmptyTip2: 'Dataset: Cloud Brain 1 provides CPU/GPU,Cloud Brain 2 provides Ascend NPU. And dataset also needs to be uploaded to the corresponding environment;',
    debugTaskEmptyTip3: 'Instructions for use: You can refer to the OpenI AI collaboration platform<a href="{url}"> Help Center </a>.',
    onlineInferTaskEmptyTitle: 'Online Inference task has not been created',
    onlineInferEmptyTip2: 'Dataset: Cloud Brain 1 provides CPU/GPU,Cloud Brain 2 provides Ascend NPU. And dataset also needs to be uploaded to the corresponding environment;',
    superTaskEmptyTitle: 'HPC task has not been created',
    generalTaskEmptyTitle: 'General task has not been created',
    generalTaskEmptyTip1: 'This task type has the following characteristics and can only be used after submitting a usage application and approval on the <a href="/computingpower/demand">Computing resources</a> page:<br/> (1) Provide a Jupyter debugging environment.<br/> (2) The running time is unlimited, but points are required.<br/> (3) Supports open ports.<br/> (4) Saving images is not supported, and debugging again is not supported.',
    deleteConfirmTips: 'Are you sure you want to delete this task? Once this task is deleted, it cannot be recovered.',
    deleteBatchConfirmTips: 'Are you sure to batch delete the selected tasks? Once a task is deleted, it cannot be restored.',
    deletingTips: 'Task deletion in progress, please wait',
    tabTitDebug: 'Debug Task',
    tabTitTrain: 'Train Task',
    tabTitInference: 'Inference Task',
    tabTitBenchmark: 'Model Evaluation',
    trainTaskEmptyTitle: 'Train task has not been created',
    trainTaskEmptyTip2: 'Dataset: Cloud Brain 1 provides CPU/GPU,Cloud Brain 2 provides Ascend NPU. And dataset also needs to be uploaded to the corresponding environment;',
    inferenceTaskEmptyTitle: 'Inference task has not been created',
    inferenceTaskEmptyTip2: 'Dataset: Cloud Brain 1 provides CPU/GPU,Cloud Brain 2 provides Ascend NPU. And dataset also needs to be uploaded to the corresponding environment;',
    bootFileTips: 'The startup file is the entry file that your program executes, and it must be a file ending in .py',
    viewSample: 'View sample',
    tabTitOnlineInference: 'Online Inference',
    tabTitGeneral: 'General Task',
    allResultDownload: 'All result download',
    downloadDisplayMaxCountTips: 'A maximum of {count} files or folders are displayed in a single directory. The storage quota for compute task results is {size} GiB. Exceeding the quota will result in data loss.',
    file_sync_ing: "File synchronization in progress, please wait",
    file_sync_wait: "File synchronization in waiting, please wait",
    file_sync_fail: "File synchronization failed",
    eval_task_ing: "The evaluation task is in progress, come back later to take a look",
    no_file_to_download: "No files can be downloaded",
    task_not_finished: "Task not finished yet, please wait",
    retrieve_results: "Retrieve results",
    reuseLastResult: 'Reuse last result',
    continue_helper: 'Check Reuse to copy the output result file of the last training task',
    computeNode: 'Compute Node',
    computeNodeCount: 'Compute node count',
    exportDataset: {
      exportDatasetTitle: 'Export the results to a dataset',
      exportDatasetTips: '<span style="color:red">*</span> The exported file can ultimately be viewed under the dataset of your choice.',
      export_failed: 'Export failed',
      export_has_same_file: 'The same file already exists in the current dataset',
      export_has_same_file1: 'The same file already exists in the current model',
      export_exceed_storage: 'The current file exceeds the size limit',
      export_success: 'Export success',
      exporting: ' Exporting',
      please_select_file: 'Please select a file first',
      please_select_output_file: 'Select result file',
      select_file: 'Select File',
      file_descr: 'File description',
      no_dataset: 'No dataset has been created yet, ',
      create_dataset: 'to create the dataset.',
      please_select_dataset: 'Please select the dataset to export to first',
    },
    chartResourceUsage: 'Usage(%)',
    chartTime: 'Time(min)',
    scrollToTop: 'Scroll to top',
    scrollToBottom: 'Scroll to bottom',
    migratingData: 'Data migration in progress',
    centerPending: 'Queuing in sub centers',
    imagePulling: 'Pulling image in progress',
    sdkUseWay: 'c2net library usage',

    dialogTips: {
      title1: 'When using online inference to provide webui or API services, it is necessary to understand the following points',
      tips1: "The platform does not directly expose custom ports to the external network for service provision. Instead, FastAPI can be used to forward requests to a designated externally exposed URL for service delivery.",
      tips1_1: 'Webui service reference:',
      tips1_2: 'API service reference:',
      tips2: 'Service startup instruction reference',
      tips3: 'Online reasoning tasks only have logs returned when the task is terminated',
      tips61: 'Detailed usage methods can be found in ',
      tips62: 'the code repository',
      tips7: "Don't prompt again",
      tips8: 'Close',
      tips9: 'OpenI Online Inference Deployment Requirements',
    },
    codeUseDlgTriggerTxt: 'How to access data resources in code',
    codeUseDlgTitle: 'How to obtain models, datasets, and output paths in code via the c2net library',
    sdkCodeTip1: 'Please use c2net library to access relevant resources in the container, which can be referred to as <a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/cloudbrain/codepath">Help</a>.',
    sdkCodeTip2: 'Based on the type of computing task you choose, as well as the specified datasets, models, etc. The example code for accessing datasets and models and uploading training output are as follows:',
    generalTaskSdkCodeTip0: 'How to open ports for general task',
    generalTaskSdkCodeTip1: 'Run the following command to configure HTTP proxy in the environment:',
    generalTaskSdkCodeTip2: '/root/bin/scc tunnel http http://127.0.0.1:7860 (Port number 7860 can be customized)',
    generalTaskSdkCodeTip3: 'After successful configuration, output the following information:',
    generalTaskSdkCodeTip4: 'You can use the address <code>https://be22fe9f-d140-474c-81f4-30fb068157b5.tunnel.paracloud.com</code> to access the corresponding service.',

    searchTaskName: 'Search Task Name...',
    searchTaskNameOrCreator: 'Search Task Name/Creator...',
    downloadReport: 'Download Report',
    cloudbrainTaskType: 'Task Type',
    ComputingResourceInfo: 'Computing resource information',
    repo: 'Repository',
    cloudbrainTaskName: 'Cloudbrain Name',

    taskIsAutomaticStop: 'Task is automatic stop',
    automaticStop: 'Automatic stop',
    manualStop: 'Manual stop',
    automaticStopTips: 'This task will automatically stop when the running time exceeds the time you have selected, or when the point balance is insufficient.',
    manualStopTips: 'This task will be manually stopped by you or automatically stopped when your point balance is insufficient.',
    customize: 'Customize',
    numOfHours: '{num} hours',
    customizeTimeLimitPlaceholder: 'Please enter an integer between 1 and 24',
    debugTaskTimeLimitTips: 'The debug type task has a usage time limit, and will automatically end if it expires. <span>Please save the debugging results before the deadline<span>.',
    autoStopTimeTips: 'The task will automatically stop after {min} minutes. Please save the results',

    forkRepo: 'Fork existing repository',
    newRepo: 'New repository',
    migrateRepo: 'New migrate',
    pullRequests: 'Pull requests',
    issues: 'Issues',
    selectRepo: 'Select repository',
    nextStep: 'Next Step',
    previousStep: 'Previous Step',
    instructionsForUse: 'Instructions for use',
    setUp: 'Set ',
    aiTaskType: 'AI task type',
    newCloudbrainAiTask: 'New Cloudbrain(AI) Task',
    selectAiTaskTypeAndRepo: 'Select AI Task Type and Repository',
    specifyComputingResourcesAndRarameters: 'Specify Computing Resources and Parameters',
    dataPreparing: 'Data preparation in progress, please wait a moment~',

    selectTheTaskType: 'Select the type of task you need to create.',
    debugTaskDesc: 'Interactive editing environment',
    debugTaskDescLong: 'Provide a Jupyter or Modelarts interactive debugging environment, suitable for debugging and building early models.',
    debugTaskDescLong1: 'Debug task will automatically stop after running for more than 4 hours.',
    trainTaskDesc: 'Submit to task queue',
    trainTaskDescLong: 'Suitable for scenarios where long-term execution does not require frequent modification of algorithm code.',
    inferenceTaskDesc: 'Supercomputing power computing task',
    inferenceTaskDescLong: 'Support running multiple applications on supercomputing power.',
    onlineinferTaskDesc: 'Build a real-time inference interface',
    onlineinferTaskDescLong: 'Provide online deployment capabilities for the model, using the Gradio framework to generate real-time inference interfaces.',
    generalTaskDesc: 'Provide Jupyter debugging environment',
    generalTaskDescLong: 'Provide a Jupyter debugging environment, which requires submitting a usage application on the computing resources page and approval before it can be used.',
    noAiTasksInThisRepo: 'There are no Computing tasks under this repository yet',
    createNewAitask: 'Create computing task',
    visualization: 'Visualization',
    sourceFtName: 'Source fine-tuning task name',
    tensorBoardVisualization: 'TensorBoard Visualization',
    viewVisualization: 'View TensorBoard visualization results',
    startDebug: 'Start Debug',
    stopTask: 'Stop Task',
    taskTmpl: 'Computing task Template',
    saveTaskTmpl: 'Save As Computing Task Template',
    saveNewModel: 'Export To New Model',
    exportData: 'Export Data',
    exportToDataset: 'Export To Dataset',
    deploymentExperience: 'Deployment Experience',
    aimTrainCompare: 'Training Comparison',
    aimTrainCompareDlgTitle: 'Select Training Tasks for Comparison',
    aimTrainCompareSelectTips: 'Please select {minCount} to {maxCount} tasks for training comparison!',
    aimVisualization: 'AIM Visualization',
    batchDelete: 'Batch delete',
    deleteFailed: 'Delete Failed',

    all: 'All',
    ihave: 'My Datasets',
    iCollaborate: 'My Collaborated Datasets',
    iCollect: 'My Favorite Datasets',
    selectApp: 'Select App',
    cbOffline: 'The Cloudbrain tab under the project is about to go offline',
    cbOffflineTips: 'Please go to the <a href="/cloudbrains/create"> "My Workspace>Computing Tasks" </a> page to view the existing Computing Tasks on this page。',
    exportOutputTis: 'Export the results to the dataset or model, please move to the PC web page',
    repoStorageTips: 'Control project size within the storage quota of {size} GiB for compute tasks.',
    runningLimit: 'This account can run {count} {taskType} simultaneously.',
    forbidPenetrationStatement: 'Declaration of Prohibition of Any Form of Penetration Behavior',
    penaltyTipContent: 'This platform strictly prohibits any form of <span class="highlight">penetration behavior</span>. Violators will have their computing power points deducted, login restricted, and serious cases will bear <span class="highlight">legal responsibility</span>!',    
  },
  taskTmplObj: {
    tmplName: 'Template Name',
    tmplNamePlacehoulder: 'Please enter a template name of up to 20 characters',
    tmplDescr: 'Template Description',
    quickRunTmplTips: 'One click run computing task template',
    editTmplFile: 'Edit template file',
    addTmpl: 'New template',
    dragSortTips: 'Drag tab to adjust order',
    deleteTmplTips: 'Do you want to delete the current Computing Task template?',
    completeTmplTips: 'Please complete the required content in the position {n} template!',
    more: 'More',
    collapsed: 'Collapsed',
    edit: 'Edit',
    run: 'Run',
    runTmplForkTips: 'You do not have permission for this repository to create a new computing task. We suggest that you fork this repository and then run the computing task with just one click.',
    forkRepo: 'Fork this repository',
    runTmplFailedTips: 'Run template failed!',
    runTmplWithConfigsErrorTips: 'Template configuration exception, unable to run properly!',
    useTaskTmpl: 'Using task template',
    saveTaskTmpl: 'Save computing task template',
    unAvailableTmplSpec: 'Template Specification "{msg}" due to reasons such as non-existent permissions or resources, <span style="color:red">currently unavailable.</span>',
    unAvailableTmplImage: 'Template Image "{msg}" due to reasons such as non-existent permissions or resources, <span style="color:red">currently unavailable.</span>',
    unAvailableTmplBranch: 'Template Code Branch "{msg}" due to reasons such as non-existent permissions or resources, <span style="color:red">currently unavailable.</span>',

    taskTmpl: 'Computing Task Template',
    publicTmpl: 'Public Templates',
    recommendTmpl: 'Recommended Templates',
    runTimes: 'Number of runs',
    searchTaskTmpl: 'Search for template name',
    createTaskTmpl: 'Create computing task template',
    myCreated: 'My Templates',
    myCollected: 'My Favorite Templates',
    deleteTaskTmplConfirmTips: 'Confirm delete the current computing task template?',
    tmplAccessRight: 'Template Access',
    accessRight: 'Access',
    collectedNum: 'Collection Nums',
    tagsAndDescr: 'Tags and Description',
    modelDatasetAndRepo: 'Model, Dataset and Repository',
    cancelRecommend: 'Cancel Recommendation',
    setRecommend: 'Set Recommended',
    cancelRecommendSuccess: 'Cancel recommendation success',
    setRecommendSuccess: 'Set recommended success',
    tmplCoreElements: 'Core Elements',
    editTmpl: 'Edit Template',
    tmplInfo: 'Template Information',
    tmplTags: 'Template tags',
    tagsPlaceholder: 'After entering, press enter to confirm the label, enter up to 10',
    editTaskTmpl: 'Edit Computing Task Template',
    createNewTaskTmpl: 'New Computing Task Template',
    createTaskTmplErrTips: 'Please complete the computing task template information',
    taskTmplSaveTips: 'The computing task template is being saved, please wait a moment',
    taskTmplSaveFailedTips: 'Failed to save computing task template',
    taskTmplReferencedRepo: 'Computing task templates that have referenced this repository',
  },
  superComputeObj: {
    mmlSparkDescr: `The full name of MMLSpark is Microsoft Machine Learning for Apache Spark, which enables users to run customized container images and grants them root accesses within the container. Users can directly use Microsoft's MMLSpark provided by the platform.\nNote: MMLSpark is a Spark version provided by Microsoft for machine learning environments（ <a target="_blank" href="https://github.com/Azure/mmlspark">https://github.com/Azure/mmlspark</a> ）Regarding mmlspark, please refer to the following paper: <a target="_blank" href="https://arxiv.org/pdf/1810.08744.pdf">https://arxiv.org/pdf/1810.08744.pdf</a>`,
  },
  modelSquare: {
    llmHeader: 'Model experience',
    chatGlm_intro: 'is an open source conversational language model that supports Chinese and English bilingualism, provided by Zhipu AI.',
    llama2: 'is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters. This is the repository for the 7B fine-tuned model, optimized for dialogue use cases and converted for the Hugging Face Transformers format.',
    dialogtips1: 'Hello 👋! Welcome to experience the large model knowledge base Q&A',
    dialogtips21: 'This experience is based on',
    dialogtips22: 'language model and m3-base vector model',
    dialogtips3: 'Please choose to talk to the model directly or ask questions based on the local knowledge base on the right.',
    dialogtips4: 'In the knowledge base Q&A mode, after selecting the name of the knowledge base, you can start Q&A.',
    dialogtips5: 'If necessary, you can upload files/folders to the knowledge base or delete files from the knowledge base after selecting the knowledge base name.',
    dialogtips6: 'The model has been successfully loaded, you can start the conversation, or select the mode from the right to start the conversation',
    promptPlaceholder: 'Please input the question content (Ctrl+Enter=line feed, press Enter to submit)',
    dialogModeSelect: 'Please select the dialogue mode',
    dialogLLM: 'LLM dialogue',
    dialogKb: 'Knowledge Base Q&A',
    configKb: 'Configure Knowledge Base',
    updatekb: 'Update existing knowledge base options',
    recreateKb: 'Vector library reconstruction in progress, please be patient and do not refresh or close the webpage',
    selectKb: 'Please select the knowledge base to load:',
    createKb: 'Create knowledge base',
    deleteKb: 'Delete knowledge base',
    deleteKbTips: 'Are you sure to delete the {knowledgeValue} knowledge base?',
    deleteVbTips: 'Are you sure to delete the knowledge base files？',
    uploadFile: 'Upload files',
    uploadFileTips1: 'Drag the file here, or click <em>to upload</em>',
    uploadFileTips2: 'Single file upload size limit is 1MB • HTML, MD, JSON, CSV, TXT, XML, DOCX',
    addFileToKb: 'Add files to the knowledge base',
    manageFile: 'Manage files',
    deleteKbFileSelect: 'Please select the file to delete from the existing files in the knowledge base',
    deleteKbFile: 'Delete files from the knowledge base',
    recreateKbSuccess: '{knowledgeValue} vector library reconstruction successful',
    noPermission: 'You do not have permission to operate',
    fileExit: 'File already exists',
    fileExceed: 'Files exceeding 1MB',
    fileError: 'File error, please re-upload!',
    fileTypeError: 'File type error, please re-upload!',
    fileUploadSuccess: '{fileName} File uploaded successfully!',
    kbName: 'Knowledge Base Name',
    createKbPlaceholder: 'The new knowledge base name can only be numbers and letters',
    vectorType: 'Vector Library Type',
    embedModel: 'Embedding Model',
    cancel: 'Cancel',
    create: 'Create',
    ok: 'Ok',
    kbNameDetect1: 'Name cannot be empty',
    kbNameDetect2: 'The name can only be numbers and letters',
    chatExceedCount: 'If the usage limit is exceeded, you will not be able to experience the model service!',
    useNotice: 'User experience instructions',
    agreeNotice: 'Agree to <a href="/home/model_privacy" target="_blank"> 《OpenI Qizhi Community AI Collaboration Platform Disclaimer and Service Usage Specification》</a> <p style="text-align: center;margin-top: 1rem;color: red;">Kind reminder: Unreasonable use may result in account closure</p>',
    modelProvide: '《Disclaimer and Service Usage Specifications》',
    modelNotExist: 'Model not exist',

    maxTries: 'Limited experience {maxTries} times',
    modelChatTask: 'Create a model online experience task',
    createChatTips1: 'Click the button below to create an online experience task. After successful creation, you can experience {expireMinutes} minutes online',
    createChatTips2: 'The online experience tasks created are exclusive to your account only.',
    createChatTips3: 'You have already created an online experience task for the current model. Click the button below to directly enter the experience interface',
    createChatBtns1: 'Create Online Experience task',
    createEvalBtns1: 'Create Evaluation task',
    createChatBtns2: 'online experience',
    experienceTime: 'Experience Countdown：',
    uploadFIleLimit: 'Upload up to 10 files',
    inputNotEmpty: 'The input content cannot be empty!',
    sessionChating: 'Session loading, don not be impatient!',
    sessionSding: 'Image generation in progress, don not be impatient！',
    chatBanned: 'Your account has been banned, please contact the website administrator',
    chatIllegal: "I'm very sorry, as an artificial intelligence assistant I can only provide objective information. Do you have anything else to ask?",
    chatExpireMins: 'If the experience time exceeds {expireMinutes} minutes, the [online experience task]({locaRefresh}) needs to be re-created.',
    chatExpired: 'Chat session expired, please create a new chat.',
    stopExperience: 'Stop the experience',
    experienceDuration: 'Experience duration',
    requireTimeout: 'Request timed out, please try again later',
    sdPlaceholder: 'Please describe the desired image content in Chinese or English, and using English prompts will result in better results.',
    submitTips: 'Ctrl + Enter line break',
    negativePromptPlaceholder: 'Please describe the screen content that you do not want to generate.',
    width: 'Width',
    height: 'Height',
    num_images_per_prompt: 'Number images',
    negative_prompt: 'Negative prompt',
    steps: 'Steps',
    seed: 'Seed',
    scheduler_name: 'Scheduler',
    guidance_scale: 'Guidance scale',
    newChat: 'New Chat',
    stopChat: 'Stop generating',
    stopedChat: 'Stoped generating',
    refreshChat: 'Regenerate',
    like: 'Like',
    unlike: 'Dislike',
    chatHeaderTips: 'Hello 👋！ Welcome to experience the {modelName} model',
    deepseekHeaderTips: "hello 👋！ Welcome to experience DeepSeek's comprehensive service for multi-scale models",
    //deepseekHeaderTips: "Hello! 👋！ Welcome to experience DeepSeek's intelligent Q&A service! We use intelligent scheduling technology to automatically match the model with the optimal parameter size based on the complexity of the problem, providing you with accurate and efficient answers",
    systemPlaceholder: 'Please enter the system persona, for example, "You are an AI assistant"',
    temperature: 'Temperature',
    top_p: 'Top_p',
    repetition_penalty: 'Repetition_penalty',
    max_tokens: 'Max_tokens',
    system_message: 'System_message',
    history: 'History',
    experienceStopTips: 'Task stopping, please wait!',
    experienceStopSuccess: 'Task stopped successfully, the experience service has been paused!',
    modelFinetuen: 'Model Finetune',
    pcMind: 'PengCheng · Mind',
    sdModelFinetuen: 'CV Finetune',
    sdModelFinetuenTask: 'CV Finetune Task',
    modelExperience: 'Model experience',
    modelExperienceTips: 'Provide online experience function for large models, where you can choose suitable models and computing resources according to your task scenarios, create online experience tasks for models, and test the response effect of the models online.',
    modelEvaluateTips: 'Evaluate the performance of the user fine-tuning generated model using the dataset provided by OpenCompass as the testing standard.',
    largeModelsList: 'Large models List',
    newModelExperience: 'New Model Experience Task',
    ModelExperienceDetail: 'Model Experience Task Details',
    ModelEvaluateDetail: 'Model Evaluation Task Details',
    modelEvaluate: 'Model evaluation',
    modelPerEvaluate: 'Model performance evaluation',
    modelSafeEvaluate: 'Model security evaluation',
    modelEvaluateTask: 'Model Performance Evaluation Task',
    evaluationModel: 'Evaluation Model',
    sftFinetune: 'NLP Finetune',
    sftFinetuneTask: 'NLP Finetune Task',
    newSftFinetune: 'Create NLP Finetune task',
    newLoraFinetune: 'Create CV Finetune task',
    newComfyUi: 'Create Comfy UI task',
    sftFinetuneDetail: 'Details of NLP Finetune task',
    sftFinetuneLimit: 'Each account can create 3 NLP Finetune tasks simultaneously',
    ModelExperienceLimit: 'Each account can create 3 Online Experience tasks simultaneously',
    ModelEvaluateLimit: 'Each account can create 1 Evaluation tasks simultaneously',
    sdLoraLimit: 'Each account can create 3 CV Finetune tasks simultaneously',
    comfyuiLimit: 'Each account can create 1 Comfy UI task simultaneously',
    sftFinetuneTips: 'At present, LoRA (Low Rank Adaptation) training mode is provided, which allows you to choose suitable training data and adjust training parameters according to your own task scenario, thereby achieving ideal model performance.',
    cvloraTips: 'LoRA is a lightweight model tuning method that trains specific network layer weights and inserts them into the base model to achieve fast, efficient, and minimal image training, ultimately optimizing the model parameter count and inference performance',
    ComfyUiTips: 'Comfy UI is a node-based graphical user interface (GUI) for Stable Diffusion, primarily designed to build highly flexible image generation workflows. It caters to diverse user groups, including digital artists, AI researchers, content creators, and more.',
    ComfyUiWarn: 'The service is starting up, please try again later!',
    uploadSound: 'Please upload a sound template',
    language: 'Language: ',
    soundStyle: 'Sound style: ',
    systemDefault: 'system Default',
    uploadSound1: 'upload sound template',
    dragDrop: 'Drag and drop audio to this location',
    outputAduio: 'output Aduio',
    appDev: 'Application Development',
    relatedTools: 'Related Tool Systems',
    inputLength: 'Input characters exceed the limit',
    ttsPlaceholder: 'Please input the text to be converted into speech, The Chinese and English speech synthesis should not exceed 82 and 250 characters respectively (Ctrl+Enter=line break, press Enter to submit)',
    soundTemplateTips: 'The sound template only supports MP3 and WAV format files',
    soundTemplateTips1: 'The sound template only supports a single file',
    soundTemplateTips3: 'Currently, only MP3 and WAV audio files are supported for uploading sound templates, and only a single file is supported',
    cvLoraTrain: 'CV Finetune',
    cvComfyui: 'Comfy UI',
    cvComfyuiTask: 'Comfy UI Task',
    modelArena: 'Model Arena',
    send: 'Send',
    newRound: 'New Round',
    pleaseSelectModelAndConversation: 'Select Model and Start Conversation',
    model_name: 'English name of model',
    model_zh_name: 'Chinese name of model',
  },
  modelFinetune: {
    foldParameters: 'Fold Parameters',
    expandParameters: 'Expand Parameters',
    epochs: 'Total number of training epochs to perform',
    learningRate: 'Initial learning rate for AdamW',
    batchSize: 'Number of samples processed on each GPU',
    valSize: 'Proportion of data in the dev set',
    evalSteps: 'Number of steps should be taken for verification',
    saveSteps: 'Number of steps between two checkpoints',
    maxsamples: 'Maximum samples per dataset',
    computeType: 'Whether to use mixed precision training',
    gradientAccumulation: 'Number of steps for gradient accumulation',
    lrScheduler: 'Name of the learning rate scheduler',
    maximumGradientNorm: 'Norm for gradient clipping',
    cutoffLen: 'Max tokens in input sequence',
    preprocessingNumWorkers: 'Number of processes used for processing',
    loggingSteps: 'Number of steps between two logs',
    warmupSteps: 'Number of steps used for warmup',
    packing: 'Pack sequences into samples of fixed length',
    optim: 'The optimizer to use: adamw_torch, adamw_8bit or adafactor',
    loraRank: 'The rank of LoRA matrices',
    loraAlpha: 'Lora scaling coefficient',
    loraDropout: 'Dropout ratio of LoRA weights',
    loraTarget: 'Name(s) of modules to apply LoRA. Use commas to separate multiple modules',
    additionalTarget: 'Name(s) of modules apart from LoRA layers to be set as trainable. Use commas to separate multiple modules',
    maxTaskTips: '<p><span>*</span>The platform only retains the results of finetune tasks for nearly<span> 30 </span> days. <span>Tasks over 30 days will not be able to download results and view logs, and cannot be finetune again</span></p>',
    maxEvalTaskTips: '<p><span>*</span>The platform only retains the results of evaluate tasks for nearly<span> 30 </span> days. <span>Tasks over 30 days will not be able to view results and logs</span></p>',
    max_epoch: 'Epoch',
    max_epoch_tips: 'Iteration rounds, control the number of iterations during the training process.',
    io_strategy: 'Model strategy',
    io_strategy_tips: '--',
    keep_interval_update: 'Checkpoint save interval',
    keep_interval_update_tips: '--',
    save_interval_update: 'Number of saved iteration steps',
    save_interval_update_tips: 'Every how many steps, save',
    lr: 'Learning rate',
    lr_tips: '--',
    vitual_pipeline_model_parallel_size: 'Virtual pipeline parallelism',
    vitual_pipeline_model_parallel_size_tips: '--',
    pipeline_model_parallel_size: 'Pipeline ',
    pipeline_model_parallel_size_tips: 'Pipeline parallelism, splitting the model according to the hierarchy of neurons, and placing different layers on different GPUs for computation',
    tensor_model_parallel_size: 'Tensor parallelism',
    tensor_model_parallel_size_tips: 'Tensor parallelism, which means combining multiple GPUs to perform tensor calculations simultaneously, such as matrix multiplication',
    num_micro_batch: 'Num micro batch',
    num_micro_batch_tips: 'The range of values for the number of micro batches is [1,32], which represents the accumulated number of micro batches in each training iteration. Setting a large number of micro batches can accelerate training, but it may cause memory issues',
    micro_batch_size: 'Micro batch size',
    micro_batch_size_tips: 'If it can only be 1 or 2, it will exceed the video memory and use gradient accumulation instead',
    recomputer_granularity: 'Recomputer granularity',
    recomputer_granularity_tips: 'Choosing to enable recalculation of compressible video memory usage may result in a decrease in throughput. It is recommended to close it if there is enough video memory available',
    modelTraining: 'model Training',
    modelTesting: 'model Testing',
    trainStart: 'started training',
    imageLabeling: 'image Captioning',
    totalPic: 'Total',
    numPic: 'pictures',
    clearAllPic: 'Clear all images',
    addPic: 'Add picture',
    captionMethod: 'captioning algorithm',
    captionthres: 'captioning threshold',
    modelTrigger: 'Model trigger word',
    modelTriggerph: 'Please enter the trigger word',
    captioning: 'Captioning',
    imgUploading: 'Picture uploading in progress',
    sureClearAllPic: 'Do you want to delete all images?',
    sureClearOnePic: 'Do you want to delete this image',
    clearAllPicSucc: 'All images have been successfully deleted',
    clearAllPicFail: 'Failed to delete all images',
    clearOnePicSucc: 'Image deleted successfully',
    clearOnePicFail: 'Image deletion failed',
    autoCaption: 'Automatically captioning images...',
    trainProgress: 'Training progress',
    currentSteps: 'Current Steps/Total Steps',
    trainingRounds: 'Training epochs/total epochs',
    trainParameters: 'Training parameters',
    viewLoss: 'View Loss',
    selected: 'Selected',
    startGenerateImg: 'Start generating images',
    sampleImage: 'Real time sample image',
    sampleImageGenerate: 'Sample image generation in progress',
    trainProcessing: 'During data processing and model loading...',
    trainingProgress: 'Training in progress',
    trainingCompleted: 'Training completed',
    loraModelName: 'LoRA model',
    picWidth: 'Width',
    picHeight: 'Height',
    loraRandomSeed: 'Random Seed',
    loraSamplingSteps: 'Sampling Steps',
    loraCFGScale: 'CFG Scale',
    loraNegativePrompt: 'Negative Prompt',
    loraInputPrompt: 'Please enter prompt!',
    capationAddPic: 'Add tags to all images',
    capationAddBegin: 'Add begin of the line',
    capationAddEnd: 'Add end of the line',
    capationAddMsg: 'Label input cannot be empty!',
    ProfessionalParameters: 'Professional Parameters',
    useBasicModel: 'Basic Model',
    Repeat: 'Repeat',
    Epoch: 'Epoch',
    totalSteps: 'total Steps',
    uploadImgCalc: 'Calculate after uploading the image',
    Prompt: 'Prompt',
    ProfessionalSetting: 'Professional Setting',
    loraPromptPlace: 'During the training process, real-time sample images will be generated based on prompt words',
    uploadImg: 'upload Images',
    uploadImgAccept: 'The file format does not meet the requirements. Please upload. jpg JPEG,. png format files',
    dragUploadImg: 'Drag and drop the image here to upload',
    uploadMaxImg: 'Add up to 200 images, supporting PNG/JPG/JPEG',
    uploadHavedImg: 'Upload existing image collection',
    uploadImgTips: 'Please ensure that the images correspond one-to-one with the marked files. The zip package cannot contain multi-level directories, and the total number of characters in the zip package name and file name should be less than 255',
    uploadImgTips1: 'File not detected',
    uploadImgTips2: 'The current maximum allowed upload is 200 image files',
    uploadImgTips3: 'The file format does not meet the requirements. Please upload an image in PNG/JPG/JPEG format',
    cvTaskfaildTips: 'The task has stopped or failed. Please recreate the task!',
    evalDatasetLimit: 'Evaluate the number of datasets',
    sftFinetuneName: 'fine-tuning task name',
    selectBaseModel: 'Select the basic model',
    selectFtModel: 'Select NLP fine-tuning model',
    evalTips: 'The model capability evaluation is based on the dataset provided by OpenCompass as the testing standard, for reference only.',
    evalTaskCategory: 'Task category',
    evalScore: 'Score',
    evalModelInput: 'Model input',
    evalModelOutput: 'Model output results',
    standerAnswer: 'Standard answer',
    evalModelOutAnswer: 'Model output answer',
    allResult: 'All result',
    correctResult: 'Correct result',
    wrongResult: 'Wrong result',
    allDataset: 'All Datasets'
  },
  userRole: {
    userRoleManagement: 'User role management',
    newOpRole: 'Create a new operational role',
    editOpRole: 'Edit operational role',
    viewOpRole: 'View operational role',
    newReRole: 'Create a new role for computing resources',
    editReRole: 'Edit computing power resources role',
    viewReRole: 'View computing resource roles',
    newStorageRole: 'Create a new storage resource role',
    editStorageRole: 'Edit storage resource role',
    viewStorageRole: 'View storage resource role',
    newContainerStorageRole: 'Create a new container storage quota role',
    editContainerStorageRole: 'Edit container storage quota role',
    viewContainerStorageRole: 'View container storage quota role',
    roleName: 'Role name',
    roleType: 'Role type',
    roleDescription: 'Role description',
    isItDefault: 'Is it default',
    viewDetail: 'View detail',
    default: 'Default',
    notDefault: 'Not default',
    reCategory: 'Computing resources type',
    opCategory: 'Operational type',
    storageCategory: 'Storage resource type',
    allRoleType: 'All role type',
    deleteRoleConfirm: 'Deleting the default role will affect all users.',
    deleteRoleConfirm1: 'Are you sure you want to delete the current {name} role?',
    roleSelected: 'Please specify the permissions that the role has (multiple choices are allowed)',
    roleSelectedTips: 'Select All/Select None',
    allUserDefault: 'All user default',
    UserPermissionConfig: 'User permission configuration',
    OrgPermissionConfig: 'Organization permission configuration',
    allOpCategory: 'All operational roles',
    allReCategory: 'All computing power resource roles',
    allStCategory: 'All storage resource roles',
    userName: 'User name',
    OrganizationName: 'Organization name',
    opCategoryRole: 'Operational roles',
    reCategoryRole: 'Computing resource roles',
    stCategoryRole: 'Storage resource roles',
    codeSizeLimit: 'Code directory size limit',
    outputSizeLimit: 'Output directory size limit',
    pleaseEnterContent: 'Please enter the content',
    pleaseEnterRoleContent: 'Please enter the role name to search...',
    userId: 'User ID',
    organizationId: 'Organization ID',
    editUserPermissions: 'Edit user permissions',
    editOrgPermissions: 'Edit organization permissions',
    OperationalPermissions: 'Operational permissions',
    detail: 'Detail',
    permissionList: 'Permission List',
    updatePermissions: 'Update permissions',
    resourcePermissions: 'computing resource permission list',
    CResourcePermissions: 'Computing resource permissions',
    StoragePermissions: 'Storage resource permissions',
    permissionUpdateUnixDesc: 'Descending by user permission update time',
    permissionUpdateUnixAsc: 'Ascending by user update time',
    permissionCreatedUnixDesc: 'Descending by user creation time ',
    permissionCreatedUnixAsc: 'Ascending by user creation time ',
    orgPermissionCreatedUnixDesc: 'Descending by organization creation time ',
    orgPermissionCreatedUnixAsc: 'Ascending by organization creation time ',
    batchSetOrCancel: 'Batch setting or canceling user roles',
    enterUserId: 'Please enter the list of users who need to set permissions',
    failed: 'Failed',
    times: 'times',
    failedUserList: 'Failed user list',
    addAcessSuccess: 'Add access successfully',
    cancelAcessSuccess: 'Access cancelled successfully',
    operaNodeTips1: 'When running training tasks can use',
    operaNodeTips2: '-node',
    operaNodeTips3: 'computing resources',
    operaTaskTips1: 'Can run simultaneously',
    operaTaskTips2: 'task',
  },
  org: {
    organization: 'Organization',
    createOrg: 'Create organization',
    searchOrg: 'Search organization',
    orgName: 'Organization name',
    orgFullName: 'Full organization name',
    Members: 'Members',
    Teams: 'Teams',
    orgTeam: 'Teams',
    orgMember: 'People',
    numMember: 'member',
    numMembers: 'members',
    numRepo: 'repository',
    numRepos: 'repositories',
    unfold: 'Unfold',
    fold: 'Fold',
    searchRepos: 'Search Repositories',
    searchModels: 'Search Models',
    searchDatasets: 'Search Datasets',
    searchImages: 'Search Images',
    customize: 'Customize',
    selectedProjects: 'Selected Projects',
    selectedModels: 'Selected Models',
    selectedDatasets: 'Selected Datasets',
    customizeSelectedProjects: 'Customize selected projects',
    customizeSelectedModels: 'Customize selected models',
    customizeSelectedDatasets: 'Customize selected datasets',
    searching: 'Search...',
    remainNum: 'Remain: {num}',
    maxProjects: 'Select up to {num} public projects',
    maxModels: 'Select up to {num} public models',
    maxDatasets: 'Select up to {num} public datasets',
    order_newest: 'Newest',
    order_oldest: 'Oldest',
    order_recentupdate: 'Recently updated',
    order_leastupdate: 'Least recently updated',
    order_reversealphabetically: 'Reverse alphabetically',
    order_alphabetically: 'Alphabetically',
    order_moststars: 'Most stars',
    order_feweststars: 'Fewest stars',
    order_mostforks: 'Most forks',
    order_fewestforks: 'Fewest forks',
    no_result: 'No Data',
    myOrg: 'My Organization',
    orgDataset: 'Organization Datasets',
    orgModel: 'Organization Models',
  },
  storage: {
    capacity_details: 'Storage Capacity Details',
    quota: 'Storage Quota',
    data_usaged: 'Dataset Used',
    model_usaged: 'Model Used',
    remaining_available: 'Free Space',
    upload_time: 'Upload time',
    deleteModelConfirm: 'Are you sure to delete the current model <span style="color:red;">{name}</span> ？',
    deleteModelConSuccess: 'Successfully deleted the current model {name}!',
    deleteDataSetConfirm: 'Are you sure to delete the current dataset  <span style="color:red;">{name}</span> ？',
    deleteDataSetSuccess: 'Successfully deleted the current dataset {name}!',
    feedback_issue: 'Feedback issue',
    remain_storage: 'Remaining storage quota',
    selected_file_size: 'Selected file size',
    exceedStorage: 'Exceeded storage limit',
    deleteBatchData: 'Are you sure to delete the datasets selected in bulk? Once deleted, it cannot be restored',
    deleteBatchModel: 'Are you sure to delete the models selected in bulk? Once deleted, it cannot be restored',
    deletingTips: 'Files deletion in progress, please wait',
    OwenerTips: 'Please check the storage capacity details of {ownerName}',
    storageOrgTips1: 'To apply for more quotas, please click',
    storageOrgTips2: 'to download the template',
    storageOrgTips3: 'fill it out and send it to the email secretariat@openi.org.cn',
  },
  evalCaterary: {
    Examination: "Examination",
    Reasoning: "Reasoning",
    Knowledge: "Knowledge",
    Code: "Code",
    Math: "Math",
    Understanding: "Understanding",
    Language: "Language",
    Instruct: "Instruct",
  },
  thirdPartyApp: {
    thirdPartyApp: 'Third-party Application',
    oauth2App: 'OAuth2 Application',
    oauth2AppDescr: '(Verified OAuth2 application, after user authorization, the application can obtain the user\'s basic information (user ID, username, user avatar link), email, and phone number)',
    authStatus: 'Verify Status',
    canGetUserInfo: 'Authorized User Information',
    searchThirdPartyAppPlaceholder: 'Search for third-party application name',
    clientID: 'Client ID',
    appName: 'Application Name',
    appCanGetUserInfo: 'Authorized User Information',
    appCreator: 'Creator',
    authenticated: 'Verified',
    notAuthenticated: 'Not Verified',
    setAuthenticated: 'Set Verification',
    cancelAuthentication: 'Cancel Verification',
    basicInfo: 'Basic information',
    basicInfoAll: 'Basic information (user ID, username, user avatar link)',
    email: 'Email',
    phoneNumber: 'Phone number',
    editOauth2AppAuthInfo: 'Edit OAuth2 application authentication information',
    authenticatedCanGetInfoTips: 'After user authorization, the application can obtain the following user information',
    verify: 'Verify',
    cancelVerify: 'Cancel Verify',
    verifyAgain: 'Verify Again',
    cancelVerifyTips: 'After canceling verify, the application will only be able to obtain basic user information and will not be able to obtain the user\'s email or phone number. Do you want to continue?',
  },
  computingPowerObj: {
    computeResource: 'Compute Resources',
    computeResourceDescr: 'In order to meet the personalized computing power needs of users, OpenI Community can customize computing power pools according to their needs. Welcome to submit your computing power requirements.',
    freeComputingPower: 'Free Compute',
    paidComputingPower: 'Paid Compute',
    paidComputingPowerTip: 'Paid computing power and after-sales service provided by partners',
    createNewComputingTask: 'Create New Computing Task',
    createComputingTask: 'Create Computing Task',
    displayFilteringConditions: 'Display Filtering Conditions',
    priceRange: 'Price Range',
    point_hr: 'Point/hr',
    use: 'Ues Now',
    buyNow: 'Buy Now',
    provider: 'Provider',
    systemDisk: 'Dystem Disk',
    computingPowerPartner: 'Compute Partner',
    computingPowerOperationPlatform: 'Compute Platform',
    chipManufacturers: 'Chip Manufacturers',
    accCardCount: 'Acc Card Count',
  },
  dashboard: {
    welcomeTips: 'Welcome to CacOps',
    newUserGuide: 'New User Guide',
    quickAccess: 'Quick Access',
    createTask: 'Create computing task',
    taskDesc: 'Use computing cards to create tasks such as debugging, training, and inference.',
    myTaskCount: 'My computing tasks',
    runningTasks: 'Running',
    totalGPUHourd: 'Cumulative Runtime',
    createProject: 'Create repository',
    createRepoDesc: 'Create a code repository and use the code in computing tasks.',
    uploadDatasetDesc: 'Upload datasets and use them in computing tasks.',
    uploadModelDesc: 'Upload AI models and use them in computing tasks.',
    oneClickCreate: 'One-Click Creation',
    remainingQuota: 'Remaining Available Storage Quota',
    occupiedStorage: 'Occupied Storage',
    datasetStorage: 'Dataset Occupancy',
    modelStorage: 'Dataset Occupancy',
    credits: 'Calculation Points',
    currentAvailable: 'Current Available Calculation Points',
    currentAvailable1: 'Current Available',
    totalGained: 'Total Gained Calculation Points',
    totalGained1: 'Total Gained',
    totalConsumed: 'Total Consumed Calculation Points',
    totalConsumed1: 'Total Consumed',
    announcements: 'Announcements',
    moreAnnouncements: 'More Announcements',
    activities: 'Events',
    weChatLinked: 'WeChat Account Linked',
    weChatNotLinked: 'WeChat Account Not Linked',
    datasetNum: 'Datasets',
    modelNum: 'Models',
    unitPoints: '',
    unitTask: '',
    unitdata: '',
    runtimeCards: '',
    templateNum: 'Total templates',
    accumulatedRuns: 'Total runs',
    unitTemplate: '',
    heatmapLoading: 'Loading Heatmap…',
    contributionCount: 'contributions in the last 12 months：{count} times'
  },
  agentPortal: {
    taskRunningTip: 'You have {count} agents running, consuming {numPoint} points/hour',
    viewRunningAgents: 'View running agents',
    bannerTitle: 'Start Your AI Agent Journey',
    bannerDesc: 'Based on the powerful computing power of China Computing Network, deploy cutting-edge large model capabilities with one click to experience AI charm anytime, anywhere.',
    searchPlaceholder: 'Search agents',
    agentSquare: 'Agent Square',
    runningAgents: 'Running Agents',
    viewDetails: 'View Details',
    oneClickDeploy: 'One-click Deploy',
    deployFailed: 'Running Failed',
    deploying: 'Deploying',
    stop: 'Stop',
    startUsing: 'Start Using',
    startSuccess: 'Started Successfully',
    startFailed: 'Start Failed',
    stopSuccess: 'Stopped Successfully',
    stopFailed: 'Stop Failed',
    agentsRunning: 'Agent {names} is running',
    updated: 'Updated',
    noData: 'No Data',
  }
}

export default en;
