const zh = {
  loading: "加载中...",
  noData: "暂无数据",
  noMessage: "暂无信息",
  date: "日期",
  noDataset: "空荡荡的，什么都没有",
  confirm: "确定",
  cancel: "取消",
  confirm1: "确认",
  confirmOp: "确认操作",
  cancelOp: "取消操作",
  enterReason: "请输入原因",
  clear: "清除",
  none: "无",
  pleaseCompleteTheInformationFirst: "请先完善信息！",
  submittedSuccessfully: "提交成功！",
  submittedFailed: "提交失败！",
  operation: "操作",
  edit: "修改",
  delete: "删除",
  tips: "提示",
  expandMore: '展开更多',
  goBack: '返回上一级',
  star: '收藏',
  unStar: '取消收藏',
  submit: '提交',
  selectAll: '全选',
  selectNone: '全不选',
  copy: '复制',
  copySuccess: '复制成功',
  copyLink: '复制链接',
  copyedLink: '已复制链接',
  downloadAddress: '下载地址',
  operationFailed: '操作失败',
  cancelOperate: '您已取消操作',

  accomplishTask: "积分任务",
  adminOperate: "管理员操作",
  runCloudBrainTask: "运行计算任务",
  operating: "消耗中",
  succeeded: "已完成",
  debugTask: "调试任务",
  trainTask: "训练任务",
  trainDuration: "训练时长",
  inferenceTask: "推理任务",
  benchmarkTask: "评测任务",
  onlineinfer: "在线推理",
  onlineinferTask: "在线推理任务",
  consoleHome: "控制台",
  superComputeTask: "超算任务",
  generalTask: "通用任务",
  createPublicProject: "创建公开项目",
  dailyPutforwardTasks: "每日提出任务",
  dailyPR: "每日提出PR",
  comment: "发表评论",
  uploadDatasetFile: "上传数据集文件",
  importNewModel: "导入新模型",
  completeWechatCodeScanningVerification: "完成微信扫码验证",
  dailyRunCloudbrainTasks: "每日运行计算任务",
  datasetRecommendedByThePlatform: "数据集被平台推荐",
  aimodelRecommendedByThePlatform: "模型被平台推荐",
  dailyCreateDataset: "创建了数据集",
  dailyCreateDataset1: "创建了数据集",
  dailyCreateAimodel: "创建了模型",
  dailyCreateAimodel1: "创建了模型",
  submitNewPublicImage: "提交新公开镜像",
  imageRecommendedByThePlatform: "镜像被平台推荐",
  firstChangeofAvatar: "首次更换头像",
  dailyCommit: "每日commit",
  calcPointDetails: "算力积分明细",
  calcPointAcquisitionInstructions: "积分获取说明",
  CurrAvailableCalcPoints: "当前可用算力积分(分)",
  totalGainCalcPoints: "总获取算力积分(分)",
  totalConsumeCalcPoints: "总消耗算力积分(分)",
  gainDetail: "获取明细",
  consumeDetail: "消耗明细",
  serialNumber: "流水号",
  time: "时间",
  scene: "场景",
  behaviorOfPoint: "积分行为",
  explanation: "说明",
  points: "积分",
  status: "状态",
  runTime: "运行时长",
  taskName: "任务名称",

  createdRepository: "创建了项目",
  repositoryWasDel: "项目已删除",
  userWasDel: "用户已删除",
  userAccountWasDel: "用户账号已注销",
  openedIssue: "创建了任务",
  createdPullRequest: "创建了合并请求",
  commentedOnIssue: "评论了任务",
  uploadDataset: "上传了数据集文件",
  createdNewModel: "导入了新模型",
  invitedFriend: "邀请了好友",
  firstBindingWechatRewards: "首次绑定微信奖励",
  created: "创建了",
  type: "类型",
  dataset: "数据集",
  setAsRecommendedDataset: "被设置为推荐数据集",
  setAsRecommendedAimodel: "被设置为推荐模型",
  committedImage: "提交了镜像",
  image: "镜像",
  setAsRecommendedImage: "被设置为推荐镜像",
  updatedAvatar: "更新了头像",
  pushedBranch: "推送了{branch}分支代码到",
  deleteBranch: "从{repo}删除分支{branch}",
  pushedTag: "推送了标签{tag}到",
  deleteTag: "从{repo}删除了标签{tag}",
  dailyMaxTips: "达到每日上限积分，不能拿满分",
  memory: "内存",
  sharedMemory: "共享内存",
  ";": "；",

  noPointGainRecord: "还没有积分获取记录",
  noPointConsumeRecord: "还没有积分消耗记录",
  consumeDescr: '说明：从2024年10月下旬开始，计算任务扣费周期有调整，具体的计费规则请参考联机帮助中“<a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/quickstart/resources?id=%e8%ae%a1%e8%b4%b9%e8%a7%84%e5%88%99">平台算力资源与积分说明</a>”页面的“计费规则”章节。',

  emptyPage: '您的访问受限！',
  emptyPageDescr: '您正尝试访问的页面 <strong>不存在</strong> 或 <strong>您尚未被授权</strong> 查看该页面。',
  handleTask: '处理任务',
  freeCompute: '普惠算力',
  repoPathTips: '路径只允许字母、数字和-_ .，最多100个字符。',
  useInPcWeb: '为获得更好的使用体验，请在PC端打开此页面。',
  acknowledgementsTips: {
    main1: '如果启智社区对您的科研工作提供了帮助，请在论文中给我们添加致谢（',
    main2: '）。',
    moreContent: '更多内容',
    p1: `英文版：Thanks for the support provided by OpenI Community (<a href="https://openi.pcl.ac.cn" target="_blank">https://openi.pcl.ac.cn</a>).`,
    p2: `中文版：感谢启智社区提供的技术支持(<a href="https://openi.pcl.ac.cn" target="_blank">https://openi.pcl.ac.cn</a>)。`,
    p3: `如果您的成果中引用了本平台，也欢迎在下述开源项目中提交您的成果信息：`,
    p4: `<a href="https://openi.pcl.ac.cn/OpenIOSSG/references" target="_blank">https://openi.pcl.ac.cn/OpenIOSSG/references</a>`,
  },
  computeResourceTitle: {
    CPU: 'CPU',
    VCPU: 'VCPU',
    'CPU/GPU': '英伟达GPU',
    GPU: '英伟达GPU',
    NPU: '昇腾NPU',
    GCU: '燧原GCU',
    MLU: '寒武纪MLU',
    DCU: '海光DCU',
    'ILUVATAR-GPGPU': '天数智芯GPGPU',
    'METAX-GPGPU': '沐曦GPGPU',
    'BIREN-GPU': '壁仞GPU',
  },
  TaskTypeTitle: {
    Notebook: '调试任务/在线推理',
    Notebook1: '调试任务',
    TrainJob: '训练任务',
    Ecs: '虚拟机',
    Inference: '推理任务',
    Service: '在线服务',
  },
  resourcesManagement: {
    OpenI: "启智集群",
    C2Net: "智算集群",
    IFLYTEKTraining: "讯飞集群",
    OpenIOne: "云脑一",
    OpenITwo: "云脑二",
    OpenIChengdu: "启智成都智算",
    chengduCenter: "成都智算",
    pclcci: "鹏城云计算所",
    hefeiCenter: "合肥类脑类脑智能开放平台",
    xuchangCenter: "中原人工智能计算中心",
    huoshi: "火石",
    willOnShelf: "待上架",
    onShelf: "已上架",
    offShelf: "已下架",
    toOnShelf: "上架",
    toOffShelf: "下架",
    toSetPriceAndOnShelf: "定价上架",
    status: "状态",
    reason: "原因",
    allStatus: "全部状态",
    syncAiNetwork: "同步智算网络",
    resQueue: "资源池（队列）",
    allResQueue: "全部资源池（队列）",
    addResQueue: "新建资源池（队列）",
    addResQueueBtn: "新增资源池",
    editResQueue: "修改资源池（队列）",
    resQueueCode: "资源池（队列）编码",
    resQueueName: "资源池（队列）名称",
    resQueueType: "资源池（队列）类型",
    resQueueIsAvailable: "资源池（队列）是否可用",
    resQueueIsAvailableAll: "资源池（队列）是否可用（全部）",
    allResQueueType: "全部资源池（队列）类型",
    whichCluster: "所属集群",
    allCluster: "全部集群",
    aiCenter: "智算中心",
    aiCenterID: "智算中心ID",
    allAiCenter: "全部智算中心",
    computeResource: "计算资源",
    allComputeResource: "全部计算资源",
    accCardType: "卡类型",
    allAccCardType: "全部卡类型",
    allNetworkType: "全部网络类型",
    cardsTotalNum: "卡数",
    accCardsNum: "卡数",
    allCardsNum: "全部卡数",
    remark: "备注",
    pleaseEnterRemark: "请输入备注(最大长度不超过255)",
    pleaseEnterPositiveIntegerCardsTotalNum: "请输入正整数的卡数！",
    addResSpecificationAndPriceInfo: "新增资源规格和单价信息",
    addResSpecificationBtn: "新增资源规格",
    editResSpecificationAndPriceInfo: "修改资源规格和单价信息",
    resSpecificationAndPriceManagement: "资源规格管理",
    sourceSpecCode: "对应资源编码",
    sourceSpecCodeTips: "云脑II需要填写对应的资源编码",
    sourceSpecId: "智算网络资源规格ID",
    cpuNum: "CPU数",
    gpuMem: "显存",
    mem: "内存",
    shareMem: "共享内存",
    unitPrice: "单价",
    point_hr: "积分/时",
    ShelfReason: "上架原因",
    node: "节点",
    free: "免费",
    onShelfConfirm: "请确认上架该规格？",
    offShelfConfirm: "请确认下架该规格？",
    onShelfCode1001: "上架失败，资源池（队列）不可用。",
    onShelfCode1003: "上架失败，资源规格不可用。",
    offShelfDlgTip1: "当前资源规格已在以下角色中被使用：",
    offShelfDlgTip2: "请确认进行下架操作？",
    characterLengthPrompt: "请输入不超过255个字符",
    resSceneManagement: "算力资源应用场景管理",
    addResScene: "新建算力资源应用场景",
    addResSceneBtn: "新增应用场景",
    editResScene: "修改算力资源应用场景",
    resSceneName: "应用场景名称",
    jobType: "任务类型",
    allJobType: "全部任务类型",
    allJobStatus: "全部任务状态",
    sceneType: "社区资源性质",
    allSceneType: "全部社区资源性质",
    isExclusiveSpec: "是否专属资源规格",
    allExclusiveAndCommonUseSpec: "全部专属和通用资源规格",
    public: "共享(public)",
    exclusive: "独占(exclusive)",
    exclusiveTxt: "独占",
    exclusiveSpec: "专属资源规格",
    commonUseSpec: "通用资源规格",
    exclusiveOrg: "专属组织",
    exclusiveOrgTips: "多个组织名之间用英文分号隔开",
    computeCluster: "算力集群",
    resourceSpecification: "资源规格",
    lastUpdateTime: "最后更新时间",
    resSceneDeleteConfirm: "是否确认删除当前应用场景？",
    resourceSpecificationIsAvailable: "资源规格是否可用",
    resourceSpecificationIsAvailableAll: "资源规格是否可用（全部）",
    available: "可用",
    notAvailable: "不可用",
    selectSpec: '选择资源规格',
    accordingSpec: '按资源规格',
    accordingQueue: '按资源池队列',
    accordingSelect: '按已勾选',
    allIsEnableVisualization: '是否支持可视化（全部）',
    notEnable: '不支持',
    enable: '支持',
    roleNameTips: '最长输入80个字符',
    roleDescTips: '最长输入800个字符'
  },
  logManagement: {
    operationLog: "操作日志",
    allOperationType: "全部操作类型",
    resourceSpecificationOnshelf: '资源规格上架',
    resourceSpecificationEdit: '资源规格修改',
    resourceSpecificationOffshelf: '资源规格下架',
    resourceSpecificationAddition: '新增资源规格',
    resourceSpecificationAutoUpdate: '资源规格是否可用状态变化',
    operationType: '操作类型',
    operationReason: '操作原因',
    operator: '操作者',
    operationTime: '操作时间',
  },
  user: {
    inviteFriends: "邀请好友",
    inviteFriendsTips: "复制二维码或者注册邀请链接分享给好友",
    clickToViewTheEventDetails: "点击查看活动详情",
    copyRegistrationInvitationLink: "复制注册邀请链接",
    registrationAdress: "注册地址：",
    recommender: "推荐人：",
    invitedFriends: "已邀请好友",
    registrationTime: "注册时间",
    theSharedContentHasBeenCopiedToTheClipboard: "分享内容已复制到剪切板",
    copyError: "复制错误",
    Activated: "已激活",
    notActive: "未激活",
    normal: '正常',
  },
  notebook: {
    createNewNotebook: "新建Notebook调试任务",
    sameTaskTips1: "您已经有",
    sameTaskTips2: "同类任务",
    sameTaskTips3: "正在等待或运行中，请等待任务结束再创建",
    sameTaskTips4: "可以在",
    sameTaskTips5: "我的工作台",
    sameTaskTips6: "计算任务",
    sameTaskTips7: "查看您所有的计算任务。",
    cpuEnv: "CPU 环境",
    gpuEnv: "GPU 环境",
    npuEnv: "NPU 环境",
    newTask: "新建任务",
    noQuene: "当前资源充足，没有任务排队",
    queneTips1: "您当前排队位置是第",
    queneTips2: "位",
    watiResource: "正在等待分配资源，请耐心等待",
    debug: "调试",
    stop: "停止",
    stopping: "停止中",
    notebookRunning: "调试环境已启动，单次连接 4 小时后自动关闭",
    stopSuccess: "停止任务成功",
    specification: "规格",
    graphicMemory: "显存",
    memory: "内存",
    sharedMemory: "共享内存",
    tips: '本次新建的调试任务会放在您名下项目openi-notebook中，如果没有该项目系统会自动新建一个。',
    balanceOfPoints: '积分余额：',
    points: '积分',
    hours: '小时',
    expected_time: '，预计可用',
    limitTitle: '{type}数量已达上限',
    limitReason: '当前账号最多创建{count}个和同时运行{runCount}个调试任务，请停止运行中的任务并删除部分历史任务后提交新任务',
    stopReason: '当前账号已有{count}个正在等待或运行的任务，请停止后再提交新任务',
    deleteReason: '当前账号最多创建{count}个{type}，请删除历史任务后提交新任务',
    stopSuccess: '停止任务成功',
    stopFailed: '停止任务失败',
    deleteSuccess: '删除任务成功',
    deleteFailed: '删除任务失败',
    handleSuccess: '操作成功，请继续创建任务',
  },
  tranformImageFailed: '图片脱敏失败',
  originPicture: '原始图片',
  desensitizationPicture: '脱敏图片',
  desensitizationObject: '脱敏对象',
  example: '示例',
  startDesensitization: '开始处理',
  all: '全部',
  others: '其它',
  onlyFace: '仅人脸',
  onlyLicensePlate: '仅车牌',
  dragThePictureHere: '拖动图片到这里',
  or: '或',
  clickUpload: '点击上传',
  dataDesensitizationModelExperience: '数据脱敏模型体验',
  dataDesensitizationModelDesc: '利用人工智能AI技术，把图片中的人脸、车牌号码进行脱敏处理。该模型更多信息请访问项目',
  limitFilesUpload: '只能上传 jpg/jpeg/png 格式的文件',
  limitSizeUpload: '上传文件大小不能超过 20M !',
  bootPlaceholder: '请输入启动文件',
  modelManage: {
    modelManage: '模型管理',
    modelName: '模型名称',
    useCluster: '可用集群',
    license: '许可证',
    selectLicense: '选择许可证',
    local: '本地',
    online: '线上',
    external: '外部',
    createModel: '创建模型',
    importLocalModel: '导入本地模型',
    importOnlineModel: '导入线上模型',
    importFrom: '从哪里导入',
    createNewModel: '新建模型',
    localModelTips: '将本地存放的模型文件导入至启智AI协作平台',
    onlineModelTips1: '将训练任务输出的模型导入至模型管理中。导入线上模型需先',
    onlineModelTips2: '创建训练任务',
    nextSteps: '下一步',
    back: '上一步',
    step1: '选择导入类型和项目',
    step2: '设置模型信息',
    step3: '上传模型文件',
    project: '所属项目',
    newRepoPath: '新项目路径',
    modelInfo: '模型信息',
    modelBriefIntro: '模型简介',
    trainingInfo: '训练相关信息',
    modifyModelInfo: '修改模型信息',
    modelList: '模型列表',
    modelFiles: '模型文件',
    addModelFiles: '增加模型文件',
    uploadModelFiles: '上传模型文件',
    pleaseInputModelName: '请输入模型名称',
    version: '版本',
    modelVersion: '模型版本',
    modelEngine: '模型框架',
    modelLabel: '模型标签',
    externalToken: '外部Token ',
    modelSource: '模型来源',
    modelLabelInputTips: '输入标签，多个标签用空格区分',
    modelLabelGatedTips: '迁移Gated的模型文件需要输入HuggingFace的Token',
    modelDescr: '模型描述',
    modelDescrInputTips: '描述字数不超过255个字符',
    confirm: '确定',
    cancel: '取消',
    modelCreateFailed: '模型创建失败',
    modelModifyFailed: '模型修改失败',
    fileUpload: '文件上传',
    folderUpload: '文件夹上传',
    upload: '上传',
    uploadPath: '上传路径',
    uploadStatus: '上传状态',
    modelFileUploadDefaultTips: '点击添加文件或直接拖拽文件到此处',
    modelFileUploadErrTips: '文件名不超过128个字符，单次最多上传 {maxCount} 个文件，单个文件超过{size}请使用<a target="_blank" href="{url}" style="cursor: pointer;">SDK上传</a></a>, 文件数量较多时，建议压缩后再上传',
    modelFileNameTips: '文件名长度不超过128个字符',
    modelFileNamSspaceTips: '文件名包含空格',
    fileIstoBig: '文件大小（{{filesize}} MiB）超过了最大允许大小（{{maxFilesize}} MiB）',
    removeFile: '移除文件',
    uploadSuccess: '上传成功',
    uploadFailed: '上传失败',
    calcFileMd5: '计算文件MD5...',
    uploading: '上传中...',
    fileHasAlreadyInTheModel: '该文件已上传在模型：',
    fileEqualInTheModel: '该文件与其它文件内容相同：',
    fileExistInTheModel: '已存在相同名称文件：',
    uploadFile: '上传文件',
    uploadFolder: '上传文件夹',
    addUploadFolder: '添加上传文件夹',
    clearAll: '清空所有',
    fileCountAndSize: '已选择文件数: {count}，总大小: {size}',
    folderUploadPlaceholder: '点击添加文件夹或直接拖拽文件夹/文件到此处',
    folderUploadTips: '本次上传的文件数量不超过 {maxCount} 个，总大小不超过 {maxSize}，超多超大的文件请通过 <a target="blank" href="https://openi.pcl.ac.cn/docs/index.html#/api/list">SDK</a> 方式上传。',
    folderUploadErrorTips: '本次上传的文件数量不超过 {maxCount} 个，单个文件超过 {maxSize}请使用<a target="_blank" href="{url}" style="cursor: pointer;">SDK上传</a>',
    basicInfo: '基本信息',
    modelSize: '模型大小',
    descr: '描述',
    createTime: '创建时间',
    label: '标签',
    trainTaskInfo: '训练相关信息',
    trainTask: '训练任务',
    codeBranch: '代码分支',
    bootFile: '启动文件',
    viewSamples: '查看样例',
    trainDataset: '训练数据集',
    datasetfile: '数据集文件',
    fileShort: '文件',
    specInfo: '规格',
    workServerNumber: '计算节点',
    runParameters: '运行参数',
    seeMore: '查看更多信息',
    collapseDetails: '折叠详细信息',
    modelFilesList: '模型文件列表',
    fileName: '文件名称',
    fileSize: '文件大小',
    updateTime: '更新时间',
    operate: '操作',
    download: '下载',
    delete: '删除',
    infoModificationFailed: '信息修改失败',
    deleteModelFileConfirmTips: '请确认是否删除当前模型文件？',
    modelFileDeleteFailed: '模型文件删除失败',
    modelAccess: '模型权限',
    modelAccessPublic: '公开',
    modelAccessPrivate: '私有',
    modelAccessTips: '公开项目才可以设置模型为公开',
    modelSettings: '模型信息设置',
    edit: '编辑',
    editFiles: '编辑文件',
    preview: '预览',
    modelIntroduction: '模型介绍',
    hasNoIntroForModel: '还没有详细的模型介绍',
    createModelIntro: '创建模型介绍',
    briefIntroduction: '简介',
    addLabels: '新增标签',
    discardFileChanges: '是否放弃当前内容修改？',
    editFileContentFirst: '请先编辑文件内容！',
    ownerRepository: '所属项目',
    creator: '创建者',
    migrator: '迁移者',
    useModel: '使用模型',
    modelEvolutionMap: '模型演化图谱',
    evolutionMap: '图谱',
    settings: '设置',
    parentModel: '父模型',
    currentModel: '当前模型',
    derivedModel: '衍生模型',
    publicDerivedModel: '公开衍生模型',
    privateDerivedModel: '私有衍生模型',
    refRepository: '引用项目',
    publicRefRepository: '公开引用项目',
    privateRefRepository: '私有引用项目',
    modelDownloadAll: '下载全部模型文件',
    otherOnline: '其他在线体验入口',
    trainUsedDataList: '和该模型一起使用过的数据集',
    trainUsedRepo: '和该模型一起使用过的代码',
    modelUseTaskList: '使用该模型的任务',
    forkModelSuccess: '模型内容复制完成，项目fork成功！',
    debugModel: '调试模型',
    onlineInference: '在线体验',
    onlineInferenceTask: '在线体验任务',
    onlineLoraTrain: '在线训练',
    onlineWorkflow: '在线工作流',
    deleted: '已删除',
    derivativeTimes: '衍生次数',
    derivativeTimes1: '衍生',
    mostDerivative: '最多衍生',
    modelBaseInfo: '模型基本信息',
    modelCollaborator: '模型协作者',
    managementTeam: '模型管理团队',
    add_team_success: '团队现在可以访问模型',
    remove_team_success: '团队访问模型的权限已被删除。',
    deletCollaboratedTips: '删除该协作者后，他将无法访问此模型，继续操作吗？',
    total_size: '总大小',
    total_size_asc: '总大小倒序'
  },
  repos: {
    activeOrganization: '活跃组织',
    activeUsers: '活跃用户',
    follow: '关注',
    unFollow: '取消关注',
    selectedFields: '领域精选',
    mostPopular: '近期热门',
    mostActive: '近期活跃',
    newest: '最近创建',
    recentlyUpdated: '最近更新',
    mostStars: '点赞最多',
    mostForks: '派生最多',
    mostDatasets: '数据集最多',
    mostAiTasks: 'AI任务最多',
    mostModels: '模型最多',
    repos: '项目',
    publicRepos: '公开项目',
    repoTopics: '项目领域',
    dataset: '数据集',
    model: '模型',
    aiTask: 'AI任务',
    updated: '最后更新于',
    contributors: '贡献者',
    searchRepositories: '搜项目...',
    search: '搜索',
    allFields: '全部领域',
    preferred: '项目优选',
    openIIncubation: '启智孵化管道',
    hotPapers: '热门论文项目',
    watch: '关注',
    star: '点赞',
    fork: '派生',
    noReposfound: '未找到匹配的项目。',
    source: '自建',
    mirrors: '镜像',
    collaborative: '协作',
    forks: '派生',
    selectRepo: '选择项目',
    selectRepoPlaceholder: '搜索项目名称...',
    cancelToping: '取消置顶',
    topping: '置顶',
    toppingSuccess: '置顶成功！',
    cancancelTopingSuccess: '取消置顶成功！',
    deleteThisRepos: '删除本项目',
    delete_notices_2: '- 此操作将永久删除项目 <strong>{repos}</strong>。包括该项目中的代码、任务、合并请求等内容',
    sureReposName: '输入项目名称以做确认：',
    repos_name1: '项目名称',
    deleteReposNameError: '项目名称输入错误！',
  },
  timeObj: {
    ago: '{msg}前',
    from_now: '{msg} 之后',
    now: '现在',
    future: '将来',
    '1s': '1 秒',
    '1m': '1 分钟',
    '1h': '1 小时',
    '1d': '1 天',
    '1w': '1 周',
    '1mon': '1 个月',
    '1y': '1 年',
    seconds: '{msg} 秒',
    minutes: '{msg} 分钟',
    hours: '{msg} 小时',
    days: '{msg} 天',
    weeks: '{msg} 周',
    months: '{msg} 个月',
    years: '{msg} 年',
    raw_seconds: '秒',
    raw_minutes: '分钟',
  },
  modelObj: {
    model_label: '选择模型',
    model_select_placeholder: '选择模型',
    model_export_placeholder: '请选择模型文件',
    model_select: '选择模型',
    model_current_repo: '本项目',
    model_my: '我拥有的',
    model_collaborate: '我协作的',
    model_collected: '我收藏的',
    model_my_migrate: '我迁移的',
    model_public: '公开模型',
    model_recommend: '平台推荐模型',
    model_migrate: '外部迁移模型',

    model_search_placeholder: '搜索模型名称...',
    model_selected: '已选模型',
    model_ok: '确定',
    model_most: '最多不超过 {msg} 个模型',
    model_not_equal_file: '不能选择相同名称的模型',
    model_exceeds_failed: '模型大小超过',
    model_should_same_model: '请选择同一模型下的文件',
    model_search: '搜索模型',
    model_square_empty: '空荡荡的，什么都没有',
    model_suport_file_tips: '模型文件支持的格式为 [ckpt, pb, h5, json, pkl, pth, t7, pdparams, onnx, pbtxt, keras, mlmodel, cfg, pt]',
    boot_file_helper: '启动文件是您程序执行的入口文件，必须是以.py结尾的文件。比如train.py、main.py、example/train.py、case/main.py。',
    can_online_infer: '可体验',
    can_fine_tune: '可微调',
    model_sdk_use_way: '模型SDK使用方式',
    codeUseDlgTriggerTxt: '在OpenI如何使用模型',
    codeUseDlgTitle: '如何在OpenI协作平台使用模型',
    codeDownDlgTitle: '如何在OpenI协作平台下载文件',
    migrate_external_model: '迁移外部模型',
    external_model_name: '外部模型名称',
    migrate_external_model_name_tips: '目前仅支持迁移HuggingFace的模型，请输入其模型名称，如：THUDM/chatglm3-6b',
    openi_model_repo_url: '启智模型仓库URL地址',
    migrate_model_should_be_public: '迁移的模型须公开',
    migrate_model: '迁移模型',
    please_enter_right_external_model_name: '请输入正确的外部模型名称',
    migrate_external_model_failed: '迁移外部模型失败！',
    create_model_migrate_loading_content: '创建模型迁移中，请稍后~',
    create_model_migrate_exists: '迁移的模型已存在，查看 <a href="{url}">模型详情</a>。',
    migrate_from: '正在从 {url} 迁移',
    migrate_watting: '等待迁移',
    migrating: '迁移中',
    migrate_success: '迁移成功',
    migrate_failed: '迁移失败',
    migrate_failed_tips: '模型迁移失败！请',
    migrate_retry: '重新迁移',
    migrate_try_later: '，或者稍后再试',
    re_migrate_failed: '重新迁移失败！',
    sync_now: '立即同步',
    model_sync: '模型同步更新',
    current_size: '当前大小',
    new_size: '最新大小',
    status_add: '新增',
    status_del: '删除',
    status_update: '有更新',
    start_sync: '开始同步',
    model_no_update_tips: '模型文件无变化，无需更新',
    model_sdk_tips1: '## 下载启智平台文件到本地文件夹：\n *文件大于{fileSize}时使用openi SDK下载，请根据具体的 **本地保存路径** 修改下列代码中的参数* \n#### 使用Python代码下载',
    model_sdk_tips2: '#### 使用命令行下载',
    model_sdk_tips3: '\n关于 `openi` SDK库的安装及使用方式请参考 <a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/model/sdk">使用帮助</a>。',
    model_download: '下载',
    model_source: '源模型：',
    model_name1: '模型名称',
    deleteThisModel: '删除本模型',
    deleteThisModelTips: '删除模型是永久性的，无法撤销的，请您谨慎操作。',
    delete_notices_2: '- 此操作将永久删除模型 <strong>{model}</strong>。',
    sureModelName: '输入模型名称以做确认：',
    deleteModelNameError: '模型名称输入错误！',
  },
  datasetObj: {
    dataset_label: "数据集",
    dataset_select_placeholder: "选择数据集",
    eval_select_placeholder: "最多选择5个评测数据集",
    dataset_select: "选择数据集",
    dataset_search_placeholder: "搜数据集名称",
    dataset_unziping: "正在解压缩",
    dataset_success: "解压成功",
    dataset_unzip_failed: "解压失败",
    dataset_status: '解压状态',
    dataset_exceeds_failed: "数据集大小超过",
    dataset_my_upload: "我上传的",
    dataset_current_repo: "本项目",
    dataset_public: "公开数据集",
    dataset_relate: "关联数据集",
    dataset_collected: "我收藏的",
    dataset_selected: "已选数据集",
    dataset_ok: "确定",
    dataset_not_equal_file: "不能选择相同名称的数据集",
    dataset_most: "最多不超过 {msg} 个数据集",
    dataset_file_was_deleted: "文件已经被删除",
    dataset_sdk_use_way: '数据集SDK使用方式',
    codeUseDlgTriggerTxt: '在OpenI如何使用数据集',
    codeUseDlgTitle: '如何在OpenI协作平台使用数据集',

    create_new_dataset: '新建数据集',
    dataset_name1: '数据集名称',
    dataset_name: '数据集英文名称',
    dataset_zh_name: '数据集中文名称',
    dataset_description: '数据集描述',
    select_category: '选择分类',
    task: '研究方向/应用领域',
    application: '应用领域',
    select_task: '选择研究方向/应用领域',
    dataset_name_tooltips: '请输入字母、数字和-_ .，以数字或字母开头和结尾，最长100个字符。',
    dataset_name_cn_tooltips: '请输入中文、字母、数字和-_ .，最长100个字符。',
    category: '分类',
    license: '授权许可',
    license_helper: '选择授权许可文件',
    dataset_name_required1: '请输入数据集中文名称',
    dataset_name_required2: '输入不符合数据集名称规则',
    dataset_name_required3: '请输入数据集英文名称',
    dataset_description_required: '请输入数据集描述详情',
    category_required: '请选择分类',
    select_task_required: '请选择研究方向/应用领域',
    dataset_repo_tips: '因每个项目只能创建一个数据集，此处仅能指定未创建数据集的项目',
    exampleDataset: '示例数据集',
    selectOpeniDataset: '选择平台数据集',
    buildDatasetTips: '如何构建数据集',
    create_public_tips: '*默认创建的数据集为公开数据集，可在数据集页面将其设置为私有数据集',
    dataset_owner: '拥有者',
    name: '名称',
    dataset_acess: '数据集权限',
    dataset_size: '数据集大小',
    hasNoIntroForModel: '还没有详细的数据集介绍',
    createModelIntro: '创建数据集介绍',
    dataset_intro: '数据集介绍',
    use_dataset: ' 使用数据集',
    deleteDataFileConfirmTips: '请确认是否删除当前文件 {name}？',
    dataFileDeleteFailed: '文件删除失败',
    dataDownloadAll: '下载全部数据集文件',
    createDataset: '创建数据集',
    deletCollaboratedTitle: '删除协作者',
    deletCollaboratedTips: '删除该协作者后，他将无法访问此数据集，继续操作吗？',
    dataBaseInfo: '数据集基本信息',
    dataSearch: '搜索中...',
    notFoundUser: '未找到匹配的',
    administrators: '管理员',
    writePermission: '可写权限',
    readPermission: '可读权限',
    datasetCollaborator: '数据集协作者',
    searchUsers: '搜索用户',
    addCollaborators: '增加协作者',
    managementTeam: '数据集管理团队',
    searchTeams: '搜索团队',
    addTeam: '添加团队',
    dangerousOperationZone: '危险操作区',
    deleteThisDataset: '删除本数据集',
    deleteThisDatasetTips: '删除数据集是永久性的，无法撤销的，请您谨慎操作。',
    sureDatasetName: '输入数据集名称以做确认：',
    deleteDatasetNameError: '数据集名称输入错误！',
    add_collaborator_success: '协作者添加成功！',
    add_team_success: '团队现在可以访问数据集',
    remove_collaborator_success: '协作者删除成功！',
    remove_team_success: '团队访问数据集的权限已被删除。',
    delete_notices_1: '- 此操作 <strong>不可以</strong> 回滚。',
    delete_notices_2: '- 此操作将永久删除数据集 <strong>{dataset}</strong>。',
  },
  imagesObj: {
    cloudbrain_images: '镜像',
    openIGPU: '启智GPU',
    c2netGPU: '智算GPU',
    images_search: '搜镜像Tag/描述/操作系统/安装的软件包/标签...',
    image_public: '平台推荐镜像',
    image_my: '我的镜像',
    image_collected: '我收藏的镜像',
    framework: '框架',
    version: '版本',
    frameworkName: '框架名称',
    frameworkVersion: '框架版本',
    pyVersion: 'Python版本',
    cudaVersion: 'Cuda版本',
    cannVersion: 'Cann版本',
    dtkVersion: 'Dtk版本',
    deleteTips: '你确认删除该镜像么？此镜像一旦删除不可恢复。',
    deleteSuccessTips: '删除成功',
    editImage: '修改镜像',
    submitImage: '提交镜像',
    appyImage: '申请成为平台推荐镜像',
    imageTag: '镜像Tag',
    imageDesc:'镜像描述',
    imageTagPlaceholder: '请输入镜像Tag',
    imageTagInputTips: '请输入字母、数字、_-.，最长50个字符，且以字母开头。',
    imageAdress: '镜像地址',
    imageAdressPlaceholder: '请输入镜像地址',
    imageAiCenterPlaceholder: '请输入智算中心JSON格式，如：\n[{"aiCenterId":"","trainJobUrl":"","notebookUrl":"","accDeviceModel":"",poolIds:""}]',
    operationSystem: '操作系统',
    operationSystemName: '操作系统名称',
    operationSystemNamePlaceholder: '请输入操作系统名称',
    operationSystemVersionPlaceholder: '请输入操作系统版本',
    pyPackge: 'Python依赖库',
    thirdPackages: 'Python依赖库及版本',
    thirdPackagesPlaceholder: `请输入安装的软件包及版本，一行一个，最多10行。如：\ntorch==1.13.1\ntransformers==4.25.1`,
    topic: '标签',
    topicPlaceholder: '输入完成后回车键完成标签确定',
    topicTips: `请在标签字段补充镜像中其他信息，如：适配的卡类型：<span class="light">T4</span>、<span class="light">Ascend 910</span>`,
    descr: '镜像简介',
    descrPlaceholder: '请输入镜像简介，不超过1000个字符',
    recommend: '推荐',
    notRecommend: '不推荐',
    submitTips: '代码目录/tmp/code不会随镜像提交，其他目录下新增的文件(夹)都会打包到镜像中。',
    submitNpuTip1: '目录/home/ma-user/work不会随镜像提交，其他目录都会打包到镜像中。',
    submitNpuTip2: '镜像保存过程中，Notebook将不可用，本任务状态也将由Running变为Waiting。',
    submitDcuTip1: '目录/home/ma-user/work不会随镜像提交，其他目录都会打包到镜像中。',
    submitDcuTip2: '镜像小于40G才能保存成功。镜像30天未使用系统将会清理，无法使用',
    submitApply: '提交申请',
    imageCommitting: '镜像提交中...',
    imageCommitSuccess: '镜像提交成功',
    imageCommitErrorTips1: '检测提交镜像是否大小超过20G!',
    imageCommitErrorTips2: '检测提交镜像是否大小超过40G!',
    committing: '提交中',
    commitSuccess: '提交成功',
    commitFailed: '提交失败',
    recommendNeedReview: '推荐待审核',
    recommendReviewApproved: '通过推荐审核',
    recommendReviewFailed: '未通过推荐审核',
    applyForRecommend: '申请推荐',
    copyAdress: '复制地址',
    filterImages: '筛选镜像',
    filterImagesPlaceholderCuda: '框架名称/框架版本/Python版本/Cuda版本',
    filterImagesPlaceholderCann: '框架名称/框架版本/Python版本/Cann版本',
    filterImagesPlaceholderDtk: '框架名称/框架版本/Python版本/Dtk版本',
    imageTaskType: '适用任务类型',
    imageTaskTips: '适用于',
    approval_status: '评审状态',
    all_approval_status: '全部评审状态',
    pending_approval: '待审核',
    approved: '通过审核',
    not_approved: '未通过审核',
    none: '无',
    create_cloud_brain_mirror: '创建云脑镜像',
    not_recommend: '不同意推荐',
  },
  specObj: {
    resSelectTips: '「资源规格」是您运行该任务使用的硬件，为了更多人能够使用本平台的资源，请按照您的实际需求进行选择。',
    no_use_resource: '暂无可用资源'
  },
  datasets: {
    computer_vision: "计算机视觉",
    natural_language_processing: "自然语言处理",
    speech_processing: "语音处理",
    computer_vision_natural_language_processing: "计算机视觉、自然语言处理",
    machine_translation: "机器翻译",
    medical_imaging: "医学影像",
    question_answering_system: "问答系统",
    information_retrieval: "信息检索",
    knowledge_graph: "知识图谱",
    text_annotation: "文本标注",
    text_categorization: "文本分类",
    emotion_analysis: "情感分析",
    language_modeling: "语言建模",
    speech_recognition: "语音识别",
    automatic_digest: "自动文摘",
    information_extraction: "信息抽取",
    description_generation: "说明生成",
    image_classification: "图像分类",
    face_recognition: "人脸识别",
    image_search: "图像搜索",
    target_detection: "目标检测",
    image_description_generation: "图像描述生成",
    vehicle_license_plate_recognition: "车辆车牌识别",
    medical_image_analysis: "医学图像分析",
    unmanned: "无人驾驶",
    unmanned_security: "无人安防",
    drone: "无人机",
    vr_ar: "VR/AR",
    "2_d_vision": "2-D视觉",
    "2_5_d_vision": "2.5-D视觉",
    "3_d_reconstruction": "3D重构",
    image_processing: "图像处理",
    video_processing: "视频处理",
    visual_input_system: "视觉输入系统",
    speech_coding: "语音编码",
    speech_enhancement: "语音增强",
    speech_synthesis: "语音合成",
    ros_hmci_datasets: "开源开放社区",
    downloadtimes: '下载次数',
    downloadtimes1: '下载',
    citations: '引用次数',
    citations1: '引用',
    default: "默认排序",
    newest: "最新创建",
    oldest: "最早创建",
    recentupdate: "最近更新",
    leastupdate: "最少更新",
    moststars: "收藏数量",
    mostCollections: "最多收藏",
    mostusecount: "最多引用",
    alphabetasc: "字母升序",
    alphabetdesc: "字母降序",
    chinesename: "中文名",
    chinesenameasc: "中文名倒序",
    size: "大小",
    sort: "排序",
    unstarSuccess: "取消收藏成功！",
    starSuccess: "收藏成功！",
    platform_recommendations: '仅显示平台推荐',
    category: '分类',
    task: '研究方向/应用领域',
    license: '授权许可',
    publick_dataset: '公开数据集',
    my_dataset: '我拥有的',
    favorite_dataset: '我收藏的',
    recommend_dataset: '平台推荐数据集',
    collaborated_dataset: '我协作的',
    views: '查看',
    loadMore: '加载更多'
  },
  cloudbrainObj: {
    cloudbrain: '云脑',
    openi: '启智集群',
    c2net: '智算网络集群(Beta)',
    create: '新建',
    createTask: '新建任务',
    cluster: '算力集群',
    computeResource: '计算资源',
    sameTaskTips1: '您已经有 {count}个同类任务正在等待或运行中，已达到最大值，请停止任务再创建。',
    sameTaskTips2: '可以在 “<a href="/cloudbrains" target="_blank">我的工作台 &gt; 计算任务</a>” 查看您所有的计算任务。',
    pathTips1: '训练脚本存储在 <strong style="color:#010101">{code}</strong> 中，数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，预训练模型存放在运行参数 <strong style="color:#010101">{model}</strong> 中，训练输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips11: '训练脚本存储在 <strong style="color:#010101">{code}</strong> 中，数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，预训练模型存储在 <strong style="color:#010101">{model}</strong> 中，训练输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips2: '项目代码存储在 <strong style="color:#010101">{code}</strong> 中，数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，选择的模型存储在 <strong style="color:#010101">{model}</strong> 中，调试输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips3: '项目代码存储在 <strong style="color:#010101">{code}</strong> 中，数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，选择的模型存储在 <strong style="color:#010101">{model}</strong> 中。',
    pathTips4: '训练脚本存储在 <strong style="color:#010101">{code}</strong> 中，预训练模型存放在运行参数 <strong style="color:#010101">{model}</strong> 中，训练输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips5: '数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，模型文件存储在 <strong style="color:#010101">{model}</strong> 中，推理输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips6: '数据集位置存储在运行参数 <strong style="color:#010101">{dataset}</strong> 中，预训练模型存放在运行参数 <strong style="color:#010101">{model}</strong> 中，训练输出路径存储在运行参数 <strong style="color:#010101">{output}</strong> 中。',
    pathTips66: '数据集位置存储在运行参数 <strong style="color:#010101">{dataset}</strong> 中，预训练模型存放在运行参数 <strong style="color:#010101">{model}</strong> 中，训练输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    pathTips7: '数据集位置存储在运行参数 <strong style="color:#010101">{dataset}</strong> 中，模型存放在运行参数 <strong style="color:#010101">{model}</strong> 中，推理输出路径存储在运行参数 <strong style="color:#010101">{output}</strong> 中。',
    pathTips71: '推理脚本存储在 <strong style="color:#010101">{code}</strong> 中，数据集存储在 <strong style="color:#010101">{dataset}</strong> 中，模型存储在 <strong style="color:#010101">{model}</strong> 中，推理输出请存储在 <strong style="color:#010101">{output}</strong> 中以供后续下载。',
    basicInfo: '基本信息',
    paramsSetting: '参数设置',
    resourceSetting: '资源设置',
    runningStatus: '运行状态',
    basicParameters: '基本参数',
    otherParameters: '其他参数',
    parameters: '参数',
    valueAndContent: '数值&内容',
    taskPrepareTips: '任务正在准备中，喝杯水回来再看看~',
    waitCountStart: '您当前排队位置是第',
    waitCountEnd: '位',
    mindTorchHelper: '不想排队？查看如何一键将PyTorch迁移至MindSpore',
    task: '任务',
    taskList: '任务列表',
    taskName: '任务名称',
    appName: '应用名称',
    appList: '应用列表',
    taskNameTips: '只能以小写字母或数字开头且只包含小写字母、数字、_和-，不能以_结尾，最长36个字符。',
    taskNameTips1: '只能以小写字母开头，包含数字、小写字母和短横线(-)，长度为5～26个字符。',
    imageInnerUrlErrTips: '您指定的镜像地址不适用于该任务，请重新指定其它镜像。',
    imageUrlErrTips: '请输入合法的镜像地址。',
    taskDescr: '任务描述',
    taskDescrPlaceholder: '描述字数不超过255个字符',
    codeBranch: '代码分支',
    image: '镜像',
    selectImage: '选择镜像',
    selectImagePlaceholder: '选择镜像或输入镜像地址',
    dataset: '数据集',
    networkType: '访问Internet',
    allNetworkType: '全部网络',
    codeGenerate: '代码生成',
    noInternet: '否',
    hasInternet: '是',
    networkTypeDesc: '「访问Internet」是描述您的任务分配到的计算资源中心是否支持互联网访问的情况。选择“否”时可分配的计算资源中心更多，且依然可以使用启智平台上的数据集和模型。',
    resourceSpec: '资源规格',
    specPlaceholder: '请选择资源规格',
    specDescr: '资源说明',
    PointGainDescr: '积分获取说明',
    balanceOfPoints: '积分余额',
    points: '积分',
    canUseTime: '，预计可用',
    hours: '小时',
    versionCount: '版本数',
    runVersion: '运行版本',
    createTime: '创建时间',
    startRunTime: '开始运行时间',
    endRunTime: '结束运行时间',
    runDuration: '运行时长',
    refresh: '刷新',
    codePath: '代码存放路径',
    datasetPath: '数据集存放路径',
    modelPath: '模型存放路径',
    outputPath: '输出存放路径',
    codeObsPath: '代码obs地址',
    clusterAndComputeResource: '集群/计算资源',
    runParameter: '运行参数',
    addRunParameter: '新增运行参数',
    parameterName: '参数名',
    parameterValue: '参数值',
    customPath: '自定义路径',
    port: '端口',
    customPathTips: '自定义路径只允许输入小写字母和数字，首字符必须是字母，长度不超过32个字符; 端口号可选择范围为8000-8800',
    debug: '调试',
    reDebug: '再次调试',
    reInfer: '再次推理',
    stop: '停止',
    modify: '修改',
    delete: '删除',
    startUse: '开始使用',
    more: '更多',
    commitImage: '提交镜像',
    downloadModel: '模型下载',
    configurationInfo: '配置信息',
    taskRuntimeInfo: '任务运行简况',
    log: '日志',
    logFile: '日志文件',
    downloadLog: '下载日志',
    viewFullScreen: '全屏',
    exitFullScreen: '退出全屏',
    scrolledToTopTip: '您已翻阅到日志顶部',
    scrolledToBottomTip: '您已翻阅到日志底部',
    resourceOccupancy: '资源占用情况',
    modelDownload: '结果下载',
    lossPlot: 'loss',
    evalOverview: '评测结果概览',
    evalDetail: '评测结果详情',
    failedReason: '运行失败原因',
    publicImage: '公开镜像',
    recommendImage: '平台推荐镜像',
    myImage: '我的镜像',
    myFavImage: '我收藏的镜像',
    searchImagePlaceholder: '搜镜像Tag/描述/操作系统/安装的软件包/标签...',
    useImage: '使用',
    submitting: '提交中',
    submitFailed: '提交失败',
    checkImageSizeTips: '检测提交镜像是否大小超过20G！',
    maxTaskTips: '<p><span>*</span> 平台仅留存近 <span>30</span> 天的调试、训练、推理、评测任务结果；<span>超过 30 天的任务将不能下载结果和查看日志，且不能再次调试、训练和微调。</span></p>',
    datasetFiles: '数据集',
    fileWasDeleted: '文件已经被删除',
    debugTaskEmptyTitle: '未创建过调试任务',
    debugTaskEmptyTip0: '代码版本：您还没有初始化代码仓库，请先 <a href="{url}">创建代码版本</a>；',
    debugTaskEmptyTip1: '运行时长：最长不超过4个小时，超过4个小时将自动停止；',
    debugTaskEmptyTip2: '数据集：云脑1提供 CPU / GPU 资源，云脑2提供 Ascend NPU 资源，调试使用的数据集也需要上传到对应的环境；',
    debugTaskEmptyTip3: '使用说明：可以参考启智AI协作平台 <a href="{url}" target="_blank">帮助中心</a>。',
    onlineInferTaskEmptyTitle: '未创建过在线推理任务',
    onlineInferEmptyTip2: '数据集：云脑1提供 CPU / GPU 资源，云脑2提供 Ascend NPU 资源，在线推理使用的数据集也需要上传到对应的环境；',
    superTaskEmptyTitle: '未创建过超算任务',
    generalTaskEmptyTitle: '未创建过通用任务',
    generalTaskEmptyTip1: '该任务类型具有如下特点，需在 <a href="/computingpower/demand">算力资源</a> 页面提交使用申请并审核通过后才能使用：<br/>（1）提供Jupyter调试环境。<br/>（2）运行时间不限时，但需消耗积分。<br/>（3）支持开放端口。<br/>（4）不支持保存镜像，不支持再次调试。',
    deleteConfirmTips: '您确认删除该任务么？此任务一旦删除不可恢复。',
    deleteBatchConfirmTips: '您确认批量删除选中的任务么？任务一旦删除不可恢复。',
    deletingTips: '任务删除中，请稍后',
    tabTitDebug: '调试任务',
    tabTitTrain: '训练任务',
    tabTitInference: '推理任务',
    tabTitBenchmark: '评测任务',
    trainTaskEmptyTitle: '未创建过训练任务',
    trainTaskEmptyTip2: '数据集：云脑1提供 CPU / GPU 资源，云脑2提供 Ascend NPU 资源，训练使用的数据集也需要上传到对应的环境；',
    inferenceTaskEmptyTitle: '未创建过推理任务',
    inferenceTaskEmptyTip2: '数据集：云脑1提供 CPU / GPU 资源，云脑2提供 Ascend NPU 资源，推理使用的数据集也需要上传到对应的环境；',
    bootFileTips: '启动文件是您程序执行的入口文件，必须是以.py结尾的文件。比如train.py、main.py、example/train.py、case/main.py。',
    viewSample: '查看样例',
    tabTitOnlineInference: '在线推理',
    tabTitGeneral: '通用任务',
    allResultDownload: '下载全部结果',
    downloadDisplayMaxCountTips: '单目录下最多显示 {count} 个文件或文件夹。计算任务容器内结果存储配额为 {size} GiB，超出配额将会导致结果丢失。',
    file_sync_ing: "文件同步中，请稍候",
    file_sync_wait: "文件等待同步中，请稍候",
    file_sync_fail: "文件同步失败",
    eval_task_ing: "评测任务进行中，稍后再来看看",
    no_file_to_download: "没有文件可以下载，稍后再来看看",
    task_not_finished: "任务还未结束，稍后再来看看",
    retrieve_results: "重新获取结果",
    reuseLastResult: '复用上次结果',
    continue_helper: '勾选复用将拷贝上次训练任务输出结果文件',
    computeNode: '计算节点',
    computeNodeCount: '计算节点数',
    exportDataset: {
      exportDatasetTitle: '导出结果至数据集',
      exportDatasetTips: '<span style="color:red">*</span> 导出的文件最终可以在您选择的数据集下查看。',
      export_failed: '导出失败',
      export_has_same_file: '当前数据集已存在相同的文件',
      export_has_same_file1: '当前模型已存在相同的文件',
      export_exceed_storage: '当前文件大小已经超出存储限额',
      export_success: '导出成功',
      exporting: '正在导出',
      please_select_file: '请先选择文件',
      please_select_output_file: '选择结果文件',
      select_file: '选择文件',
      file_descr: '文件描述',
      no_dataset: '还未创建过数据集',
      create_dataset: '去创建数据集',
      please_select_dataset: '请先选择要导出到的数据集',
    },
    chartResourceUsage: '占有率(%)',
    chartTime: '时间(min)',
    scrollToTop: '滚动到顶部',
    scrollToBottom: '滚动到底部',
    migratingData: '数据迁移中',
    centerPending: '分中心排队中',
    imagePulling: '拉取镜像中',
    sdkUseWay: '通过c2net库访问方式',

    dialogTips: {
      title1: '使用在线推理提供webui或api服务时需要了解以下几点',
      tips1: "平台没有对外直接提供自定义端口对外提供服务，可以使用fastapi转发到对外暴露的指定的URL提供服务。",
      tips1_1: 'webui服务参考：',
      tips1_2: 'api服务参考：',
      tips2: '服务启动指令参考',
      tips3: '在线推理任务只有在任务终止状态下才有日志返回',
      
      tips61: '详细使用方法可查看',
      tips62: '使用样例代码仓',
      tips7: '不再提示',
      tips8: '关闭',
      tips9: 'OpenI在线推理部署须知',
    },
    codeUseDlgTriggerTxt: '代码中如何访问数据资源',
    codeUseDlgTitle: '如何在代码中通过c2net库方式获取模型、数据集和输出路径',
    sdkCodeTip1: '请使用c2net库方式在容器中访问相关资源，可参考<a target="_blank" href="https://openi.pcl.ac.cn/docs/index.html#/cloudbrain/codepath">使用帮助</a>。',
    sdkCodeTip2: '根据您选择的计算任务类型，指定的数据集、模型等，访问数据集和模型，回传结果的示例代码如下：',
    generalTaskSdkCodeTip0: '通用任务如何开放端口',
    generalTaskSdkCodeTip1: '运行以下命令可在环境中配置HTTP代理：',
    generalTaskSdkCodeTip2: '/root/bin/scc tunnel http http://127.0.0.1:7860 （端口号7860可自定义）',
    generalTaskSdkCodeTip3: '配置成功后，输出如下信息：',
    generalTaskSdkCodeTip4: '即可使用地址<code>https://be22fe9f-d140-474c-81f4-30fb068157b5.tunnel.paracloud.com</code>访问相应服务。',

    searchTaskName: '搜索任务名称...',
    searchTaskNameOrCreator: '搜索任务名称/创建者...',
    downloadReport: '下载此报告',
    cloudbrainTaskType: '任务类型',
    ComputingResourceInfo: '算力资源信息',
    repo: '项目',
    cloudbrainTaskName: '云脑侧任务',

    taskIsAutomaticStop: '任务是否自动停止',
    automaticStop: '自动停止',
    manualStop: '手动停止',
    automaticStopTips: '该任务将在运行时长超过您所选择的时长后，或积分余额不足时，自动停止。',
    manualStopTips: '该任务将由您手动停止或积分余额不足时自动停止。',
    customize: '自定义',
    numOfHours: '{num} 小时',
    customizeTimeLimitPlaceholder: '请输入1到24之间的整数',
    debugTaskTimeLimitTips: '调试任务有使用时长限制，超时将自动结束任务，<span>请在到时前自行保存调试结果。</span>',
    autoStopTimeTips: '{min} 分钟后，该调试任务将自动结束，请自行保存调试结果',

    forkRepo: 'Fork已有项目',
    newRepo: '新建项目',
    migrateRepo: '迁移外部项目',
    pullRequests: '合并请求',
    issues: '任务管理',
    selectRepo: '指定已有项目',
    nextStep: '下一步',
    previousStep: '上一步',
    instructionsForUse: '使用须知',
    setUp: '设置',
    aiTaskType: 'AI任务类型',
    newCloudbrainAiTask: '新建云脑（AI）任务',
    selectAiTaskTypeAndRepo: '选择AI任务类型和项目',
    specifyComputingResourcesAndRarameters: '指定计算资源和参数',
    dataPreparing: '数据准备中，请稍后~',

    selectTheTaskType: '选择你需要创建的任务类型。',
    debugTaskDesc: '交互编辑环境',
    debugTaskDescLong: '提供Jupyter或Modelarts交互式调试环境，适合早期模型的调试和构建。',
    debugTaskDescLong1: '调试任务运行超过4个小时将自动停止。',
    trainTaskDesc: '提交至任务队列',
    trainTaskDescLong: '适用于长时间执行，不需要频繁修改算法代码的场景。',
    inferenceTaskDesc: '超算算力计算任务',
    inferenceTaskDescLong: '支持在超算算力上运行多种应用。',
    onlineinferTaskDesc: '搭建实时推理界面',
    onlineinferTaskDescLong: '为模型提供在线部署功能，使用Gradio框架，生成实时推理界面。',
    generalTaskDesc: '提供Jupyter调试环境',
    generalTaskDescLong: '提供Jupyter调试环境，需在算力资源页面提交使用申请并审核通过后即可使用。',
    noAiTasksInThisRepo: '该项目下还没有计算任务',
    createNewAitask: '新建计算任务',
    visualization: '可视化',
    sourceFtName: '源微调任务名称',
    tensorBoardVisualization: 'TensorBoard可视化',
    viewVisualization: '查看TensorBoard可视化结果',
    startDebug: '开始调试',
    stopTask: '停止任务',
    taskTmpl: '计算任务模板',
    saveTaskTmpl: '保存为计算任务模板',
    saveNewModel: '导出为新模型',
    exportData: '导出数据',
    exportToDataset: '导出结果至数据集',
    deploymentExperience: '部署体验',
    aimTrainCompare: '训练对比',
    aimTrainCompareDlgTitle: '选择对比的训练任务',
    aimTrainCompareSelectTips: '请选择 {minCount} 至 {maxCount} 个任务进行训练对比！',
    aimVisualization: 'AIM可视化',
    batchDelete: '批量删除',
    deleteFailed: '删除失败',

    all: '所有',
    ihave: '我拥有的',
    iCollaborate: '我协作的',
    iCollect: '我收藏的',
    selectApp: '选择应用',
    cbOffline: '项目下的“云脑”页签即将下线',
    cbOffflineTips: '请到<a href="/cloudbrains/create">“我的工作台 > 计算任务”</a>页面查看该页面原有的计算任务。',
    exportOutputTis: '导出结果至数据集或者模型，请移步pc网页端',
    repoStorageTips: '计算任务容器内项目存储配额为 {size} GiB，请控制项目大小。',
    runningLimit: '您的账户可以同时创建{count}个{taskType}。',
    forbidPenetrationStatement: '禁止任何形式的穿透行为声明',
    penaltyTipContent: '本平台严禁任何形式的<span class="highlight">穿透行为</span>。违规者将被扣除算力积分、限制登录，严重者将承担<span class="highlight">法律责任</span>！',    
  },
  taskTmplObj: {
    tmplName: '模板名称',
    tmplNamePlacehoulder: '请输入模板名称，最多20个字符',
    tmplDescr: '模板描述',
    quickRunTmplTips: '一键运行计算任务模板',
    editTmplFile: '编辑模板文件',
    addTmpl: '新增模板',
    dragSortTips: '可拖动页签调整顺序',
    deleteTmplTips: '是否要删除当前计算任务模板？',
    completeTmplTips: '请完善第 {n} 个模板中的必填内容！',
    more: '更多',
    collapsed: '收起',
    edit: '编辑',
    run: '运行',
    runTmplForkTips: '您对本项目没有写入权限，无法新建计算任务，建议您fork本项目，然后再一键运行计算任务。',
    forkRepo: 'Fork本项目',
    runTmplFailedTips: '运行模板失败！',
    runTmplWithConfigsErrorTips: '模板配置异常，无法正常运行！',
    useTaskTmpl: '使用任务模板',
    saveTaskTmpl: '保存计算任务模板',
    unAvailableTmplSpec: '模板资源规格"{msg}"因权限或资源不存在等原因，<span style="color:red">目前不可用</span>',
    unAvailableTmplImage: '模板镜像"{msg}"因权限或资源不存在等原因，<span style="color:red">目前不可用</span>',
    unAvailableTmplBranch: '模板代码分支"{msg}"因权限或资源不存在等原因，<span style="color:red">目前不可用</span>',

    taskTmpl: '计算任务模板',
    publicTmpl: '公开模板',
    recommendTmpl: '平台推荐模板',
    runTimes: '运行次数',
    searchTaskTmpl: '搜索计算任务模板名称',
    createTaskTmpl: '新建计算任务模板',
    myCreated: '我创建的',
    myCollected: '我收藏的',
    deleteTaskTmplConfirmTips: '是否确认删除当前计算任务模板？',
    tmplAccessRight: '模板权限',
    accessRight: '权限',
    collectedNum: '收藏次数',
    tagsAndDescr: '标签及描述',
    modelDatasetAndRepo: '模型、数据集及代码',
    cancelRecommend: '取消推荐',
    setRecommend: '设为推荐',
    cancelRecommendSuccess: '取消推荐成功',
    setRecommendSuccess: '设为推荐成功',
    tmplCoreElements: '核心要素',
    editTmpl: '编辑模板',
    tmplInfo: '模板信息',
    tmplTags: '模板标签',
    tagsPlaceholder: '输入完成后回车键完成标签确定，最多输入10个',
    editTaskTmpl: '编辑计算任务模板',
    createNewTaskTmpl: '新建计算任务模板',
    createTaskTmplErrTips: '请完善计算任务模板信息',
    taskTmplSaveTips: '计算任务模板保存中，请稍后',
    taskTmplSaveFailedTips: '保存计算任务模板失败',
    taskTmplReferencedRepo: '引用过该代码仓的计算任务模板',
  },
  superComputeObj: {
    mmlSparkDescr: `MMLSpark全称为Microsoft Machine Learning for Apache Spark，支持用户运行自制容器镜像，且赋予了用户容器内root权限。用户可直接使用平台提供的微软的MMLSpark。\n注：MMLSpark是微软提供针对机器学习环境的Spark版本(<a target="_blank" href="https://github.com/Azure/mmlspark">https://github.com/Azure/mmlspark</a>)，关于mmlspark可参考论文：<a target="_blank" href="https://arxiv.org/pdf/1810.08744.pdf">https://arxiv.org/pdf/1810.08744.pdf</a>`,
  },
  modelSquare: {
    llmHeader: '模型体验',
    chatGlm_intro: '是一个开源的、支持中英双语的对话语言模型，由智谱AI提供。',
    llama2: 'is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters. This is the repository for the 7B fine-tuned model, optimized for dialogue use cases and converted for the Hugging Face Transformers format.',
    dialogtips1: '你好👋！欢迎体验大模型知识库问答',
    dialogtips21: '此体验基于',
    dialogtips22: '语言模型与m3-base向量模型',
    dialogtips3: '请在右侧选择直接与模型对话或基于本地知识库问答',
    dialogtips4: '知识库问答模式，选择知识库名称后，即可开始问答。',
    dialogtips5: '如有需要可以在选择知识库名称后上传文件/文件夹至知识库，或从知识库中删除文件。',
    dialogtips6: '模型已成功加载，可以开始对话，或从右侧选择模式后开始对话',
    promptPlaceholder: '请输入提问内容...(Ctrl + Enter = 换行, 按回车键进行提交)',
    dialogModeSelect: '请选择使用模式',
    dialogLLM: 'LLM 对话',
    dialogKb: '知识库问答',
    configKb: '配置知识库',
    updatekb: '更新已有知识库选项',
    recreateKb: '向量库重构中，请耐心等待，请勿刷新或关闭网页',
    selectKb: '请选择要加载的知识库:',
    createKb: '新建知识库',
    deleteKb: '删除本知识库',
    deleteKbTips: '确定删除{knowledgeValue}知识库吗？',
    deleteVbTips: '确定删除已选择的知识库文件吗？',
    uploadFile: '上传文件',
    uploadFileTips1: '将文件拖到此处，或<em>点击上传</em>',
    uploadFileTips2: '单个文件上传大小限制为1MB • HTML, MD, JSON, CSV, TXT, XML, DOCX',
    addFileToKb: '添加文件到知识库',
    manageFile: '管理文件',
    deleteKbFileSelect: '请从知识库已有文件中选择要删除的文件',
    deleteKbFile: '从知识库中删除文件',
    recreateKbSuccess: '{knowledgeValue}向量库重构成功',
    noPermission: '您没有权限操作',
    fileExit: '文件已经存在',
    fileExceed: '文件超过1MB',
    fileError: '文件错误,请重新上传!',
    fileTypeError: '文类型件错误,请重新上传!',
    fileUploadSuccess: '{fileName}文件上传成功!',
    kbName: '知识库名称',
    createKbPlaceholder: '新知识库名称只能是数字和字母',
    vectorType: '向量库类型',
    embedModel: 'Embedding 模型',
    cancel: '取 消',
    create: '新 建',
    ok: '确 定',
    kbNameDetect1: '名称不能为空',
    kbNameDetect2: '名称只能是数字和字母',
    chatExceedCount: '超出使用次数，无法体验模型服务！',
    useNotice: '使用体验须知',
    agreeNotice: '同意 <a href="/home/model_privacy" target="_blank"> 《OpenI启智社区AI协作平台免责声明和服务使用规范》 </a>中所述内容 <p style="text-align: center;margin-top: 1rem;color: red;">温馨提示：不合理使用可能会被封号!</p>',
    modelProvide: '《免责声明和服务使用规范》',
    modelNotExist: '模型不存在',

    maxTries: '限量体验{maxTries}次',
    modelChatTask: '创建模型在线体验任务',
    createChatTips1: '单击下方按钮创建在线体验任务，创建成功后可在线体验{expireMinutes}分钟',
    createChatTips2: '本人创建的在线体验任务只限本人体验',
    createChatTips3: '您已经创建过当前模型的在线体验任务，点击下方按钮直接进入体验界面',
    createChatBtns1: '创建在线体验任务',
    createEvalBtns1: '创建评测任务',
    createChatBtns2: '在线体验',
    experienceTime: '体验倒计时：',
    uploadFIleLimit: '最多上传10个文件',
    inputNotEmpty: '输入内容不能为空！',
    sessionChating: '会话加载中，不要心急哦！',
    sessionSding: '图像生成中，不要心急哦！',
    chatBanned: '您的帐户被禁止登录，请与网站管理员联系',
    chatIllegal: '非常抱歉，作为一个人工智能助手我只能提供客观的信息。您还有什么要问的吗？',
    chatExpireMins: '体验时间超过{expireMinutes}分钟，需重新创建[在线体验任务]({locaRefresh})',
    chatExpired: '对话已过期，请重新创建对话',
    stopExperience: '结束体验',
    experienceDuration: '已体验时长',
    requireTimeout: '请求超时，请稍后再试',
    sdPlaceholder: '请使用英文prompt描述想要生成的画面内容。',
    submitTips: 'Ctrl + Enter换行',
    negativePromptPlaceholder: '请描述不想要生成的画面内容。',
    width: '图宽',
    height: '图高',
    num_images_per_prompt: '图像数量',
    negative_prompt: '负向提示词',
    steps: '采样步数',
    seed: '随机种子',
    scheduler_name: '采样方式',
    guidance_scale: '提示词相关性',
    newChat: '全新对话',
    stopChat: '停止生成',
    stopedChat: '已停止生成',
    refreshChat: '重新生成',
    like: '喜欢',
    unlike: '不喜欢',
    chatHeaderTips: '你好👋！欢迎体验 {modelName} 模型',
    deepseekHeaderTips: '你好👋！欢迎体验 DeepSeek 多尺寸模型综合服务',
    //deepseekHeaderTips: '您好👋！欢迎体验DeepSeek智能问答服务！我们采用智能调度技术，可根据问题复杂程度自动匹配最佳参数规模的模型，为您提供精准高效的解答',
    systemPlaceholder: '请输入系统人设，例如“你是一个AI助手”',
    temperature: '温度',
    top_p: '多样性',
    repetition_penalty: '重复惩罚',
    max_tokens: '最大生成长度',
    system_message: '系统人设',
    history: '多轮对话',
    experienceStopTips: '任务停止中,请稍后!',
    experienceStopSuccess: '任务停止成功,该体验服务已经暂停!',
    modelFinetuen: '模型微调',
    pcMind: '鹏城 · 脑海',
    sdModelFinetuen: 'CV微调',
    sdModelFinetuenTask: 'CV微调任务',
    modelExperience: '模型体验',
    modelExperienceTips: '提供大模型在线体验功能，您可以根据自己的任务场景选择合适的模型和计算资源，创建模型在线体验任务，从而在线检验模型的反应效果。',
    modelEvaluateTips: '以opencompass提供的数据集为测试标准，对用户微调产生模型的性能（performance）进行评估。',
    largeModelsList: '大模型列表',
    newModelExperience: '新建模型体验任务',
    ModelExperienceDetail: '模型体验任务详情',
    ModelEvaluateDetail: '模型评测任务详情',
    modelEvaluate: '模型评测',
    modelPerEvaluate: '模型性能评测',
    modelSafeEvaluate: '模型安全评测',
    modelEvaluateTask: '模型性能评测任务',
    evaluationModel: '评测模型',
    sftFinetune: 'NLP微调',
    sftFinetuneTask: 'NLP微调任务',
    newSftFinetune: '创建NLP微调任务',
    newLoraFinetune: '创建CV微调任务',
    newComfyUi: '创建Comfy UI任务',
    sftFinetuneDetail: 'NLP微调任务详情',
    sftFinetuneLimit: '每个账户可以同时创建3个NLP微调任务',
    ModelExperienceLimit: '每个账户可以同时创建3个模型体验任务',
    ModelEvaluateLimit: '每个账户可以同时创建1个模型评测任务',
    sdLoraLimit: '每个账户可以同时创建3个CV微调任务',
    comfyuiLimit: '每个账户可以同时创建1个Comfy UI任务',
    sftFinetuneTips: '目前提供LoRA（Low-Rank Adaptation）训练模式，您可以根据自己的任务场景选择合适的训练数据、调整训练参数，从而实现理想的模型效果。',
    cvloraTips: 'LoRA是一种轻量化的模型调校方法，通过训练特定网络层的权重并插入到基础模型中，实现快速、高效且只需少量图片的训练，最终优化了模型的参数量和推理性能。',
    ComfyUiTips: 'Comfy UI 是一个基于节点的稳定扩散图形用户界面，主要用于构建高度灵活的图像生成工作流。它适用于数字艺术家、AI研究人员、内容创作者等多种用户群体',
    ComfyUiWarn: '服务正在启动中，请稍后再试！',
    uploadSound: '请上传声音模板',
    language: '语言: ',
    soundStyle: '声音风格: ',
    systemDefault: '系统默认',
    uploadSound1: '上传声音模板',
    dragDrop: '拖放音频至此处',
    outputAduio: '输出音频',
    appDev: '应用开发',
    relatedTools: '相关工具系统',
    inputLength: '输入字符超过限制',
    ttsPlaceholder: '请输入要转换成语音的文案，中、英文语音合成分别不超过82和250个字符...(Ctrl + Enter = 换行, 按回车键进行提交)',
    soundTemplateTips: '声音模板只支持mp3和wav格式文件',
    soundTemplateTips1: '声音模板仅支持单个文件',
    soundTemplateTips3: '上传声音模板目前只支持mp3,wav两种格式的音频文件，并且只支持单个文件',
    cvLoraTrain: 'CV微调',
    cvComfyui: 'Comfy UI',
    cvComfyuiTask: 'Comfy UI任务',
    modelArena: '大模型竞技场',
    send: '发送',
    newRound: '新开一轮',
    pleaseSelectModelAndConversation: '请选择模型后进行对话',
    model_name1: '模型名称',
    model_name: '模型英文名称',
    model_zh_name: '模型中文名称',
  },
  modelFinetune: {
    foldParameters: '折叠参数',
    expandParameters: '展开参数',
    epochs: '需要执行的训练总轮数',
    learningRate: 'AdamW 优化器的初始学习率',
    batchSize: '每张卡处理的样本数量',
    valSize: '验证集占全部样本的百分比',
    evalSteps: '每隔多少步进行验证',
    saveSteps: '每两次断点保存间的更新步数',
    maxsamples: '每个数据集使用的最大样本数',
    computeType: '是否使用混合精度训练。',
    gradientAccumulation: '梯度累计的步数',
    lRScheduler: '采用的学习率调节器名称',
    maximumGradientNorm: '用于梯度裁剪的范数',
    cutoffLen: '输入序列分词后的最大长度',
    preprocessingNumWorkers: '用于处理的进程数',
    loggingSteps: '每两次日志输出间的更新参数',
    warmupSteps: '学习率预热采用的步数',
    packing: '在有监督微调阶段将序列打包为相同长度的样本',
    optim: '使用的优化器：adamw_torch、adamw_8bit 或 adafactor',
    loraRank: 'LoRA 矩阵的秩大小',
    loraAlpha: 'LoRA 缩放系数大小',
    loraDropout: 'LoRA 权重随机丢弃的概率',
    loraTarget: '应用 LoRA 的模块名称。使用英文逗号分隔多个名称',
    additionalTarget: '除 LoRA 层以外的可训练模块名称。使用英文逗号分隔多个名称',
    maxTaskTips: '<p><span>*</span> 平台仅留存近 <span>30</span> 天的微调任务结果；<span>超过 30 天的任务将不能下载结果和查看日志，且不能再次微调。</span></p>',
    maxEvalTaskTips: '<p><span>*</span> 平台仅留存近 <span>30</span> 天的评测任务结果；<span>超过 30 天的任务将不能查看评测结果和日志。</span></p>',
    max_epoch: '迭代轮次',
    max_epoch_tips: '迭代轮次，控制训练过程中的迭代轮数。',
    io_strategy: '模型策略',
    io_strategy_tips: '--',
    keep_interval_update: '模型保存间隔',
    keep_interval_update_tips: '--',
    save_interval_update: '保存的迭代步数',
    save_interval_update_tips: '每隔多少个step，保存',
    lr: '学习率',
    lr_tips: '--',
    vitual_pipeline_model_parallel_size: '虚拟流水线并行度',
    vitual_pipeline_model_parallel_size_tips: '--',
    pipeline_model_parallel_size: '流水线并行度',
    pipeline_model_parallel_size_tips: '流水线并行，把模型按照神经元的层次进行拆分，不同层放到不同的 GPU 上去计算',
    tensor_model_parallel_size: '张量并行度',
    tensor_model_parallel_size_tips: '张量并行，也就是联合多个 GPU 同时做一个张量计算，比如说矩阵乘法',
    num_micro_batch: '微批处理数量',
    num_micro_batch_tips: '"微批处理数量取值范围是[1,32]，表示在每次训练迭代中累加的微批处理数。微批处理数量设置较大可以加速训练，但可能会导致内存问题。',
    micro_batch_size: '微批处理大小',
    micro_batch_size_tips: '一般只能是1, 2的话就会超显存，使用梯度累加代替',
    recomputer_granularity: '重计算策略',
    recomputer_granularity_tips: '选择开启重计算可压缩显存使用量，但会造成吞吐量下降。在显存够用的情况下建议关闭',
    modelTraining: '模型训练',
    modelTesting: '模型测试',
    trainStart: '立即训练',
    imageLabeling: '图片打标',
    totalPic: '共',
    numPic: '张',
    clearAllPic: '清空所有图片',
    addPic: '添加图片',
    captionMethod: '打标算法',
    captionthres: '打标阈值',
    modelTrigger: '模型触发词',
    modelTriggerph: '请输入触发词',
    captioning: '打标',
    imgUploading: '图片上传中...',
    sureClearAllPic: '是否要删除所有图片?',
    sureClearOnePic: '是否要删除本张图片?',
    clearAllPicSucc: '所有图片删除成功',
    clearAllPicFail: '所有图片删除失败',
    clearOnePicSucc: '图片删除成功',
    clearOnePicFail: '图片删除失败',
    autoCaption: '图片自动打标中...',
    trainProgress: '训练进度',
    currentSteps: '当前步数/总步数',
    trainingRounds: '训练轮数/总轮数',
    trainParameters: '训练参数',
    viewLoss: '查看loss',
    selected: '已选择',
    startGenerateImg: '开始生图',
    sampleImage: '实时样图',
    sampleImageGenerate: '样图生成中',
    trainProcessing: '数据处理和模型加载中...',
    trainingProgress: '训练中',
    trainingCompleted: '训练完成',
    loraModelName: 'LoRA模型',
    picWidth: '图片宽度（Width）',
    picHeight: '图片高度（Height）',
    loraRandomSeed: '随机种子 （Random Seed）',
    loraSamplingSteps: '采样步数 （Sampling Steps）',
    loraCFGScale: '提示词引导系数 （CFG Scale）',
    loraNegativePrompt: '负向提示词 （Negative Prompt）',
    loraInputPrompt: '请输入prompt!',
    capationAddPic: '为所有图片添加标签',
    capationAddBegin: '添加到行首',
    capationAddEnd: '添加到行尾',
    capationAddMsg: '标签输入不能为空！',
    ProfessionalParameters: '专业参数',
    useBasicModel: '使用底模',
    Repeat: '单张次数',
    Epoch: '循环轮次',
    totalSteps: '总步数',
    uploadImgCalc: '上传图片后计算',
    Prompt: '提示词',
    ProfessionalSetting: '专业设置',
    loraPromptPlace: '训练过程中会根据提示词实时生成样图',
    uploadImg: '上传图片',
    uploadImgAccept: '文件格式不符合要求，请上传.jpg, .jpeg, .png格式的文件',
    dragUploadImg: '拖拽图片到这里上传',
    uploadMaxImg: '最多添加 200 张图片，支持 PNG / JPG / JPEG ',
    uploadHavedImg: '上传已有图片集',
    uploadImgTips: '请保证图片和打标文件一一对应，zip包内不能包含多级目录，zip包名称和文件名称总字符数低于255',
    uploadImgTips1: '未检测到文件',
    uploadImgTips2: '当前最大允许上传200个图片文件',
    uploadImgTips3: '文件格式不符合要求，请上传 PNG / JPG / JPEG 格式的图片',
    cvTaskfaildTips: '任务已停止或失败请重新创建任务！',
    evalDatasetLimit: '评估数据集条数',
    sftFinetuneName: '微调任务名称',
    selectBaseModel: '选择基础模型',
    selectFtModel: '选择NLP微调模型',
    evalTips: '模型能力评测以 opencompass 提供的数据集为测试标准，仅供参考。',
    evalTaskCategory: '任务类别',
    evalScore: '得分',
    evalModelInput: '模型输入',
    evalModelOutput: '模型输出结果',
    standerAnswer: '标准答案',
    evalModelOutAnswer: '模型输出答案',
    allResult: '全部结果',
    correctResult: '正确结果',
    wrongResult: '错误结果',
    allDataset: '全部数据集'
  },
  userRole: {
    userRoleManagement: '用户角色管理',
    newOpRole: '新建操作角色',
    editOpRole: '编辑操作角色',
    viewOpRole: '查看操作角色',
    newReRole: '新建算力资源角色',
    editReRole: '编辑算力资源角色',
    viewReRole: '查看算力资源角色',
    newStorageRole: '新建存储资源角色',
    editStorageRole: '编辑存储资源角色',
    viewStorageRole: '查看存储资源角色',
    newContainerStorageRole: '新建容器内储存配额角色',
    editContainerStorageRole: '编辑容器内储存配额角色',
    viewContainerStorageRole: '查看容器内储存配额角色',
    roleName: '角色名称',
    roleType: '角色类型',
    roleDescription: '角色描述',
    isItDefault: '是否默认',
    viewDetail: '查看详情',
    default: '默认',
    notDefault: '非默认',
    reCategory: '算力资源类',
    opCategory: '操作类',
    storageCategory: '存储资源类',
    allRoleType: '全部角色',
    deleteRoleConfirm: '删除【默认】角色会影响所有用户，',
    deleteRoleConfirm1: '是否确认删除当前 {name} 角色？',
    roleSelected: '请指定角色拥有的权限（可多选）',
    roleSelectedTips: '全选/全不选',
    allUserDefault: '所有用户默认',
    UserPermissionConfig: '用户权限配置',
    OrgPermissionConfig: '组织权限配置',
    allOpCategory: '全部操作类角色',
    allReCategory: '全部算力资源类角色',
    allStCategory: '全部存储资源类角色',
    userName: '用户名',
    OrganizationName: '组织名',
    opCategoryRole: '操作类角色',
    reCategoryRole: '算力资源类角色',
    stCategoryRole: '存储资源类角色',
    codeSizeLimit: '运行的计算任务容器内code目录存储配额',
    outputSizeLimit: '运行的计算任务容器内output目录存储配额',
    pleaseEnterContent: '请输入内容',
    pleaseEnterRoleContent: '请输入角色名称搜索...',
    userId: '用户ID',
    organizationId: '组织ID',
    editUserPermissions: '编辑用户权限',
    editOrgPermissions: '编辑组织权限',
    OperationalPermissions: '操作类权限',
    detail: ' 详情',
    permissionList: '权限清单',
    updatePermissions: '更新权限',
    resourcePermissions: '的算力资源权限清单',
    CResourcePermissions: '算力资源类权限',
    StoragePermissions: '存储资源类权限',
    permissionUpdateUnixDesc: '按权限更新时间降序',
    permissionUpdateUnixAsc: '按用户更新时间升序',
    permissionCreatedUnixDesc: '按用户创建时间降序',
    permissionCreatedUnixAsc: '按用户创建时间升序',
    orgPermissionCreatedUnixDesc: '按组织创建时间降序',
    orgPermissionCreatedUnixAsc: '按组织创建时间升序',
    batchSetOrCancel: '批量设置或取消用户角色',
    enterUserId: '请输入需设置权限的用户名单',
    failed: '失败了',
    times: '个',
    failedUserList: '失败用户列表',
    addAcessSuccess: '增加权限成功',
    cancelAcessSuccess: '取消权限成功',
    operaNodeTips1: '运行训练任务时可以使用',
    operaNodeTips2: '节点的',
    operaNodeTips3: '计算资源',
    operaTaskTips1: '可以同时运行',
    operaTaskTips2: '个',

  },
  org: {
    organization: '组织',
    createOrg: '新建组织',
    searchOrg: '搜索组织',
    orgName: '组织名称',
    orgFullName: '组织全称',
    Members: '成员',
    Teams: '团队',
    orgTeam: '组织团队',
    orgMember: '组织成员',
    numMember: '名成员',
    numMembers: '名成员',
    numRepo: '个项目',
    numRepos: '个项目',
    unfold: '展开',
    fold: '收起',
    searchRepos: '搜索项目',
    searchModels: '搜索模型',
    searchDatasets: '搜索数据集',
    searchImages: '搜索镜像',
    customize: '自定义',
    selectedProjects: '精选项目',
    selectedModels: '精选模型',
    selectedDatasets: '精选数据集',
    customizeSelectedProjects: '自定义精选项目',
    customizeSelectedModels: '自定义精选模型',
    customizeSelectedDatasets: '自定义精选数据集',
    searching: '搜索...',
    remainNum: '还能推荐 {num} 个',
    maxProjects: '最多可选择 {num} 个公开项目',
    maxModels: '最多可选择 {num} 个公开模型',
    maxDatasets: '最多可选择 {num} 个公开数据集',
    order_newest: '最新创建',
    order_oldest: '最早创建',
    order_recentupdate: '最近更新',
    order_leastupdate: '最少更新',
    order_reversealphabetically: '按字母逆序排序',
    order_alphabetically: '按字母顺序排序',
    order_moststars: '点赞由多到少',
    order_feweststars: '点赞由少到多',
    order_mostforks: '派生由多到少',
    order_fewestforks: '派生由少到多',
    no_result: '空荡荡的，什么都没有',
    myOrg: '我的组织',
    orgDataset: '组织数据集',
    orgModel: '组织模型',
  },
  storage: {
    capacity_details: '存储容量明细',
    quota: '存储配额',
    data_usaged: '数据集已用',
    model_usaged: '模型已用',
    remaining_available: '剩余可用',
    upload_time: '上传时间',
    deleteModelConfirm: '是否确认删除当前模型 <span style="color:red;word-break: break-all;">{name}</span> ？',
    deleteModelConSuccess: '删除当前模型 {name} 成功！',
    deleteDataSetConfirm: '是否确认删除当前数据集 <span style="color:red;word-break: break-all;">{name}</span> ？',
    deleteDataSetSuccess: '删除当前数据集 {name} 成功 ！',
    feedback_issue: '反馈问题',
    remain_storage: '剩余存储配额',
    selected_file_size: '已选文件大小',
    exceedStorage: '已经超出存储限额',
    deleteBatchData: '您确认删除批量选中的数据集吗？一旦删除不可恢复',
    deleteBatchModel: '您确认删除批量选中的模型吗？一旦删除不可恢复',
    deletingTips: '文件删除中，请稍后',
    owenerTips: '请查看 {ownerName}（拥有者）的存储容量明细',
    storageOrgTips1: '申请更多配额，请单击',
    storageOrgTips2: '下载模板',
    storageOrgTips3: '填写好后发送至邮箱 secretariat@openi.org.cn',

  },
  evalCaterary: {
    Examination: "学科",
    Reasoning: "推理",
    Knowledge: "知识",
    Code: "代码",
    Math: "数学",
    Understanding: "理解",
    Language: "语言",
    Instruct: "指令跟随",
  },
  thirdPartyApp: {
    thirdPartyApp: '第三方应用',
    oauth2App: 'OAuth2应用',
    oauth2AppDescr: '（已认证过的OAuth2应用，用户授权后，该应用可获取用户的基本信息（用户id、用户名、用户头像链接）、电子邮箱、手机号码）',
    authStatus: '认证状态',
    canGetUserInfo: '可获得的用户信息',
    searchThirdPartyAppPlaceholder: '搜第三方应用名称',
    clientID: '客户端ID',
    appName: '应用名称',
    appCanGetUserInfo: '应用可获得的用户信息',
    appCreator: '应用创建者',
    authenticated: '已认证',
    notAuthenticated: '未认证',
    setAuthenticated: '通过认证',
    cancelAuthentication: '取消认证',
    basicInfo: '基本信息',
    basicInfoAll: '基本信息（用户id、用户名、用户头像链接）',
    email: '电子邮箱',
    phoneNumber: '手机号码',
    editOauth2AppAuthInfo: '修改OAuth2应用认证信息',
    authenticatedCanGetInfoTips: '用户授权后，该应用可获得如下用户信息',
    verify: '认证',
    cancelVerify: '取消认证',
    verifyAgain: '再次认证',
    cancelVerifyTips: '取消认证后，该应用将只能获得用户基本信息，不能获得用户电子邮箱、手机号码，是否继续操作？',
  },
  computingPowerObj: {
    computeResource: '算力资源',
    computeResourceDescr: '为了满足用户的个性化算力需求，启智社区可以根据用户的需求定制算力池，欢迎提交您的算力需求。',
    freeComputingPower: '普惠算力',
    paidComputingPower: '付费算力',
    paidComputingPowerTip: '付费算力及售后服务由合作伙伴提供',
    createNewComputingTask: '新建计算任务',
    createComputingTask: '创建算力任务',
    displayFilteringConditions: '显示筛选条件',
    priceRange: '价格区间',
    point_hr: '积分/卡时',
    use: '去使用',
    buyNow: '立即购买',
    provider: '提供方',
    systemDisk: '系统盘',
    computingPowerPartner: '算力合作伙伴',
    computingPowerOperationPlatform: '算力运营平台',
    chipManufacturers: '芯片厂商',
    accCardCount: '卡数',
  },
  dashboard: {
    welcomeTips: '欢迎来到 CacOps 智算服务平台',
    newUserGuide: '新用户指引',
    quickAccess: '快捷入口',
    createTask: '创建计算任务',
    taskDesc: '使用算力卡，创建调试、训练、推理等计算任务',
    myTaskCount: '我的计算任务',
    runningTasks: '运行中',
    totalGPUHourd: '累计运行',
    createProject: '创建项目',
    createRepoDesc: '创建代码仓，在计算任务中使用这些代码',
    uploadDatasetDesc: '上传数据集，在计算任务中使用这些数据集',
    uploadModelDesc: '上传AI模型，在计算任务中使用这些模型',
    oneClickCreate: '一键创建',
    remainingQuota: '剩余可用存储配额',
    occupiedStorage: '占用存储',
    datasetStorage: '数据集占用',
    modelStorage: '模型占用',
    credits: '算力积分',
    currentAvailable: '当前可用算力积分',
    currentAvailable1: '当前可用',
    totalGained: '总获取算力积分',
    totalGained1: '总获取',
    totalConsumed: '总消耗算力积分',
    totalConsumed1: '总消耗',
    announcements: '公告',
    moreAnnouncements: '更多公告',
    activities: '活动',
    weChatLinked: '微信已绑定',
    weChatNotLinked: '微信未绑定',
    datasetNum: '数据集',
    modelNum: '模型',
    unitPoints: '分',
    unitTask: '个',
    unitdata: '个',
    runtimeCards: '卡时',
    templateNum: '模板总数量',
    accumulatedRuns: '累计运行',
    unitTemplate: '次',
    heatmapLoading: '正在加载热图...',
    contributionCount: ' 最近一年贡献：{count} 次'
  },
  agentPortal: {
    taskRunningTip: '你有 {count} 个智能体正在运行，消耗 {numPoint} 积分/每小时',
    viewRunningAgents: '查看正在运行的智能体',
    bannerTitle: '开启您的 AI 智能体之旅',
    bannerDesc: '基于中国算力网强大算力底座，将前沿大模型能力一键部署，即可随时随地体验Al魅力。',
    searchPlaceholder: '搜索智能体',
    agentSquare: '智能体广场',
    runningAgents: '运行中的智能体',
    viewDetails: '了解详情',
    oneClickDeploy: '一键部署',
    deployFailed: '运行失败',
    deploying: '部署中',
    stop: '停止',
    startUsing: '开始使用',
    startSuccess: '启动成功',
    startFailed: '启动失败',
    stopSuccess: '停止成功',
    stopFailed: '停止失败',
    agentsRunning: '智能体 {names} 正在运行中',
    updated: '更新于',
    noData: '暂无数据',
  }
}

export default zh;
